<link type="text/css" href="/modules/translation/css/ui.multiselect.css" rel="stylesheet" />
<style> 
    /* multiselect styles */
    .multiselect {
        width: 420px;
        height: 200px;
    }
    .multiselect .available{
        
    }
</style>
<script type="text/javascript">
    $(function(){
        var $callback = $("#callback");

//    $.localise('ui-multiselect', {language: 'en'}); //,*/ path: 'js/locale/'
        $(".multiselect").multiselect();
       

//        $('#switcher').themeswitcher();
    });
    $('.clickme').live('click', function() {
        alert($("#export").serializeArray().toSource());
    });
</script>
<form method="post"  class="FormGrid" id="export"
    title="<?php echo $this->translate('Export to excel'); ?>"
    action="<?php echo $this->url(array('controller' => 'admin', 'action' => 'export-to-excel')) ?>"
    enctype="application/x-www-form-urlencoded">
    <input type="hidden" name="data[grid_params]" id="data[grid_params]" value='<?php echo $this->grid_params ;?>' />
    <label class="required" for="name"><?php echo $this->translate('Select language to export'); ?>:</label>
    <select class="multiselect" id="data[language_id]" name="data[language_id][]" multiple="multiple" >
               <?php foreach ($this->translateLanguages as $translateLanguage) {?>
                <option value="<?php echo $translateLanguage['id'];?>" ><?php echo $this->escape($translateLanguage['name']);?></option>
                <?php }?>
    </select>
   <!--  <a href="#" onclick="return false;" class="clickme">filter by</a>  -->
    <dl class="hz_form">
        <dt class="label">
        </dt>
        <dd class="err_color">
           <?php echo $this->errorMessages($this->errors['language_id']);?>
        </dd>
   </dl>
    
</form>