<?php
$this->headScript()->appendFile('/plugins/hfb/js/jquery.hfbSelect.js');
$this->headScript()->appendFile('/plugins/hfb/js/jquery.hfbSearch.js');
$this->headScript()->appendFile('/plugins/hfb/js/jquery.hfbList.js');
$this->headScript()->appendFile('/modules/admin/js/list.js');
$this->headScript()->appendFile('/plugins/jqueryui/i18n/jquery.ui.datepicker-' . $this->lang .'.js');
?>
<script type="text/javascript">

    initList('/' + CURR_LANG + '/contact/admin/contact-list/',{},function(me,data){
        //DELETE ajax action call
        $("#listContainer").find("a.delete").click(function(){
            if(!window.confirm("<?php echo $this->translate('Are you sure you want to delete this contact?\nThis operation has no undo.');?>")){
                return false;
            }
            $.ajax({
                type: "POST",
                data: {"contact_id":$(this).data('id')},
                url: '/' + CURR_LANG + '/' + 'contact/admin/contact-delete',
                success: function(data) {
                    if(data['success']){
                        if(data['message']){
                            $.flashMessenger(data['message'],{clsName:"ok"});
                        }
                        //reload list
                        updateList();
                    }
                    else{
                        if(data['message']){
                            $.flashMessenger(data['message'],{clsName:"err"});
                        }
                    }
                },
                error: function(data) {
                    alert(_('An error has occured retrieving data!'));
                }
            })
            return false;
        });
         $("#listContainer").find("a.show_more").click(function(){
            var id = $(this).data('id');
            $('#dialog_more_'+ id).dialog({modal:true});
            updateList();
         });
    });

   

    //init select filter
    $(document).ready(function(){

        $("#langFilter").change(function(){
            updateList('langFilter',$(this).val());
        });

        $('#searchExecute').click(function() {
            updateList('searchFilter', $('#searchFilter').val());
        });

        $("#all_export").click(function(){
            $('#form_contact').submit();
            return false;
        });

        var dates = $( "#fromFilter, #toFilter" ).datepicker({
            dateFormat: 'dd.mm.yy',
            autoSize: true,
            defaultDate: "+1w",
            changeMonth: true,
            numberOfMonths: 1,
            onSelect: function( selectedDate ) {
                var option = this.id == "fromFilter" ? "minDate" : "maxDate",
                instance = $( this ).data( "datepicker" ),
                date = $.datepicker.parseDate(
                instance.settings.dateFormat ||
                    $.datepicker._defaults.dateFormat,
                selectedDate, instance.settings );
                dates.not( this ).datepicker( "option", option, date );
                if(this.id == 'fromFilter'){
                    updateList('fromFilter', $('#fromFilter').val());
                }else{
                    updateList('toFilter', $('#toFilter').val());
                }
            }
        });

        $("#fromFilter").bind('keyup' ,function(){
            if($(this).val() != ""){
                updateList('fromFilter', $('#fromFilter').val());
            }
        });

        $("#toFilter").bind('keyup' ,function(){
            if($(this).val() != ""){
                updateList('toFilter', $('#toFilter').val());
            }
        });

        $("#from_delete").click(function(){
            if($('#fromFilter').val() != ""){
                $('#fromFilter').val("");
                updateList('fromFilter', $('#fromFilter').val());
            }
        });

        $("#to_delete").click(function(){
            if($('#toFilter').val() != ""){
                $('#toFilter').val("");
                updateList('toFilter', $('#toFilter').val());
            }
        });
        


});

</script>
<form id="form_contact" name="form_contact" action="/<?php echo $this->currLang; ?>/contact/admin/export">
    <div class="hcms_content_top">
        <h1><?php echo $this->translate('Contacts'); ?> <span class="hcms_button"><a id="all_export" href="#" style="margin:6px 0 0 0;" class="add button"><?php echo $this->translate('Export'); ?></a></span></h1>
        <span class="hcms_search">
            <input id="searchFilter" name="searchFilter" value="" />
            <span class="hcms_button"><a href="#" id="searchExecute"><?php echo $this->translate("Search"); ?></a></span>
        </span>
    </div>
    <div class="hcms_content">
        <div class="language">
            <?php if($this->singleLang === false){?>
            <label><?php echo $this->translate('Language'); ?></label>
            <select id="langFilter" name="langFilter">
                <option value="" selected="selected"></option>
                <?php foreach ($this->languages as $langCode => $lang) {
                ?>
                    <option value="<?php echo $langCode; ?>"><?php echo $this->escape($lang['name']); ?></option>
                <?php } ?>
            </select>
            <?php }?>
            <label><?php echo $this->translate('From date'); ?></label>
            <input id="fromFilter" name="fromFilter" value="" readonly/>
            <span id="from_delete" class="delete_from_to"></span>
            <label><?php echo $this->translate('To date'); ?></label>
            <input id="toFilter" name="toFilter" value="" readonly/>
            <span id="to_delete" class="delete_from_to"></span>
        </div>
        <table class="hcms_table adminList" width="100%">
            <thead>
                <tr>
                    <th><a href="#" class="sort" data-column="gender"><?php echo $this->translate('Gender'); ?><b></b></a></th>
                    <th><a href="#" class="sort" data-column="first_name"><?php echo $this->translate('First Name'); ?><b></b></a></th>
                    <th><a href="#" class="sort" data-column="last_name"><?php echo $this->translate('Last Name'); ?><b></b></a></th>
                    <th><a href="#" class="sort" data-column="street"><?php echo $this->translate('Street/Nr'); ?><b></b></a></th>
                    <th><a href="#" class="sort" data-column="zip"><?php echo $this->translate('ZIP'); ?><b></b></a></th>
                    <th><a href="#" class="sort" data-column="zip"><?php echo $this->translate('City'); ?><b></b></a></th>
                    <th><a href="#" class="sort" data-column="country"><?php echo $this->translate('Country'); ?><b></b></a></th>
                    <th><a href="#" class="sort" data-column="phone"><?php echo $this->translate('Phone'); ?><b></b></a></th>
                    <th><a href="#" class="sort" data-column="mobile"><?php echo $this->translate('Mobile'); ?><b></b></a></th>
                    <th><a href="#" class="sort" data-column="fax"><?php echo $this->translate('Fax'); ?><b></b></a></th>
                    <th><a href="#" class="sort" data-column="email"><?php echo $this->translate('Email'); ?><b></b></a></th>
                    <th style="width:300px"><a href="#" class="sort" data-column="description"><?php echo $this->translate('Description'); ?><b></b></a></th>
                    <th><a href="#" class="sort" data-column="language"><?php echo $this->translate('Language'); ?><b></b></a></th>
                    <th><a href="#" class="sort" data-column="posted"><?php echo $this->translate('Posted'); ?><b></b></a></th>
                </tr>
            </thead>
            <tbody id="listContainer">
            </tbody>
        </table>
        <div id="pager"></div>
    </div>
</form>
<script type="text/html" id="records_tpl">
    <% if (rows.length > 0){
    var rowClass = 'odd';
    %>
    <% for ( var i = 0; i < rows.length; i++ ){
    rowClass = (i % 2 == 0)? 'even':'odd';
    %>
    <tr class="<%=rowClass%>">
        <td>
           <%=rows[i].gender%>
        </td>
        <td>
            <%=rows[i].first_name%>
            <ul class="hcms_menu_actions">
             <li><a href="#" class="delete" data-id="<%=rows[i].id%>" data-type_id="<%=rows[i].type_id%>"><?php echo $this->translate('Delete');?></a></li>
            </ul>
        </td>
        <td>
            <%=rows[i].last_name%>
        </td>       
        <td>
            <%=rows[i].street%>
        </td>
        <td>
            <%=rows[i].zip%>
        </td>
        <td>
            <%=rows[i].city%>
        </td>
        <td>
            <%=rows[i].country%>
        </td>
        <td>
            <%=rows[i].phone%>
        </td>
        <td>
            <%=rows[i].mobile%>
        </td>
        <td>
            <%=rows[i].fax%>
        </td>
        <td>
            <%=rows[i].email%>
        </td>
        <td>
            <a class="show_more" data-id="<%=rows[i].id%>" href="javascript:void(0);"><%=rows[i].description_short%></a>
            <div style="display:none;" id="dialog_more_<%=rows[i].id%>" title="<?php echo $this->translate('Description');?>"><p><%=rows[i].description%></p></div>
        </td>
        <td>
            <%=rows[i].language%>
        </td>
        <td>
            <%=rows[i].posted%>
        </td>
    </tr>
    <% } %>
    <% } %>
</script>