<div class="introTxt">
    <h1>About Us</h1>
    <h2>HORISEN – Marketing Technology for Marketing Professionals.</h2>
</div>
<p>HORISEN has grown into a large business thanks to thousands of satisfied customers.</p>

<span class="qoutes">
    <p>“Who always does what he is already able to do, always remains what he already is.”</p>
    <p>Henry Ford</p>
</span>

<p>HORISEN provides a self-developed cloud based enterprise software (SaaS) that drives extraordinary results to businesses and
    organizations of any size. More than 1’200 customers take advantage of our services on a daily basis which only proves the 
    words. The experience gained through numerous projects allow us to help companies like yours keep growing. We like to stay in 
    the shadow while enjoying your business success with you.</p>
<p>We live in the world of extremely fast changing market and our customers highly depend on these changes. They mostly affect
    technology in terms of modernization and user-friendly services. Our mission consists of remaining innovative in terms of 
    continuously “reinventing” our business and services and adapt them to new market and technology trends.</p>
<p>Thanks to our professional approach and strong customer-orientation, we’ve become a reliable partner in many strategy-
    oriented marketing departments. Contact us and find out how HORISEN can help your business or organization with successful 
    marketing campaigns and achieving measurable results.</p>

<h3>More about HORISEN:</h3>
<ul>
    <li>Privately owned company founded in 2001.</li>
    <li>Headquarters in Rorschach, Switzerland.</li>
    <li>More than 50 employees</li>
    <li>More than 1’200 customers worldwide – from SMEs to Fortune 500 global companies.</li>
    <li>Our work touches various disciplines such as sociology, psychology, communications, branding, advertising, PR,
        customer experience management and digital and mobile technology.</li>
    <li>We focus on a cloud-based marketing business software (SaaS: Software-as-a-Service) which seamlessly integrates
        marketing with technology and is ideal for marketing experts.</li>
</ul>

<h2>Our Vision</h2>
<p>We strive to provide a single platform bringing all communication channels under one umbrella combining voice, web, mobile 
    and social media with classic offline media to become a single unified cross-media channel and a seamlessly integrated digital 
    customer experience. Our vision is seen through the image of a man surrounded with many “Little Helpers”. These little helpers 
    are invisible electronic pocket knives that work every day and can help you without restriction regardless of location, technology 
    or source compatibility.</p>

<h2>Our Mission</h2>
<p>HORISEN is changing the game by using a new approach to marketing technology. In today’s communication flow new
    customer groups are easier to be detected and targeted because the new methods are direct and fast. That’s why marketing 
    and technology have to be combined – to meet the customers’ needs and, at the same time, send the right data to the right 
    channels. We are convinced that using technology, every marketer achieves great success in the market. Knowing customer 
    requests, each activity has to be put in the right frame and this can be really exhausting for marketers. So, we take this part of 
    the work and leave you to use your own competences and time which will put you ahead of your competitors very soon!</p>

<h2>We meet our partners’ milestones</h2>
<p>Our main goal is to support organizations and businesses on their way to achieve professional success by providing quality 
    service to their customers. This is done thanks to our expertise, great and high-quality skilled team and many projects we 
    successfully implemented. We provide you creative ideas for your business, but also concrete project implementation support. 
    Because we understand your customers’ requirements, we can work in parallel with you.</p>

<h2>Philosophy</h2>
<p>Having time for your business for us means investing in your success. We invest time to understand your business. Your success
    is our success – and that is the key element for a long-lasting and successful partnership. The sustainability therefore provided is 
    the basis for future stable growth of both our companies.</p>

<h2>Philanthropy</h2>
<p>As a company, we strive to help the society in its sustainable development efforts.</p>

<p><span class="bold">Supporting social causes</span> – instead of small incentives to its clients, partners and other stakeholders HORISEN donates a certain 
    amount for social causes during Christmas season. Each year we choose a different institution or organization – we always 
    contribute to different areas and help the most endangered areas of society.</p>

<p><span class="bold">Internship</span> – with the support of our great team of experienced people, HORISEN is proud to introduce Internship program and
    help educate young people by developing their professional skills towards future development and business challenges. This 
    initiative is sponsored by the owner of HORISEN, personally.</p>

<p><span class="bold">Open Source</span> – we are very proud to support different open source projects. The openness of different approaches and the open
    source software we use enables a company-enhancing diversity of production models and different problem solving methods. 
    Being part of the open source community we empower other contributors to interact and create a product / service with great 
    economic value and unique design.</p>

<p><span class="bold">Employees Workplace</span> – our employees work in a nice and professional environment. They work in nice offices with modern 
    equipment and are given all necessary tools for delivering great results in less time. Our team spends their working day in a 
    healthy environment (far from the industrial zone), very close to city center where they can easily organize their social life and 
    activities and can be reached by public transportation or using a bike. Only motivated employees can deliver the results we 
    expect.</p>