<h1>Terms</h1>
<p>HORISEN provides the HORISEN Services (as defined below) to you subject to the following Terms of Services ("TOS"). 
    You can review the most current version of the TOS at any time below. <br />
    By accessing and using the HORISEN Services, you accept and agree to be bound by the terms and provision of the TOS. 
    The TOS is a legal agreement between you and HORISEN and applies to you whether you are user of the Site and HORISEN 
    Services (defined below), a customer of HORISEN Paid Services (defined below) or a visitor just browsing the Site (collectively, "Users").</p>

<p>The TOS limits HORISEN's liability and obligations to you, grant us certain rights in your Content (defined below) 
    and allows us to change, suspend or terminate your access to and use of the Site and HORISEN Services. The TOS and 
    the other policies posted on the Site or made available via the HORISEN Services govern your access to and use of the 
    Site and HORISEN Services, including any content, information, products or services therein.</p>

<h2>1. DESCRIPTION OF HORISEN SERVICES</h2>
<p>HORISEN provides Users on its various web sites ("Sites") an online application market for applications ("apps") in the 
    areas of voice, web, mobile and social media. The latter to be installed on - but not limited to - on Facebook. These 
    HORISEN app services are e.g. contact form app, winning game apps, sms-based apps or IVR-based apps and others hitherto 
    known and future apps not yet developed. HORISEN Professional Services are  e.g. services such as strategy and marketing 
    consulting, creative design, project management, software development, technical support, web hosting, bulk and Premium 
    sms transit or Premium Number Hosting hiherto known and others not yet developed. All of the above are  collectively the 
    "HORISEN Services" when referenced below.</p>

<h2>2. REGISTRATION AND ELIGIBILITY</h2>
<p>In order to access certain features of the Sites and HORISEN Services, you will have to create a HORISEN account and become 
    a "User." You must be an authorized representative of a company that is a registered legal entity.<br />
    When you register with HORISEN and set up your HORISEN account, you agree that all information provided to HORISEN upon registration 
    and at all other times will be true, accurate, current and complete.<br /> 
    When you sign up to become a User, you may be asked to install a HORISEN application through Facebook using Facebook account details. 
    You are entirely responsible for maintaining the confidentiality of your Facebook account and password. You agree to not use the account, 
    username, or password of another User at any time or to disclose your password to any third party. You agree to notify HORISEN immediately 
    if you suspect any unauthorized use of your account or access to your password. You are solely responsible for any and all use of your account. 
    If you become a User you consent to the use of: (a) electronic means to complete these TOS and to provide you with any notices given pursuant 
    to these TOS; and (b) electronic records to store information related to these TOS or your use of the Site and HORISEN Services.</p>

<h2>3. HORISEN MATERIALS</h2>
<p>General. HORISEN makes certain content available through the Site. "HORISEN Materials" mean all materials originated by HORISEN and otherwise 
    made available through the Site and HORISEN Services, including, without limitation, the HORISEN logo, and all designs, text, data, graphics, 
    other files, and the selection and arrangement thereof. HORISEN and its licensors own all right, title and interest, including all worldwide 
    intellectual property rights in the Site, HORISEN Materials, and the trademarks, service marks and logos contained therein other than your Content. 
    You may electronically copy and print to hard copy portions of the Site for the sole purpose of using materials it contains for informational and 
    non-commercial, personal use only. You will not remove, alter or conceal any copyright, trademark, service mark or other proprietary rights notices 
    incorporated in or accompanying the Site, HORISEN Materials, Content or related products and services and you will not reproduce, modify, adapt, 
    prepare derivative works based on, perform, display, publish, distribute, transmit, broadcast, sell, license or otherwise exploit the Site, HORISEN 
    Materials, Content (other than your Content).<br />  
    HORISEN Trademarks. The HORISEN name and logo are trademarks of HORISEN, and may not be copied, imitated or used, in whole or in part, without the prior 
    written permission of HORISEN. In addition, all page headers, custom graphics, button icons and scripts are service marks, trademarks and/or trade dress 
    of HORISEN, and may not be copied, imitated or used, in whole or in part, without the prior written permission of HORISEN.</p>

<h2>4. USER CONTENT</h2>
<p>You understand that all information, listings, data, text, software, sound, photographs, graphics, video, messages or other materials ("Content"), whether 
    publicly posted or privately transmitted, excluding HORISEN Materials, are the sole responsibility of the User from which such Content originated. If you 
    are using Content on behalf of one or more entities or persons ("third parties") then you confirm and warrant that you are authorized to act on behalf and 
    bind such entity(s) or person to the TOS. You understand that by using HORISEN Services, you may be exposed to Content that is offensive, indecent or objectionable. <br />
    You, or a third party licensor, as appropriate, retain any intellectual property rights in the Content you submit. By submitting Content on or through the Services, 
    you grant HORISEN, under those intellectual property rights, an irrevocable, perpetual, worldwide, non-exclusive, royalty-free, sub-licensable license to distribute, 
    reproduce, modify, perform and display and otherwise use the Content in HORISEN Services. By submitting Content, you authorize HORISEN to use your trademarks, service marks, 
    trade names, proprietary logos, domain names and any other source or business identifiers in connection with the HORISEN. Additionally, if you are a customer, you agree that 
    we may use your name and logo to identify you as a HORISEN customer on the Site and in HORISEN marketing, corporate and promotional materials. Your Content may have been 
    integrated into HORISEN Services as improvements. This license is solely for the purpose of providing, promoting and improving HORISEN Services.</p>

<h2>5. USER CONDUCT</h2>
<p>You agree that you are responsible for your own conduct and Content while using HORISEN Services and for any consequences thereof. You agree to use HORISEN Services 
    only for purposes that are legal, proper and in accordance with the TOS and any applicable policies or guidelines such as but not limited to Facebook TOS. By way of 
    example, and not as a limitation, you agree that when using HORISEN Services, you will not:</p>
<ul>
    <li>defame, abuse, harass, stalk, threaten or otherwise violate the legal rights (such as rights of privacy and publicity) of others;</li>
    <li>upload, post, email or transmit or otherwise make available any inappropriate, defamatory, infringing, obscene, or unlawful Content;</li>
    <li>upload, post, email or transmit or otherwise make available any Content that infringes any patent, trademark, copyright, trade secret 
        or other proprietary right of any party, unless you are the owner of such rights or have the permission of the owner to post such Content;</li>
    <li>upload, post, email or transmit or otherwise make available messages that promote pyramid schemes, chain letters or disruptive commercial 
        messages or advertisements, or anything else prohibited by law, the TOS or any applicable policies or guidelines.</li>
    <li>download any file posted by another that you know, or reasonably should know, that cannot be legally distributed in such manner;</li>
    <li>impersonate another person or entity, or falsify or delete any author attributions, legal or other proper notices or proprietary designations 
        or labels of the origin or source of software or other material;</li>
    <li>restrict or inhibit any other user from using and enjoying HORISEN Services;</li>
    <li>use HORISEN Services for any illegal or unauthorized purpose;</li>
    <li>remove any copyright, trademark or other proprietary rights notices contained in or on HORISEN Services;</li>
    <li>interfere with or disrupt HORISEN Services or servers or networks connected to HORISEN Services, or disobey any requirements, procedures, 
        policies or regulations of networks connected to HORISEN Services;</li>
    <li>use any robot, spider, site search/retrieval application, or other device to retrieve or index any portion of HORISEN Services or collect 
        information about users for any unauthorized purpose;</li>
    <li>submit Content that falsely expresses or implies that such Content is sponsored or endorsed by HORISEN;</li>
    <li>create user accounts by automated means or under false or fraudulent pretences;</li>
    <li>promote or provide instructional information about illegal activities or promote physical harm or injury against any group or individual; or</li>
    <li>transmit any viruses, worms, defects, Trojan horses, or any items of a destructive nature.</li>
</ul>
<p>While HORISEN prohibits such conduct and Content in connection with HORISEN Services, you understand and agree that HORISEN may or may not pre-screen 
    Content and shall have the right (but not the obligation) in its sole discretion to pre-screen, refuse or move any Content submitted to HORISEN Services. 
    In particular any content not considered ethically, dismissive or adult content may lead to immediate service termination.<br />
    International users agree to comply with their own local rules regarding online conduct and acceptable content, including laws regulating the export of data 
    to Switzerland or your country of residence.</p>

<h2>6. TERMINATION OR SUSPENSION OF THE SITE OR HORISEN SERVICES & MODIFICATION OF THE TOS.</h2>
<p>By User: You may terminate your HORISEN account at any. After receipt of your termination notice, HORISEN will terminate your account. Any fees paid by you prior 
    to your termination are non-refundable, including any fees paid in advance for the term during which you terminate. Termination of your account shall not relieve 
    you of any obligation to pay any accrued fees or charges.<br /> 
    By HORISEN: HORISEN reserves the right, in its sole discretion, at any time to modify, discontinue or terminate the Site and HORISEN Services, or modify these TOS 
    without advance notice. All modified terms and conditions will be effective after they are posted on the Site (unless a longer notice period is required by applicable law). 
    If any modified terms and conditions are not acceptable to you, your sole remedy is to cease using the Site and HORISEN Services, and if applicable, cancel your HORISEN 
    account. By continuing to access or use the Site and HORISEN Services after HORISEN makes any such revision, you agree to be bound by the revised TOS.<br /> 
    Without limiting other remedies, HORISEN may immediately terminate or suspend your access to the Site and HORISEN Services and remove any material (including Content) 
    from the Site or our servers, in the event that you breach these TOS. Notwithstanding the foregoing, we also reserve the right to terminate the Site, HORISEN Services or 
    your access thereto at any time and for any reason. After any termination by you or HORISEN: You understand and acknowledge that we will have no further obligation to provide 
    the HORISEN Services. Upon termination, all licenses and other rights granted to you by these TOS will immediately cease. HORISEN is not liable to you or any third party for 
    termination of the HORISEN Services or termination of your use of the HORISEN Services. UPON ANY TERMINATION OR SUSPENSION, ANY INFORMATION (INCLUDING USER SUBMISSIONS) 
    THAT YOU HAVE SUBMITTED ON THE SITE OR THAT WHICH IS RELATED TO YOUR ACCOUNT MAY NO LONGER BE ACCESSED BY YOU. Furthermore, HORISEN will have no obligation to maintain any 
    information stored in our database related to your account or to forward any information to you or any third party. 
    Any suspension, termination or cancellation will not affect your obligations to HORISEN under these TOS (including but not limited to ownership, indemnification and 
    limitation of liability), which by their sense and context are intended to survive such suspension, termination or cancellation.</p>

<h2>7. PAYMENT</h2>
<p>Fees. If you purchase any services that we offer for a fee, either on a one-time or subscription basis (collectively, "Paid Services"), you agree to pay all fees 
    and charges specified when you signed up for the Services and any part thereof. All fees are exclusive of applicable taxes (e.g., sales, use, or value-added tax), 
    unless otherwise stated, and you are solely responsible for the payment of any such taxes that may be imposed on your use of the Services.<br /> 
    Credit Card Authorization. You may be asked to provide HORISEN with a credit card number from a card issuer that we accept in order to activate and/or pay for any fees 
    related to Paid Services. You agree that any credit card and related billing and payment information that you provide may be shared by HORISEN with companies, such as 
    payment processors and/or credit agencies, solely for the purposes of checking credit, effecting payment to HORISEN and servicing your account. HORISEN may seek 
    pre-authorization of your credit card account prior to a purchase to verify the credit card is valid and/or has the necessary funds or credit available to cover your 
    purchase. These pre-authorizations will reduce your available balance by the authorization amount until it is released or reconciled with the actual charge. Please 
    contact your card issuer if you have additional questions regarding when an authorization amount will be removed from your statement.<br /> 
    Payment Method. HORISEN will charge the subscription fee and any other additional fees you authorize to the charge or credit card account provided by you. By authorizing 
    HORISEN to charge a credit card for the fees associated with your subscription, you are authorizing HORISEN to automatically continue charging that card (or any replacement 
    card if the original card is renewed, lost, stolen, or changed for any reason by the card issuer, and the issuer informs HORISEN of the new replacement card account) for 
    all fees or charges associated with your subscription including any renewal fees as described below. You authorize the card issuer to pay any amounts described herein and 
    authorize HORISEN, or any other company that acts as a billing agent for HORISEN, to continue to attempt to charge all sums described herein to your credit card account 
    until such amounts are paid in full. You agree to provide HORISEN updated information on your credit card upon HORISEN's request and any time the information earlier 
    provided is no longer valid. If payment is not received by HORISEN from your credit card issuer or its agents, you agree to pay all amounts due upon demand by HORISEN. 
    Free Trial Period. HORISEN does offer free trials upon it`s sole discretion without any rights whatsoever.<br />
    Cancellation of Paid Services You may cancel any Paid Services that are Facebook applications ("Paid Apps") at any time. If you cancel your account, all Content you 
    have submitted to us may be deleted and shall not be recovered by HORISEN. If you delete any Paid Apps such services shall be cancelled and, after you pay for any 
    accrued by unpaid services, you will not receive any future billings. For other Paid Services, you may cancel your account by contacting customer care at 
    contact@HORISEN.com and you will be provided with instructions. All fees and charges are nonrefundable and there are no refunds or credits for partially used periods 
    or for unused services. Automatic Renewal of Subscription. When you sign up online for the Paid Services, your monthly or annual subscription will be set to automatically 
    renew upon its expiration, depending on the option you select. This means that unless you cancel your account or change its renewal settings prior to its expiration, 
    your account will automatically renew for another month or year, as applicable. At the time of renewal, we will charge your credit card the then-current fees to renew 
    the Paid Services. We may notify you by email to your email address that your account is about to renew and remind you that your credit card will be billed the indicated 
    Paid Services fees on the renewal date. <br />
    Changes in Price. HORISEN may at any time, upon notice required by applicable law, change the price of the Paid Services or any part thereof, or institute new charges or 
    fees. Price changes and institution of new charges implemented during your subscription term will apply to subsequent subscription terms and to all new subscribers after 
    the effective date of the change. If you do not agree to any such price changes, then you must cancel your account and stop using the Paid Services. Your continued use 
    of the Paid Services after the effective date of any such change shall constitute your acceptance of such change.</p>

<h2>8. INDEMNIFICATION</h2>
<p>You agree to defend, indemnify, and hold HORISEN, its officers, directors, employees and agents, harmless from and against any claims, liabilities, damages, losses, and 
    expenses, including without limitation reasonable attorney's fees and costs, arising out of or in any way connected with (i) your access to or use of the Site, HORISEN 
    Services, HORISEN Materials and Content; (ii) your violation of the TOS; or (iii) your violation of any third party right, including without limitation any intellectual 
    property right, publicity, confidentiality, property or privacy right.<br /> 
    YOU EXPRESSLY UNDERSTAND AND AGREE THAT:<br /> 
    YOUR USE OF THE HORISEN SERVICE, SITE, MATERIALS AND USER CONTENT IS AT YOUR SOLE RISK. THE HORISEN SERVICE, SITE, HORISEN MATERIALS AND USER CONTENT AND ALL MATERIALS, 
    INFORMATION, PRODUCTS AND SERVICES INCLUDED THEREIN, ARE PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS. HORISEN EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND, WHETHER 
    EXPRESS OR IMPLIED, RELATING TO THE HORISEN SERVICE, SITE, HORISEN MATERIALS AND USER CONTENT, INCLUDING, BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY, 
    FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT.<br /> 
    HORISEN MAKES NO WARRANTY THAT (i) THE SITE OR HORISEN SERVICES WILL MEET YOUR REQUIREMENTS, (ii) THE SITE AND HORISEN SERVICES WILL BE UNINTERRUPTED, TIMELY, SECURE, 
    OR ERROR-FREE, (iii) THE RESULTS THAT MAY BE OBTAINED FROM THE USE OF THE SITE OR HORISEN SERVICES WILL BE ACCURATE OR RELIABLE, (iv) THE QUALITY OF ANY PRODUCTS, SERVICES, 
    INFORMATION, OR OTHER MATERIAL PURCHASED OR OBTAINED BY YOU THROUGH THE SITE AND HORISEN SERVICES WILL MEET YOUR EXPECTATIONS, AND (V) ANY ERRORS IN ANY SOFTWARE AVAILABLE 
    THROUGH THE SITE OR HORISEN SERVICES WILL BE CORRECTED.<br /> 
    ANY DOWNLOADING OR USE OF ANY CONTENT OR MATERIAL VIA THE HORISEN SERVICES IS DONE AT YOUR OWN DISCRETION AND RISK AND YOU WILL BE SOLELY RESPONSIBLE FOR ANY DAMAGE TO YOUR 
    COMPUTER SYSTEM OR LOSS OF DATA THAT RESULTS FROM THE DOWNLOAD OF ANY SUCH CONTENT OR MATERIAL. 
    NO ADVICE OR INFORMATION, WHETHER ORAL OR WRITTEN, OBTAINED BY YOU FROM HORISEN OR THROUGH OR FROM THE SITE OR HORISEN SERVICES SHALL CREATE ANY WARRANTY NOT EXPRESSLY 
    STATED IN THE TOS.</p>

<h2>9. LIMITATION OF LIABILITY</h2>
<p>YOU EXPRESSLY UNDERSTAND AND AGREE THAT HORISEN SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL OR EXEMPLARY DAMAGES, ARISING OUT OF OR IN 
    CONNECTION WITH YOUR USE OF THE SITE, SERVICES, CONTENT AND USER SUBMISSIONS INCLUDING BUT NOT LIMITED TO, DAMAGES FOR LOSS OF PROFITS, GOODWILL, USE, DATA OR OTHER 
    INTANGIBLE LOSSES (EVEN IF HORISEN HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES), RESULTING FROM: (i) THE USE OR THE INABILITY TO USE THE HORISEN SERVICE; (ii) 
    THE COST OF PROCUREMENT OF SUBSTITUTE GOODS AND SERVICES RESULTING FROM ANY GOODS, DATA, INFORMATION OR SERVICES PURCHASED OR OBTAINED OR MESSAGES RECEIVED OR 
    TRANSACTIONS ENTERED INTO THROUGH OR FROM THE SERVICE; (iii) UNAUTHORIZED ACCESS TO OR ALTERATION OF YOUR TRANSMISSIONS OR DATA; (iv) STATEMENTS OR CONDUCT OF ANY 
    THIRD PARTY ON THE SERVICE; OR (v) ANY OTHER MATTER RELATING TO THE SERVICE. IN NO EVENT WILL HORISEN'S CUMULATIVE LIABILITY TO YOU EXCEED FIVE TIMES THE MOST RECENT 
    MONTHLY FEE THAT YOU PAID FOR A PAID SERVICE, IF ANY, OR EURO 100, WHICHEVER AMOUNT IS GREATER.</p>

<h2>10. GENERAL INFORMATION</h2>
<p>The TOS constitutes the entire agreement between you and HORISEN and governs your use of the Services, superseding any prior agreements between you and HORISEN. 
    You also may be subject to additional terms and conditions that may apply when you use affiliate or other HORISEN Services, third-party Content or third-party 
    software. You will not assign the TOS or assign any rights or delegate any obligations hereunder, in whole or in part, whether voluntarily or by operation of law, 
    without the prior written consent of HORISEN. Any purported assignment or delegation by you without the appropriate prior written consent of HORISEN will be null 
    and void. HORISEN may assign the TOS or any rights hereunder without your consent. The TOS and the relationship between you and HORISEN shall be governed by the 
    laws of Switzerland without regard to its conflict of law provisions. You and HORISEN agree to submit to the personal and exclusive jurisdiction of the courts 
    located within the county of St.Gallen, Switzerland. The failure of HORISEN to exercise or enforce any right or provision of the TOS shall not constitute a waiver 
    of such right or provision. If any provision of the TOS is found by a court of competent jurisdiction to be invalid, the parties nevertheless agree that the court 
    should endeavor to give effect to the parties' intentions as reflected in the provision, and the other provisions of the TOS remain in full force and effect. 
    You agree that regardless of any statute or law to the contrary, any claim or cause of action arising out of or related to use of the Services or the TOS must be 
    filed within one (1) year after such claim or cause of action arose or be forever barred. The section titles in the TOS are for convenience only and have no legal 
    or contractual effect.</p>

<h2>11. VIOLATIONS AND COMMENTS</h2>
<p>Please report any violations of the TOS or make any comments by emailing us at contact@horisen.com. You agree, however, that: (i) by submitting unsolicited ideas 
    to HORISEN or any of its employees or representatives, you automatically forfeit your right to any intellectual property rights in these ideas; and (ii) unsolicited 
    ideas submitted to HORISEN or any of its employees or representatives automatically become the property of HORISEN. You hereby assign and agree to assign all rights, 
    title and interest you have in such comments and ideas to HORISEN together with all intellectual property rights therein.</p>