<div class="introTxt">
    <h1>App Development</h1>
    <h2>Rapid delivery of apps tailored to your needs</h2>
</div>
<p>Your creative social media campaign idea delivered to desktop, smartphones and tablets in no time.</p>
<div class="row innerRow">
    <div class="col-md-9 listWrapper">
        <div class="row listGroup">
            <div class="collapseContent col-md-6">
                <h3>You want</h3>
                <ul class="collapseContentBox">
                    <li>App features tailored to your needs.</li>
                    <li>No watermarked campaigns.</li>
                    <li>Contests for mobile devices.</li>
                    <li>Custom branding options.</li>   
                </ul>
            </div>
            <div class="collapseContent col-md-6">
                <h3>We have</h3>
                <ul class="collapseContentBox">
                    <li>Ready-made components for rapid assembly.</li>
                    <li>Hosting, app support and white labeling included.</li>
                    <li>Mobile-ready campaigns.</li>
                    <li>Custom skins and design support included.</li>
                </ul>
            </div>
        </div>
        <div class="row listGroup">
            <div class="collapseContent col-md-6">
                <h3>Features</h3>
                <ul class="collapseContentBox">
                    <li>Easy-to-navigate app admin cockpit.</li>
                    <li>Mobile-ready campaigns.</li>
                    <li>Built-in custom features.</li>
                    <li>Custom app design supported.</li>
                    <li>Gamifications included.</li>
                    <li>Multi-language support.</li>
                    <li>Completely white-labeled campaigns.</li>
                    <li>Advanced statistics and data export.</li>
                    <li>Mobile / SMS marketing included.</li>
                </ul>
            </div>
            <div class="collapseContent col-md-6">
                <h3>Purpose</h3>
                <ul class="collapseContentBox">
                    <li>Achieving great brand awareness.</li>
                    <li>Keeping brand consistency.</li>
                    <li>Attracting specific target group.</li>
                    <li>Suitable for any occasion important to your business.</li>
                    <li>More traffic to business website or landing page.</li>
                    <li>Cost-effective advertising: no extra payments.</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="col-md-3">
        <div class="row">
            <div class="col-md-12 col-xs-6 innerPageImage">
                <?php echo $this->renderPicture('picture1', '/images/inner/picture1', 'Placeholder image for sms winning game', '.jpg');?>
            </div>
            <div class="col-md-12 col-xs-6 innerPageImage">
                <?php echo $this->renderPicture('picture2', '/images/inner/picture2', 'Placeholder image for sms winning game', '.jpg');?>
            </div>
        </div>
    </div>
</div>
<section class="collapsibleSection">
    <h2>Description</h2>
    <div class="row description">
        <div class="col-md-9">
            <p>With custom app development we rapidly deliver apps tailored to your needs! Now it's possible to make unique fan page campaigns which are well planned, designed and executed. Creating custom tabs for Facebook pages is just one step towards successful social media marketing campaigns – which is crucial to your business. In this way you get many new brand fans and build a quality contact database which helps in fan-to-customer conversion process and drives more traffic to your website.</p>

            <p>In the last years we have developed and launched hundreds of custom fan page apps. As a &quot;by-product&quot;, we have developed an app developer kit that enables us to deliver the most sophisticated apps according to customer requirements in no time! And very cost-efficiently! Custom app solutions let you choose app features that fit your business' plan best, enable participation on every device and help you embedding a unique and easily recognizable design. With totally customized solutions you build engaging campaigns and measure your success during or after each campaign. Apps include free hosting, app support and white labelling.</p>

            <p>For more features and custom app development benefits for your business, visit our <a href="http://www.megafanapps.com/en/applications/custom-apps" target="_blank">app store</a> now.</p>
        </div>
        <div class="col-md-3">
            <div class="row">
                <div class="col-md-12 col-xs-6 innerPageImage">
                    <?php echo $this->renderPicture('picture1', '/images/inner/picture1', 'Placeholder image for sms winning game', '.jpg');?>
                </div>
                <div class="col-md-12 col-xs-6 innerPageImage">
                    <?php echo $this->renderPicture('picture1', '/images/inner/picture1', 'Placeholder image for sms winning game', '.jpg');?>
                </div>
            </div>
        </div>  
    </div>
</section>
<section class="collapsibleSection">
    <h2>Campaign Idea</h2>
    <div class="row">
        <div class="col-md-12">  
           <p><a href="<?php echo $this->contactUrl();?>">Contact us</a> or Download <a href="#">Order Form</a> in PDF.</p>
        </div>
    </div>
</section>