<div class="introTxt">
    <h1>Awards</h1>
    <h2>Rating Certificate for No. 1 quality service</h2>
</div>
<p>Extraordinary business performance comes with high-quality service provided by HORISEN.</p>
<h2>Rating Certificate from Dun & Bradstreet (D&amp;B)</h2>

<a href="http://www.top-rating.ch/?sort=H&page=2&language=de" target="_blank">
    <?php echo $this->renderPicture('awards01', '/images/inner/awards', 'Placeholder image for awards', '.jpg');?>
</a>
<p>HORISEN AG holds the Rating Certificate from Dun & Bradstreet (D&amp;B). The risk indicator AA1 of D&amp;B is a great compliment
    and, at the same time, a strong recognition for the commercial and financial stability of our company. Only about 2% of Swiss 
    companies qualify for this award. With total score of 100 points (maximum) we are well beyond the industry average.</p>
<p>As a holder of D&amp;B Rating Certificate, we assure the investment stability and safety of our services. The competitive advantage
    proved by this award gives us the credibility among our customers and provide only positive recommendations. This information 
    is very important for our current and future customers since it ensures business sustainability.</p>
<p>Sustainability in revenue and overall business performance is the main thing we care about. Our customers are the most 
    important factor that rises the quality of our services and products developed within HORISEN.</p>
<p>HORISEN services are safe and trusted – with us you get a healthy and stable company as reliable partner on your way to
    success.</p>