<div class="introTxt">
    <h1>Bulk SMS for Carrier</h1>
    <h2>Send thousands of SMS messages all over the world</h2>
</div>
<p>HORISEN is the best mobile marketing and Bulk SMS service provider.</p>
<div class="row innerRow">
    <div class="col-md-9 listWrapper">
        <div class="row listGroup">
            <div class="collapseContent col-md-6">
                <h3>You want</h3>
                <ul class="collapseContentBox">
                    <li>Cost-effective SMS application for mass sending.</li>
                    <li>Application which you can use and edit at any time.</li>
                    <li>Dedicated technical support.</li>
                </ul>
            </div>
            <div class="collapseContent col-md-6">
                <h3>We have</h3>
                <ul class="collapseContentBox">
                    <li>Bulk SMS for Carrier service – a very cost-effective tool for any business.</li>
                    <li>Quick access to business account with possibility of testing, setting up and evaluating SMSs mass sending.</li>
                    <li>Experts in marketing technology that help you implementing your mobile marketing applications.</li>
                </ul>
            </div>
        </div>
        <div class="row listGroup">
            <div class="collapseContent col-md-6">
                <h3>Features</h3>
                <ul class="collapseContentBox">
                    <li>Pre-set price packages for sent SMS's.</li>
                    <li>Lower prices for larger packages.</li>
                    <li>Alphanumeric and numeric sender ID supported.</li>
                    <li>1000+ SMS per minute.</li>
                    <li>Demographic targeting included.</li>
                    <li>Supports all telecom operators.</li>
                    <li>Online support 24/7.</li>
                    <li>Dedicated technical support.</li>
                    <li>Account setup for testing SMS messages.</li>
                    <li>Full access to HORISEN online SMS portal.</li>
                </ul>
            </div>
            <div class="collapseContent col-md-6">
                <h3>Purpose</h3>
                <ul class="collapseContentBox">
                    <li>Send your business message worldwide.</li>
                    <li>To reach wide range of customers with your business offers.</li>
                    <li>Using multiple carriers with cost-effective sending solutions.</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="col-md-3">
        <div class="row">
            <div class="col-md-12 col-xs-6 innerPageImage">
                <?php echo $this->renderPicture('picture1', '/images/inner/picture1', 'Placeholder image for sms winning game', '.jpg');?>
            </div>
            <div class="col-md-12 col-xs-6 innerPageImage">
                <?php echo $this->renderPicture('picture2', '/images/inner/picture2', 'Placeholder image for sms winning game', '.jpg');?>
            </div>
        </div>
    </div>
</div>
<section class="collapsibleSection">
    <h2>Description</h2>
    <div class="row description">
        <div class="col-md-9">
            <p>Bulk SMS for Carrier allows you to easily setup SMS mass sending campaign in a few steps. With HORISEN mobile marketing you
            make your business ahead of other competitors. We offer you a cloud-based system solution hosted within our own servers; 
            this is a very reliable option since you need to keep track of your mobile campaign progress. HORISEN mobile application system 
            allows you to reach as many customers needed for the success of your business not only locally, but worldwide.</p> 

            <p>The first step is creating account in our internal system. The list of carriers is provided within the system. Bulk SMS application
            enables thousands of messages to be sent at once to different mobile phone numbers around the world. Bulk SMS for Carrier 
            provides a safe and highly reliable delivery of SMS messages to mobile users. This is a very cost-effective and efficient solution 
            for any business that knows how marketing works in practice. Sending thousands and more messages per minute enables you to 
            spread your marketing message faster than sending emails and newsletter reminders.</p>

            <p>Bulk SMS for Carrier is an effective tool for any business size. And, the more important, it takes place worldwide. You can send 
            SMSs to any country in the world choosing the right operator; also tailor your costs and expenditures during the campaign. The 
            system allows you to do quality SMS delivery testing – therefore, you know when your campaign is really ready to be launched.</p>
        </div>
        <div class="col-md-3">
            <div class="row">
                <div class="col-md-12 col-xs-6 innerPageImage">
                    <?php echo $this->renderPicture('picture1', '/images/inner/picture1', 'Placeholder image for sms winning game', '.jpg');?>
                </div>
                <div class="col-md-12 col-xs-6 innerPageImage">
                    <?php echo $this->renderPicture('picture1', '/images/inner/picture1', 'Placeholder image for sms winning game', '.jpg');?>
                </div>
            </div>
        </div>  
    </div>
</section>
<section class="collapsibleSection">
    <h2>Preparations</h2>
    <div class="row">
        <div class="col-md-12">  
            <p>Before you setup Bulk SMS application, you need to do open account in HORISEN mobile marketing (SMS services) system where 
            you can start, test and adjust your Bulk SMS campaigns from one touch point.</p>
            <p>Demo: click here(Bulk SMS video)</p>
        </div>
    </div>
</section>
<section class="collapsibleSection">
    <h2>Prices</h2>
    <div class="row">
        <div class="col-md-12">  
            <p><a href="<?php echo $this->contactUrl();?>">Contact us</a> or Download <a href="#">Order Form</a> in PDF.</p>
        </div>
    </div>
</section>