<div class="introTxt">
    <h1>Call &amp; Win</h1>
    <h2>Engage your customers over the phone</h2>
</div>
<p>HORISEN is the best Call &amp; Win application provider on the market.</p>
<div class="row innerRow">
    <div class="col-md-9 listWrapper">
        <div class="row listGroup">
            <div class="collapseContent col-md-6">
                <h3>You want</h3>
                <ul class="collapseContentBox">
                    <li>Easy to participate winning game for your customers.</li>
                    <li>Quality customer database.</li>
                    <li>No extra operational costs.</li>
                </ul>
            </div>
            <div class="collapseContent col-md-6">
                <h3>We have</h3>
                <ul class="collapseContentBox">
                    <li>The best phone winning game on the market.</li>
                    <li>Automated system for data collection and export.</li>
                    <li>Pre-defined Call &amp; Win campaign prices.</li>
                </ul>
            </div>
        </div>
        <div class="row listGroup">
            <div class="collapseContent col-md-6">
                <h3>Features</h3>
                <ul class="collapseContentBox">
                    <li>Quick &amp; Easy participation.</li>
                    <li>Automated answer recording possible.</li>
                    <li>Campaign frequency is completely adjustable.</li>
                    <li>Customer data export (Excel, CSV).</li>
                    <li>Time-limited campaigns enabled.</li>
                    <li>Online admin panel for campaign settings.</li>
                    <li>Real-time statistics.</li>
                    <li>And many more...</li>
                </ul>
            </div>
            <div class="collapseContent col-md-6">
                <h3>Purpose</h3>
                <ul class="collapseContentBox">
                    <li>Collect customer data quickly and easily.</li>
                    <li>Increase brand awareness.</li>
                    <li>Attract wider target groups (audience).</li>
                    <li>Quality customer contact database.</li>
                    <li>Great sales promotion tool.</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="col-md-3">
        <div class="row">
            <div class="col-md-12 col-xs-6 innerPageImage">
                <?php echo $this->renderPicture('picture1', '/images/inner/picture1', 'Placeholder image for sms winning game', '.jpg');?>
            </div>
            <div class="col-md-12 col-xs-6 innerPageImage">
                <?php echo $this->renderPicture('picture2', '/images/inner/picture2', 'Placeholder image for sms winning game', '.jpg');?>
            </div>
        </div>
    </div>
</div>
<section class="collapsibleSection">
    <h2>Description</h2>
    <div class="row description">
        <div class="col-md-9">
            <p>HORISEN Call &amp; Win app executes all processes from registration, play voice prompts, record caller speech and promotion analytics. 
                You can re-use any existing premium number you have, otherwise we provide you that as well. Participating is as easy as placing a 
                call, your administration efforts are close to zero.</p> 

            <p>Call &amp; Win application allows you to organize winning game over phone for thousands of customers at once. Due to high automation process 
                run by HORISEN system, your administrative costs are down to minimum. If you use our Premium numbers in order to run a campaign, you can 
                generate additional revenue with your Call &amp; Win campaign. The application is fully automated in all its steps, from participants’ registration, 
                reproduction of recorded announcements/voices and another sound recordings necessary for gathering additional contact details from participants 
                or guessing the winning word, for example.<br /> 
                You can easily set the sound that will correspond to your outgoing messages – these sounds can be 
                downloaded from our system.</p>

            <p>Everything you need to set up a quality Call &amp; Win application is a 090x number. If you already have this number, the process is even easier – we 
                import it and it's ready for use. Otherwise, we will provide you 090x number.<br />  
                Call &amp; Win is the application you got a full control over and can modify its parameters at any time. Detailed statistics found in our system give 
                you necessary information and provide all data valuable for planning the next Call & Win campaign.<br />  
                Participation in Call & Win campaign is very simple: Participant dials your 090x number and follows the instructions. That's it.<br /> 
                Because it’s so simple and available, Call &amp; Win is the application many customers will use to try their luck and win great prizes! </p>
        </div>
        <div class="col-md-3">
            <div class="row">
                <div class="col-md-12 col-xs-6 innerPageImage">
                    <?php echo $this->renderPicture('picture1', '/images/inner/picture1', 'Placeholder image for sms winning game', '.jpg');?>
                </div>
                <div class="col-md-12 col-xs-6 innerPageImage">
                    <?php echo $this->renderPicture('picture1', '/images/inner/picture1', 'Placeholder image for sms winning game', '.jpg');?>
                </div>
            </div>
        </div>  
    </div>
</section>
<section class="collapsibleSection">
    <h2>Preparations</h2>
    <div class="row">
        <div class="col-md-12">  
            <h3>Preparations from your side</h3>
            <ol>
                <li>Idea for Call &amp; Win campaign (e.g. sales).</li>
                <li>Record the message which will be played for winning game participants.</li>
                <li>Determine prize rates and numbers (1 x Smart TV, 5 x shop card, etc.).</li>
                <li>Enter all prizes in Call &amp; Win online system administration.</li>
                <li>Advertise Call &amp; Win campaign on your website and announce prizes.</li>
                <li>Set campaign starting and ending dates.</li>
                <li>Let's start!</li>
            </ol>
            <h3>How your customers participate in your Call &amp; Win campaign</h3>
            <ol>
                <li>Participants dial your 0901 number or a premium-rate number.</li>
                <li>The system responds playing recorded message (IVR service – interactive voice response).</li>
                <li>The application records and sorts the answers or different keywords.</li>
                <li>The system sends additional message (if recorded).</li>
                <li>Participants subscribe to your email newsletter by going to your website for additional coupon.</li>
                <li>This is the part where your future marketing activities start.</li>
            </ol>
        </div>
    </div>
</section>
<section class="collapsibleSection">
    <h2>Prices</h2>
    <div class="row">
        <div class="col-md-12">  
            <p><a href="<?php echo $this->contactUrl();?>">Contact us</a> or Download <a href="#">Order Form</a> in PDF.</p>
        </div>
    </div>
</section>