<div class="introTxt">
    <h1>Call &amp; Vote Application</h1>
    <h2>Phone voting application for thousands of participants</h2>
</div>
<p>HORISEN is specialist for managing voice apps – one of them is Call &amp; Vote</p>
<div class="row innerRow">
    <div class="col-md-9 listWrapper">
        <div class="row listGroup">
            <div class="collapseContent col-md-6">
                <h3>You want</h3>
                <ul class="collapseContentBox">
                    <li>To run a voting campaign using phone.</li>
                    <li>To quickly collect participants' data.</li>
                    <li>Have a real-time overview of voting results.</li>
                </ul>
            </div>
            <div class="collapseContent col-md-6">
                <h3>We have</h3>
                <ul class="collapseContentBox">
                    <li>The best phone voting application.</li>
                    <li>Call &amp; Vote application collects participants' data after they submit their votes.</li>
                    <li>Real-time statistics that are available online.</li>
                </ul>
            </div>
        </div>
        <div class="row listGroup">
            <div class="collapseContent col-md-6">
                <h3>Features</h3>
                <ul class="collapseContentBox">
                    <li>Call &amp; Vote application suitable for any type of voting campaign.</li>
                    <li>Real-time voting results available.</li>
                    <li>No pre-registration needed.</li>
                    <li>Possibility to combine Call &amp; Vote with premium number.</li>
                    <li>Votes export in CSV at any time.</li>
                    <li>Online cockpit for easy settings.</li>
                    <li>Evaluation and full campaign support provided.</li>
                </ul>
            </div>
            <div class="collapseContent col-md-6">
                <h3>Purpose</h3>
                <ul class="collapseContentBox">
                    <li>Applicable for any type of voting campaigns.</li>
                    <li>To attract voters for radio and TV shows, concerts, sports events, fairs, etc.</li>
                    <li>Product reviews.</li>
                    <li>Telephone voting research.</li>
                    <li>Voting for Parliament Elections.</li>
                    <li>Television Voting.</li>
                    <li>Great marketing tool to generate customer data.</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="col-md-3">
        <div class="row">
            <div class="col-md-12 col-xs-6 innerPageImage">
                <?php echo $this->renderPicture('picture1', '/images/inner/picture1', 'Placeholder image for sms winning game', '.jpg');?>
            </div>
            <div class="col-md-12 col-xs-6 innerPageImage">
                <?php echo $this->renderPicture('picture2', '/images/inner/picture2', 'Placeholder image for sms winning game', '.jpg');?>
            </div>
        </div>
    </div>
</div>
<section class="collapsibleSection">
    <h2>Description</h2>
    <div class="row description">
        <div class="col-md-9">
            <p>Give your customers a great and simple opportunity – to vote via their phones! Call &amp; Vote application allows you to quickly and
            easily run phone voting campaigns for thousands of participants. Your participants simple call your 0901 number in order to hear 
            a short text message and then type their votes.</p> 

            <p>HORISEN Call &amp; Vote application is fully automated starting from participants' registration, reproduction of recorded 
            announcements/voices and another sound recordings necessary for gathering additional contact details from participants. You
            can easily adjust the sound of all outgoing messages by uploading the file into our system. Everything you need for running a 
            quality Call &amp; Vote campaign is a 0901 number. If you already have this number, the process is even easier – we import it and it's 
            ready for use. Otherwise, we will provide you a 0901 number.</p>

            <p>You have a full-time control over the voting history, and can modify parameters at any time. Our detailed and real-time statistics
            give you all the information you need. Participation in Call &amp; Vote campaign is very simple. Participant dials your 0901 number 
            and follows the instructions. After that he needs to fill in the registration form and send it via regular mail or email; this info is 
            important for your campaign's evaluation.</p>

            <p>Because it's so simple and available, Call &amp; Vote is the application many participants will use to join your voting campaign!</p>
        </div>
        <div class="col-md-3">
            <div class="row">
                <div class="col-md-12 col-xs-6 innerPageImage">
                    <?php echo $this->renderPicture('picture1', '/images/inner/picture1', 'Placeholder image for sms winning game', '.jpg');?>
                </div>
                <div class="col-md-12 col-xs-6 innerPageImage">
                    <?php echo $this->renderPicture('picture1', '/images/inner/picture1', 'Placeholder image for sms winning game', '.jpg');?>
                </div>
            </div>
        </div>  
    </div>
</section>
<section class="collapsibleSection">
    <h2>Preparations</h2>
    <div class="row">
        <div class="col-md-12">  
            <h3>Preparations from your side</h3>
            <ul>
                <li>Define the type of phone voting campaign.</li>
                <li>Record the message which will be played for participants when dial the number.</li>
                <li>Advertise your voting campaign on your website and announce prizes for voters.</li>
                <li>Set the starting and ending date for your phone voting campaign into the system.</li>
                <li>Record additional message – contact details for the database or a short commercial.</li>
                <li>Let's start!</li>
            </ul>
            <h3>How your customers participate in Call &amp; Vote campaign</h3>
            <ul>
                <li>Participants dial your 0901 number using their phones.</li>
                <li>The system responds playing recorded message (IVR service – interactive voice response).</li>
                <li>The application records and sorts the answers (votes).</li>
                <li>The system sends additional message (if recorded).</li>
                <li>Participant goes online to fill in the form and win prizes.</li>
                <li>This is the part where your future marketing activities start.</li>
            </ul>
        </div>
    </div>
</section>
<section class="collapsibleSection">
    <h2>Prices</h2>
    <div class="row">
        <div class="col-md-12">  
            <p><a href="<?php echo $this->contactUrl();?>">Contact us</a> or Download <a href="#">Order Form</a> in PDF.</p>
        </div>
    </div>
</section>