<div class="introTxt">
    <h1>Social Media Concept and Consulting</h1>
    <h2>Smart planning leads to successful implementation</h2>
</div>
<p>With the right strategy, plan your social media marketing activities in advance!</p>
<div class="row innerRow">
    <div class="col-md-9 listWrapper">
        <div class="row listGroup">
            <div class="collapseContent col-md-6">
                <h3>You want</h3>
                <ul class="collapseContentBox">
                    <li>Great social media marketing strategy.</li>
                    <li>Cross-channel social media marketing activities.</li>
                    <li>Ideas for seasonal product/service promotion.</li>
                    <li>Consistent branding.</li>
                </ul>
            </div>
            <div class="collapseContent col-md-6">
                <h3>We have</h3>        
                <ul class="collapseContentBox">
                    <li>Experienced team to support your plans.</li>
                    <li>Cross-channel strategies that work!</li>
                    <li>Quality consulting regarding different campaign ideas using best practice examples only.</li>
                    <li>Design department working on effective branding and cross-channel consistent look.</li>  
                </ul>
            </div>
        </div>
        <div class="row listGroup">
            <div class="collapseContent col-md-6">
                <h3>Features</h3>
                <ul class="collapseContentBox">
                    <li>Planning end-to-end marketing process workflow.</li>
                    <li>Successful execution of social media marketing related activities.</li>
                    <li>Competitor scorecard done.</li>
                    <li>Analytics and campaign performance statistics at any time.</li>
                    <li>Live support and monitoring.</li>
                    <li>From campaign idea to live performance and results.</li>
                </ul>
            </div>
            <div class="collapseContent col-md-6">
                <h3>Purpose</h3>
                <ul class="collapseContentBox">
                    <li>Cost-effective social media marketing campaigns.</li>
                    <li>Strategy driven approach.</li>
                    <li>Fast conversion and website traffic.</li>
                    <li>Success measured with experience and expertise.</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="col-md-3">
        <div class="row">
            <div class="col-md-12 col-xs-6 innerPageImage">
                <?php echo $this->renderPicture('picture1', '/images/inner/picture1', 'Placeholder image for sms winning game', '.jpg');?>
            </div>
            <div class="col-md-12 col-xs-6 innerPageImage">
                <?php echo $this->renderPicture('picture2', '/images/inner/picture2', 'Placeholder image for sms winning game', '.jpg');?>
            </div>
        </div>
    </div>
</div>
<section class="collapsibleSection">
    <h2>Description</h2>
    <div class="row description">
        <div class="col-md-9">
<p>Social media marketing is one of the most important parts of your business’ success. Successful planning and the right strategy is the key of marketing success. HORISEN team consists of social media marketing experts with years of experience behind. Our team helps you achieve the most out of single social media marketing campaign, but also takes care of the cross-channel consistency and right targeted branding.</p>

<p><strong>Concept</strong>: In social media marketing, a right strategy is the key to achieve, but also measure success. This strategy is made according to the type of your business. For instance, if you are a retailer, then the main channels for effective communication with your customers (buyers) are: </p>

<ol>
    <li>Facebook – business page where you communicate with your fans;</li>
    <li>Instagram – for great visual appearance of your brand;</li>
    <li>Twitter – because most of your competitors are there;</li>
    <li>Pinterest – for quality promotions and call-to-actions for shopping.</li>
</ol>


<p>The main concept is about cross-channel consistency and right targeting. It means that a single campaign is already defined from the moment of planning, until the evaluation and preparation of the new campaign. We cover the whole project cycle management.</p>
<p><strong>Consulting</strong>: HORISEN team is here to give you smart advices how social media networks work – what is important, when and where to find your customers, what type of content to use, on which channels to post and be active, etc. We are constantly up-to-date with the latest technological improvements coming from social media world and can help you with the most relevant tips and tricks for great social media marketing success.</p>

<p>It’s about time to start exploring the possibility of smart consulting and social media marketing concept in advance!</p>
        </div>
        <div class="col-md-3">
            <div class="row">
                <div class="col-md-12 col-xs-6 innerPageImage">
                    <?php echo $this->renderPicture('picture1', '/images/inner/picture1', 'Placeholder image for sms winning game', '.jpg');?>
                </div>
                <div class="col-md-12 col-xs-6 innerPageImage">
                    <?php echo $this->renderPicture('picture1', '/images/inner/picture1', 'Placeholder image for sms winning game', '.jpg');?>
                </div>
            </div>
        </div>  
    </div>
</section>
<section class="collapsibleSection">
    <h2>Preparations</h2>
    <div class="row">
        <div class="col-md-12">  
            <h3>Social media marketing consulting process consists of:</h3>
            <ol>
                <li>You define the type of promotion (e.g. new product launch, sales period, business promotion, etc.).</li>
                <li>We choose the right promo channels (e.g. Twitter for latest updates, Facebook for constant communication and possibility to share content – also viral buzz, YouTube for effective video presentation, etc.).</li>
                <li>Your target audience is defined and the proper activities are proposed.</li>
                <li>According to a well-planned strategy, each activity has its timeframe for implementation.</li>
                <li>We also monitor and evaluate the results of your campaign.</li>
                <li>Together we measure your campaign’s success.</li>
            </ol>
        </div>
    </div>
</section>
<section class="collapsibleSection">
    <h2>Prices</h2>
    <div class="row">
        <div class="col-md-12">  
            <p><a href="<?php echo $this->contactUrl();?>">Contact us</a> or Download <a href="#">Order Form</a> in PDF.</p>
        </div>
    </div>
</section>