<div class="introTxt">
    <h1>Shaping</h1>
    <h2>contributes to your image</h2>
</div>
<p>Do you need more attention of the target group? Does your communication a crisp
    and zeitgemasses facelift or hovering in front of you a new advertising concept?
    We enitwickeln with your Mirwirken a suitable Strategic define objectives and implement them gesstalterisch attractive for you to.</p>
<p>Do you need more attention of the target group? Does your communication a crisp
    and zeitgemasses facelift or hovering in front of you a new advertising concept?
    We enitwickeln with your Mirwirken a suitable Strategic define objectives and implement them gesstalterisch attractive for you to.</p>
<h2>Our services</h2>
<section class="collapsibleSection designSection">
    <h3>Consultation, analysis and optimization</h3>
    <div class="row description">
        <div class="col-md-12 listWrapper">
            <div class="row listGroup">
                <div class="collapseContent col-md-7">
                    <?php echo $this->renderPicture('picture3', '/images/inner/picture3', 'Placeholder image for sms winning game', '.png');?>
                </div>
                <div class="collapseContent col-md-5">
                    <p>Modern webdesign reacts flexibly to the screen size of the retrieval device. Whether Smart Phone, iPad, or screen the available space is used optimally for the Enderat</p>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="collapsibleSection designSection">
    <h3>Logo Design</h3>
    <div class="row description">
        <div class="col-md-12 listWrapper">
            <div class="row listGroup">
                <div class="collapseContent col-md-7">
                    <?php echo $this->renderPicture('picture3', '/images/inner/picture3', 'Placeholder image for sms winning game', '.png');?>
                </div>
                <div class="collapseContent col-md-5">
                    <p>Modern webdesign reacts flexibly to the screen size of the retrieval device.
                    <br />Whether Smart Phone, iPad, or screen the available space is used optimally for the Enderat</p>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="collapsibleSection designSection">
    <h3>Corporate Design</h3>
    <div class="row description">
        <div class="col-md-12 listWrapper">
            <div class="row listGroup">
                <div class="collapseContent col-md-7">
                    <?php echo $this->renderPicture('picture3', '/images/inner/picture3', 'Placeholder image for sms winning game', '.png');?>
                </div>
                <div class="collapseContent col-md-5">
                    <p>Modern webdesign reacts flexibly to the screen size of the retrieval device. Whether Smart Phone, iPad, or screen the available space is used optimally for the Enderat</p>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="collapsibleSection designSection">
    <h3>Image Editing and Illustration</h3>
    <div class="row description">
        <div class="col-md-12 listWrapper">
            <div class="row listGroup">
                <div class="collapseContent col-md-7">
                    <?php echo $this->renderPicture('picture3', '/images/inner/picture3', 'Placeholder image for sms winning game', '.png');?>
                </div>
                <div class="collapseContent col-md-5">
                    <p>Modern webdesign reacts flexibly to the screen size of the retrieval device. Whether Smart Phone, iPad, or screen the available space is used optimally for the Enderat</p>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="collapsibleSection designSection">
    <h3>Flyer</h3>
    <div class="row description">
        <div class="col-md-12 listWrapper">
            <div class="row listGroup">
                <div class="collapseContent col-md-7">
                    <?php echo $this->renderPicture('picture3', '/images/inner/picture3', 'Placeholder image for sms winning game', '.png');?>
                </div>
                <div class="collapseContent col-md-5">
                    <p>Modern webdesign reacts flexibly to the screen size of the retrieval device. Whether Smart Phone, iPad, or screen the available space is used optimally for the Enderat</p>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="collapsibleSection designSection">
    <h3>(responsive) Webdesign</h3>
    <div class="row description">
        <div class="col-md-12 listWrapper">
            <div class="row listGroup">
                <div class="collapseContent col-md-7">
                    <?php echo $this->renderPicture('picture3', '/images/inner/picture3', 'Placeholder image for sms winning game', '.png');?>
                </div>
                <div class="collapseContent col-md-5">
                    <p>Modern webdesign reacts flexibly to the screen size of the retrieval device. Whether Smart Phone, iPad, or screen the available space is used optimally for the Enderat</p>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="collapsibleSection designSection">
    <h3>Magazine Design</h3>
    <div class="row description">
        <div class="col-md-12 listWrapper">
            <div class="row listGroup">
                <div class="collapseContent col-md-7">
                    <?php echo $this->renderPicture('picture3', '/images/inner/picture3', 'Placeholder image for sms winning game', '.png');?>
                </div>
                <div class="collapseContent col-md-5">
                    <p>Modern webdesign reacts flexibly to the screen size of the retrieval device. Whether Smart Phone, iPad, or screen the available space is used optimally for the Enderat</p>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="collapsibleSection designSection">
    <h3>Video tutorials</h3>
    <div class="row description">
        <div class="col-md-12 listWrapper">
            <div class="row listGroup">
                <div class="collapseContent col-md-7">
                    <?php echo $this->renderPicture('picture3', '/images/inner/picture3', 'Placeholder image for sms winning game', '.png');?>
                </div>
                <div class="collapseContent col-md-5">
                    <p><a href="<?php echo $this->contactUrl();?>">Contact us</a> or Download <a href="#">Order Form</a> in PDF.</p>
                </div>
            </div>
        </div>
    </div>
</section>