<div class="introTxt">
    <h1>Data Center</h1>
    <h2>Your data is completely safe</h2>
</div>
<p>Web data protection done from the most reliable source.</p>
<div class="row innerRow">
    <div class="col-md-9 listWrapper">
        <div class="row listGroup">
            <div class="collapseContent col-md-6">
                <h3>You want</h3>
                <ul class="collapseContentBox">
                    <li>High-quality data security.</li>
                    <li>Great maintenance and back-up.</li>
                    <li>Data safety and protection.</li>
                </ul>
            </div>
            <div class="collapseContent col-md-6">
                <h3>We have</h3>
                <ul class="collapseContentBox">
                    <li>HORISEN hardware hosted in high-protection building.</li>
                    <li>Full Service regarding data management.</li>
                    <li>Your data is completely safe and protected.</li>
                </ul>
            </div>
        </div>
        <div class="row listGroup">
            <div class="collapseContent col-md-6">
                <h3>Features</h3>
                <ul class="collapseContentBox">
                    <li>Safe data protection center.</li>
                    <li>High-quality maintenance.</li>
                    <li>Best web performance at any time.</li>
                    <li>HORISEN hardware run in high security data center.</li>
                </ul>
            </div>
            <div class="collapseContent col-md-6">
                <h3>Purpose</h3>
                <ul class="collapseContentBox">
                    <li>Data is strictly private.</li>
                    <li>No access to your data files.</li>
                    <li>Maximum data protection and maintenance.</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="col-md-3">
        <div class="row">
            <div class="col-md-12 col-xs-6 innerPageImage">
                <?php echo $this->renderPicture('picture1', '/images/inner/picture1', 'Placeholder image for sms winning game', '.jpg');?>
            </div>
            <div class="col-md-12 col-xs-6 innerPageImage">
                <?php echo $this->renderPicture('picture2', '/images/inner/picture2', 'Placeholder image for sms winning game', '.jpg');?>
            </div>
        </div>
    </div>
</div>
<section class="collapsibleSection">
    <h2>Description</h2>
    <div class="row description">
        <div class="col-md-9">
            <p>The purpose of using data center is to completely secure customers’ data. HORISEN uses a data center based in Switzerland
            where we have our own hardware. This hardware hosts data from our customers and is, therefore, extremely important to keep 
            them safe and kept in privacy.</p> 

            <p>HORISEN web hosting services are, therefore, very reliable since the data keeping servers are in top-secured building which
            provides:</p>

            <ul>
                <li>Electricity always available.</li>
                <li>Backup power feeds that ensure server redundancy.</li>
                <li>Emergency power is ensured.</li>
                <li>Advanced security equipment.</li>
                <li>Access to data center is monitored and limited to members only.</li>
            </ul>

            <p>Data center building fulfils banking standards of security which requires passing through five security checkpoints that include
            manned security stations, mantraps and biometric readers.<br /> 
            So, your data hosted with HORISEN is completely safe and your website always on!</p>
        </div>
        <div class="col-md-3">
            <div class="row">
                <div class="col-md-12 col-xs-6 innerPageImage">
                    <?php echo $this->renderPicture('picture1', '/images/inner/picture1', 'Placeholder image for sms winning game', '.jpg');?>
                </div>
                <div class="col-md-12 col-xs-6 innerPageImage">
                    <?php echo $this->renderPicture('picture1', '/images/inner/picture1', 'Placeholder image for sms winning game', '.jpg');?>
                </div>
            </div>
        </div>  
    </div>
</section>