<div class="introTxt">
    <h1>Domain Registration</h1>
    <h2>Your business name is now on WWW</h2>
</div>
<p>Introduce your business to World Wide Web and register a great domain name.</p>
<div class="row innerRow">
    <div class="col-md-9 listWrapper">
        <div class="row listGroup">
            <div class="collapseContent col-md-6">
                <h3>You want</h3>
                <ul class="collapseContentBox">
                    <li>Register a great domain name for your website.</li>
                    <li>An URL which can be optimized and remembered.</li>
                    <li>Domain Registration service included into website development.</li>
                    <li>One place where you manage all your domain registrations.</li>
                </ul>
            </div>
            <div class="collapseContent col-md-6">
                <h3>We have</h3>
                <ul class="collapseContentBox">
                    <li>More than 100 different top level domains.</li>
                    <li>Carefully chosen domain with optimized URLs.</li>
                    <li>Full service web development including domain registration.</li>
                    <li>HORISEN hosts all your domains!</li>
                </ul>
            </div>
        </div>
        <div class="row listGroup">
            <div class="collapseContent col-md-6">
                <h3>Features</h3>
                <ul class="collapseContentBox">
                    <li>Large amount of top level domains to register.</li>
                    <li>Personal domain registration.</li>
                    <li>Domain transfer to any existing website.</li>
                    <li>Unique web address.</li>
                    <li>Professional email aliases.</li>
                    <li>Optimized URLs.</li>
                    <li>DNS Hosting.</li>
                    <li>Optional SSL certificates.</li>
                    <li>Technical support.</li>
                </ul>
            </div>
            <div class="collapseContent col-md-6">
                <h3>Purpose</h3>
                <ul class="collapseContentBox">
                    <li>Ensure the best domain for your business.</li>
                    <li>Secured domain registration process.</li>
                    <li>Recognizable web address.</li>
                    <li>Website support at any time.</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="col-md-3">
        <div class="row">
            <div class="col-md-12 col-xs-6 innerPageImage">
                <?php echo $this->renderPicture('picture1', '/images/inner/picture1', 'Placeholder image for sms winning game', '.jpg'); ?>
            </div>
            <div class="col-md-12 col-xs-6 innerPageImage">
                <?php echo $this->renderPicture('picture2', '/images/inner/picture2', 'Placeholder image for sms winning game', '.jpg'); ?>
            </div>
        </div>
    </div>
</div>
<section class="collapsibleSection">
    <h2>Description</h2>
    <div class="row description">
        <div class="col-md-9">
            <p>Before your web presentation goes officially online, it’s necessary to acquire a domain name and register it by going to the
                certified domain registration entity. Using HORISEN web services you get domain registration as a bonus to successfully
                developed website. On the other hand, you can purchase your domain from us regardless of the quantity of web services
                HORISEN provides you. This domain will be unique, related to your business industry and easy to be found on searching engines.</p>

            <p>So, talk to your customers, business associates or buyers in their language, using common domain name!</p>

            <p>There are over 100 top level domain (TLD) extensions that we offer. They are really cost-effective but also very popular on the
                market. You can easily search your competitors and see what their choice is – then just make a similar one and be one of the
                top-rated sites within the same business niche. New domain extensions (also called New TLDs) are launched every week, so we
                constantly keep the record and enlarge our business offer in order to satisfy every customer. And don’t worry about your
                domain renewal – we take care of that, too.<br />
                Furthermore, we offer personal consulting where our customers can rely on us when they handover all their TLDs to us for
                further management and maintenance.</p>

            <p>Besides regular Domain Registration, HORISEN offers any kind of SSL certificates. It provides security for you and your website
                visitors when exchanging data, thus also providing the highest assurance level, increase the levels of visitors’ trust and gives your
                website a visible, world-standard security credentials. Using SSL certificate can only improve the conversion rates and brings you
                more revenue through loyal customers.</p>
        </div>
        <div class="col-md-3">
            <div class="row">
                <div class="col-md-12 col-xs-6 innerPageImage">
                    <?php echo $this->renderPicture('picture1', '/images/inner/picture1', 'Placeholder image for sms winning game', '.jpg'); ?>
                </div>
                <div class="col-md-12 col-xs-6 innerPageImage">
                    <?php echo $this->renderPicture('picture1', '/images/inner/picture1', 'Placeholder image for sms winning game', '.jpg'); ?>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="collapsibleSection">
    <h2>Preparations</h2>
    <div class="row">
        <div class="col-md-12">
            <p>Website domain registration is done along with web development and another web services HORISEN provides for your company. <br />
                After your website is done, look at our top level domain (TLD) list and find the best one for your business. We will take the rest
                of the business done very fast.</p>

        </div>
    </div>
</section>
<section class="collapsibleSection">
    <h2>Prices</h2>
    <div class="row">
        <div class="col-md-12">
            <p><a href="<?php echo $this->contactUrl();?>">Contact us</a> or Download <a href="#">Order Form</a> in PDF.</p>
        </div>
    </div>
</section>

