<div class="introTxt">
    <h1>HORISEN Expertise</h1>
    <h2>Our marketing technology specialists provide you only the best</h2>
</div>
<p>Many say they can, but just a few of them can really do it.</p>
<div class="expertiseContent">
    <h2>Methodology</h2>
    <p>In HORISEN you work with the best marketing technologists implementing your cross-media marketing strategy. Implementing 
        strategy requires resources that are well beyond the regular marketing staff in terms of expertise, skills and technical knowledge 
        in particular.</p>
    <p>Customers want competent specialists who solve their issues quickly and successfully. HORISEN is very demanding when it
        comes to its employees in order to ensure the real quality delivered to customers. A high-quality work can be provided only by 
        employees who have necessary experience and bring great motivation with themselves. HORISEN guarantees the quality of its 
        services by its high standards and established business processes.</p>
    <p>We are a trusted specialist for combined marketing and technology services for any company, regardless of its size and market
        impact. As a company with lifelong learning principles, we are constantly walking on the edge of newest technology and 
        following trends; being up-to-date is a must for our employees and a company itself.</p>
    <p>HORISEN is a fast growing company – we are in constant search for qualified marketing and technology specialists. Marketing 
        technology is still a fresh term on the market meaning that the process of acquiring people that work on both frontiers is 
        developing. But, we are way ahead. Marketing technology is what we are already doing – our expertise is proven through 
        numerous successful customer projects.</p>
    <p>We are really passionate about taking on immense challenges which modern technology imposes nowadays. To be an expert, 
        first you need to prove your professional excellence and efficiency. This is how our marketing technology specialists’ team was 
        built.</p>
    <br />
    <p><span class="bold">Expertize:</span> We are convinced that each activity requires appropriate level of knowledge, either it is technical or in terms of the
        market. In order to raise the competitiveness level, we are a learning organization, both for the good of our customers and our 
        own good.</p>
    <p><span class="bold">Excellence:</span> In everything we do, we try to follow only the best examples within the industry and strive for the high-quality of our 
        business processes and products. Because we want to be a competent service for our customers and partners, we will continue 
        to constantly develop and improve.</p>
    <p><span class="bold">Efficiency:</span> We strive to be efficient in our core business. For this purpose we highly optimize our business processes and
        compare our job with the best players in our industry. Therefore, we perceive only the most important business opportunities 
        and the right ones! Not to forget that our business efficiency depends on our project partners.</p>
</div>

<p><a href="<?php echo $this->contactUrl();?>">Contact us</a> and find out more!</p>