<div class="introTxt">
    <h1>Facebook Ads</h1>
    <h2>Advertise your business or brand on Facebook</h2>
</div>
<p>Start your successful social media campaign targeting the right audience.</p>
<div class="row innerRow">
    <div class="col-md-9 listWrapper">
        <div class="row listGroup">
            <div class="collapseContent col-md-6">
                <h3>You want</h3>
                <ul class="collapseContentBox">
                    <li>Place Advertisement on Facebook.</li>
                    <li>More people on your business page.</li>
                    <li>To advertise new product or service.</li>
                    <li>Convert visitors into customers.</li>
                    <li>Increase sales.</li>
                </ul>
            </div>
            <div class="collapseContent col-md-6">
                <h3>We have</h3>
                <ul class="collapseContentBox">
                    <li>360° Advertisement Service.</li>
                    <li>Experience in live campaign positioning.</li>
                    <li>350+ successfully run ad campaigns.</li>
                    <li>Facebook Ads experts’ support.</li>
                    <li>Ads concept planning and implementing.</li>
                </ul>
            </div>
        </div>
        <div class="row listGroup">
            <div class="collapseContent col-md-6">
                <h3>Features</h3>
                <ul class="collapseContentBox">
                    <li>Facebook Ads management control.</li>
                    <li>Implementation of multiple Ads per single campaign.</li>
                    <li>Smart budgeting and expenditures’ overview.</li>
                    <li>Quality analysis of past and current campaigns.</li>
                    <li>Ads planning and implementation support.</li>
                </ul>
            </div>
            <div class="collapseContent col-md-6">
                <h3>Purpose</h3>
                <ul class="collapseContentBox">
                    <li>Facebook fan page attractiveness and visibility. </li>
                    <li>Boosts engagement.</li>
                    <li>Increases fan page community.</li>
                    <li>Advertise new products/services.</li>
                    <li>Be visible and competitive within the target market.</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="col-md-3">
        <div class="row">
            <div class="col-md-12 col-xs-6 innerPageImage">
                <?php echo $this->renderPicture('picture1', '/images/inner/picture1', 'Placeholder image for sms winning game', '.jpg');?>
            </div>
            <div class="col-md-12 col-xs-6 innerPageImage">
                <?php echo $this->renderPicture('picture2', '/images/inner/picture2', 'Placeholder image for sms winning game', '.jpg');?>
            </div>
        </div>
    </div>
</div>
<section class="collapsibleSection">
    <h2>Description</h2>
    <div class="row description">
        <div class="col-md-9">
<p>Facebook has already given you the opportunity to advertise and bring more engagement to your business page. But, the most important thing is to think cleverly and wrap-up promo campaigns targeting the right audience. </p>

<p>With Ads Manager you have a complete overview of your current campaigns which you can edit and monitor, but also track conversions. Moreover, the idea to start and organize Facebook Ads does not finish the whole process. At this point you have to start thinking about: </p>

<ol>
    <li>Engaging your fans with great content on your business page; </li>
    <li>How to influence more people – by organizing viral contests on your fan page, your fans get encouraged to share and invite their friends to join; </li>
    <li>Retaining fans on your business page and increase traffic to your website.</li>
</ol>

<p>At this point you get a full support from our social media marketing experts’ team disregarding the number of campaigns you wish to advertise on Facebook. </p>

<p>Facebook Ad can be created if you want to promote your page. This means that people will be shown the page with a visible “Like the page” button to click on. On the other hand, the most useful promotion is “Boost Post” – you can effectively target your customers with a single post. Since Facebook organic reach (also posting) has significantly decreased, boosting posts is a real visibility booster and, if you choose to boost a post with most engagement (comments, likes), that means you care about your customers. </p>
<p>Promoting your posts will only increase the virality and fan page buzz and will increase the number of your loyal customers.</p>
        </div>
        <div class="col-md-3">
            <div class="row">
                <div class="col-md-12 col-xs-6 innerPageImage">
                    <?php echo $this->renderPicture('picture1', '/images/inner/picture1', 'Placeholder image for sms winning game', '.jpg');?>
                </div>
                <div class="col-md-12 col-xs-6 innerPageImage">
                    <?php echo $this->renderPicture('picture1', '/images/inner/picture1', 'Placeholder image for sms winning game', '.jpg');?>
                </div>
            </div>
        </div>  
    </div>
</section>
<section class="collapsibleSection">
    <h2>Short promotion guide</h2>
    <div class="row">
        <div class="col-md-12">  
            <p>You have chosen the elements necessary for your new product promotion on Facebook. After you’ve prepared the whole campaign (define texts, make images, videos or links to your website/blog/other relevant web page), it’s time to advertise and attract visitors to make it viral! Since Facebook has dramatically declined organic reach for fan pages, the only way you will attract new visitors and well targeted audience is via Facebook Ads. </p>
            <p>A set of well-defined and, above all, cleverly designed ads will help you drive attention to your business page and send the right message about great new things you do. This ad goes only to narrowed group of people (current or potential customers) and calls them to: like your page, participate in your campaign, support a cause, share a post to win a prize, and many more. By providing prizes for fan page campaign, you will attract more people to your business, engage them to your fan page and create strong brand awareness. </p>
        </div>
    </div>
</section>
<section class="collapsibleSection">
    <h2>Prices</h2>
    <div class="row">
        <div class="col-md-12">  
            <p><a href="<?php echo $this->contactUrl();?>">Contact us</a> or Download <a href="#">Order Form</a> in PDF.</p>
        </div>
    </div>
</section>