<div class="introTxt">
    <h1>Google Ads</h1>
    <h2>Another way to be the business number one</h2>
</div>
<p>Smart optimization and additional online advertising value for your business.</p>
<div class="row innerRow">
    <div class="col-md-9 listWrapper">
        <div class="row listGroup">
            <div class="collapseContent col-md-6">
                <h3>You want</h3>
                <ul class="collapseContentBox">
                    <li>Excellent website visibility.</li>
                    <li>To generate leads online.</li>
                    <li>To show up on Google search – page one. </li>
                    <li>Good rating among competitors. </li>
                    <li>Relevance on the market.</li>
                    <li>Single point of contact for your Online Ads.</li>
                </ul>
            </div>
            <div class="collapseContent col-md-6">
                <h3>We have</h3>
                <ul class="collapseContentBox">
                    <li>Experience in creating and implementing successful Google Ads campaigns.</li>
                    <li>Carefully planned Google Ads campaigns that drive more traffic to your website.</li>
                    <li>Full Google Ads management support.</li>
                    <li>Help for campaign’s evaluation.</li>
                    <li>Additional support for testing and monitoring process.</li>
                    <li>Experienced team that creates, manages and evaluates Ads campaign from A-Z.</li>
                </ul>
            </div>
        </div>
        <div class="row listGroup">
            <div class="collapseContent col-md-6">
                <h3>Features</h3>
                <ul class="collapseContentBox">
                    <li>Single point-of-contact for Ads campaigns.</li> 
                    <li>Account on Google AdWords.</li>
                    <li>Free access to all account updates.</li> 
                    <li>Full ads campaign design.</li> 
                    <li>Success measurement.</li> 
                    <li>Competitor benchmarking.</li>
                    <li>Reports for Google Ads performance.</li> 
                    <li>Success measurement included.</li> 
                    <li>Setting up more Ads at the same time.</li>
                </ul>
            </div>
            <div class="collapseContent col-md-6">
                <h3>Purpose</h3>
                <ul class="collapseContentBox">
                    <li>Be on Google Search page 1.</li>
                    <li>More traffic to your website.</li>
                    <li>Increased conversions: visitor &gt; customer.</li>
                    <li>Increase competitiveness on the market.</li>
                    <li>Promote your business in the best possible way.</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="col-md-3">
        <div class="row">
            <div class="col-md-12 col-xs-6 innerPageImage">
                <?php echo $this->renderPicture('picture1', '/images/inner/picture1', 'Placeholder image for sms winning game', '.jpg');?>
            </div>
            <div class="col-md-12 col-xs-6 innerPageImage">
                <?php echo $this->renderPicture('picture2', '/images/inner/picture2', 'Placeholder image for sms winning game', '.jpg');?>
            </div>
        </div>
    </div>
</div>
<section class="collapsibleSection">
    <h2>Description</h2>
    <div class="row description">
        <div class="col-md-9">
            <p>Google Ads allows you to put your business' message in front of your potential customers at the right time and place. Your task
            is to simply design the Ad, choose the searching terms which correspond to your products or services and then set the overall 
            budget. When your customers search the term they want (and you offer), the possibility for ending up on your website is much 
            bigger. The difference is when your regular customers search your business, they will search by the name of the company; on 
            the other hand, your potential customers will search the topic or will use keywords that might lead them to your page, but also 
            to your competitors’ page.</p> 

            <p>This includes: fully optimized content, with smart keywords and description included. In this way Google Ads help your potential 
            customers choosing your business instead another one. Our experts' team help you creating, positioning and monitoring Google 
            Ads campaign at any point. Success measurement is one of the key things for the overall performance of your Ad. This means 
            that our team take care of the analytics during and after each campaign, does regular competitor benchmarking and measures 
            its success for future campaigns' optimization.</p>

            <p>HORISEN has got significant experience in self-positioning using Google Ads and, therefore, its competence for giving support to 
            its partners is out of any doubt.</p>
            
            <p>Be there for your customers for anything they need and can find with you! Google is searching engine number one and your 
            business needs to be well-crafted and always present. Present for your business promotion, but helpful for your customers.</p>     
        </div>
        <div class="col-md-3">
            <div class="row">
                <div class="col-md-12 col-xs-6 innerPageImage">
                    <?php echo $this->renderPicture('picture1', '/images/inner/picture1', 'Placeholder image for sms winning game', '.jpg');?>
                </div>
                <div class="col-md-12 col-xs-6 innerPageImage">
                    <?php echo $this->renderPicture('picture1', '/images/inner/picture1', 'Placeholder image for sms winning game', '.jpg');?>
                </div>
            </div>
        </div>  
    </div>
</section>
<section class="collapsibleSection">
    <h2>Campaign Idea</h2>
    <div class="row">
        <div class="col-md-12">  
            <h3>Idea for particular Google Ads campaign</h3>
            <ol>
                <li>The best-selling product promotion – you know which product was the best-seller in the period behind.</li>
                <li>Development of website lading page – product promotion with great discount.</li>
                <li>Google Ads campaign development.</li>
                <li>Budgeting – set up daily or monthly budgeting, depending on campaign's duration.</li>
                <li>Campaign monitoring and collecting leads through landing page.</li>
                <li>Comparison of campaign investment and promotion earnings.</li>
            </ol>
        </div>
    </div>
</section>
<section class="collapsibleSection">
    <h2>Prices</h2>
    <div class="row">
        <div class="col-md-12">  
            <p><a href="<?php echo $this->contactUrl();?>">Contact us</a> or Download <a href="#">Order Form</a> in PDF.</p>
        </div>
    </div>
</section>