<div class="introTxt">
    <h1>Web Hosting</h1>
    <h2>Dedicated hosting for extraordinary online performance</h2>
</div>
<p>Best web hosting service for reliable, updated and secure browsing experience.</p>
<div class="row innerRow">
    <div class="col-md-9 listWrapper">
        <div class="row listGroup">
            <div class="collapseContent col-md-6">
                <h3>You want</h3>
                <ul class="collapseContentBox">
                    <li>Secure server space for your websites and emails.</li>
                    <li>Reliable website performance.</li>
                    <li>Dedicated technical support.</li>
                </ul>
            </div>
            <div class="collapseContent col-md-6">
                <h3>We have</h3>
                <ul class="collapseContentBox">
                    <li>Space in data center provided for quality hosting.</li>
                    <li>Quality maintenance and website availability.</li>
                    <li>Personal technical support.</li>
                </ul>
            </div>
        </div>
        <div class="row listGroup">
            <div class="collapseContent col-md-6">
                <h3>Features</h3>
                <ul class="collapseContentBox">
                    <li>High security for your website.</li>
                    <li>Internal server space provided.</li>
                    <li>Full server redundancy provided.</li>
                    <li>Globally available data (through website domain).</li>
                    <li>Full web hosting service provided.</li>
                    <li>Support provided by phone, email and messaging.</li>
                    <li>Private cloud infrastructure included.</li>
                </ul>
            </div>
            <div class="collapseContent col-md-6">
                <h3>Purpose</h3>
                <ul class="collapseContentBox">
                    <li>Safe file storage and maintenance.</li>
                    <li>Website availability 24/7.</li>
                    <li>External technical support.</li>
                    <li>Cost-effective for additional web data storage services.</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="col-md-3">
        <div class="row">
            <div class="col-md-12 col-xs-6 innerPageImage">
                <?php echo $this->renderPicture('picture1', '/images/inner/picture1', 'Placeholder image for sms winning game', '.jpg');?>
            </div>
            <div class="col-md-12 col-xs-6 innerPageImage">
                <?php echo $this->renderPicture('picture2', '/images/inner/picture2', 'Placeholder image for sms winning game', '.jpg');?>
            </div>
        </div>
    </div>
</div>
<section class="collapsibleSection">
    <h2>Description</h2>
    <div class="row description">
        <div class="col-md-9">
            <p>Web hosting is specific server space provided by HORISEN which keeps all your data files safe. These files are globally available
                using your business' domain. Thanks to our own hardware which we host in a high-protection building (<a href="<?php echo $this->url(array('module' => 'cms', 'controller' => 'page', 'action' => 'index', 'page_id' => 63),'cms',true);?>">data center</a>), your 
            website performance quality has been brought to maximum.</p> 

            <p>There are numerous benefits of HORISEN web hosting service:</p>

            <ul>
                <li>We take care of the server's maintenance.</li>
                <li>High-security web hosting using our own hardware.</li>
                <li>No server management required for high-traffic websites.</li>
                <li>Delivering high performance and full redundancy.</li>
                <li>Maximum security with regular backups and web space recovery.</li>
                <li>Dedicated resources to your applications.</li>
            </ul>
        </div>
        <div class="col-md-3">
            <div class="row">
                <div class="col-md-12 col-xs-6 innerPageImage">
                    <?php echo $this->renderPicture('picture1', '/images/inner/picture1', 'Placeholder image for sms winning game', '.jpg');?>
                </div>
                <div class="col-md-12 col-xs-6 innerPageImage">
                    <?php echo $this->renderPicture('picture1', '/images/inner/picture1', 'Placeholder image for sms winning game', '.jpg');?>
                </div>
            </div>
        </div>  
    </div>
</section>
<section class="collapsibleSection">
    <h2>Preparations / Development</h2>
    <div class="row">
        <div class="col-md-12">  
            <p>Web hosting is done within HORISEN internal server or using private cloud infrastructure offered to its clients. It's a service 
            available next to successful website development and regular technical support / maintenance.</p>
        </div>
    </div>
</section>
<section class="collapsibleSection">
    <h2>Prices</h2>
    <div class="row">
        <div class="col-md-12">  
            <p><a href="<?php echo $this->contactUrl();?>">Contact us</a> or Download <a href="#">Order Form</a> in PDF.</p>
        </div>
    </div>
</section>