<div class="address-contact">
    <h1>Address and Contact</h1>
    <ul>
        <li>HORISEN AG</li>
        <li>Hauptstrasse 65</li>
        <li>CH-9400 Rorschach</li>
        <li>Switzerland</li>
    </ul>
    <div class="row">
        <div class="col-md-6 col-xs-12">
            <div class="col-md-3 col-xs-6">
                <p>Tel</p>
                <p>Fax</p>
            </div>
            <div class="col-md-3 col-xs-6">
                <p>+41 58 700 00 00</p>
                <p>+41 58 700 00 01</p>
            </div>
            <div class="col-md-3 col-xs-6">
                <p>Email</p>
                <p>Web</p>
            </div>
            <div class="col-md-3 col-xs-6">
                <p><a href="mailto:info@horisen.com">info@horisen.com</a></p>
                <p><a href="http://www.horisen.com" target="_blank">www.horisen.com</a></p>
            </div>
        </div>
    </div>
</div>
<div class="company-information">
    <h1>Company Information</h1>
    <div class="row">
        <div class="col-md-6 col-xs-12">
            <div class="col-md-6">
                <p>CEO</p>
            </div>
            <div class="col-md-6">
                <p>Dipl. Ing. Fabrizio Salanitri</p>
            </div>
            <div class="col-md-6">
                <p>Board of Directors</p>
            </div>
            <div class="col-md-6">
                <p>Dipl. Ing. Fabrizio Salanitri, Chairman<br />
                    Michael Olbrich<br />
                    Ilija Reymond</p>
            </div>
            <div class="col-md-6">
                <p>VAT Nr.:</p>
            </div>
            <div class="col-md-6">
                <p>CHE-109.327.117 MWST</p>
            </div>
            <div class="col-md-6">
                <p>Company Registration Nr.:</p>
            </div>
            <div class="col-md-6">
                <p>CH-170.4.003.420-4</p>
            </div>
            <div class="col-md-6">
                <p>D-U-N-S-Nr.:</p>
            </div>
            <div class="col-md-6">
                <p>48-162-2368</p>
            </div>
        </div>
    </div>
</div>