<div class="introTxt">
    <h1>Inbound SMS Service</h1>
    <h2>Easily engage in 2-way SMS conversation</h2>
</div>
<p>Marketing starts with successful SMS interaction with your customers.</p>
<div class="row innerRow">
    <div class="col-md-9 listWrapper">
        <div class="row listGroup">
            <div class="collapseContent col-md-6">
                <h3>You want</h3>
                <ul class="collapseContentBox">
                    <li>A global reply service.</li>
                    <li>Personalized communication.</li>
                    <li>Higher customer engagement.</li>
                    <li>To collect customer data.</li>
                </ul>
            </div>
            <div class="collapseContent col-md-6">
                <h3>We have</h3>
                <ul class="collapseContentBox">
                    <li>Inbound SMS service that includes direct interaction with customers.</li>
                    <li>HORISEN Inbound SMS service can be used globally.</li>
                    <li>A service that includes: customer questions, inquiries, replies from all over the world.</li>
                    <li>Online database which aggregate customer data and other information.</li>
                </ul>
            </div>
        </div>
        <div class="row listGroup">
            <div class="collapseContent col-md-6">
                <h3>Features</h3>
                <ul class="collapseContentBox">
                    <li>Global reach through a single point of access.</li>
                    <li>Two-way SMS communication enabled.</li>
                    <li>SMS applications included.</li>
                    <li>SMS integration into different mobile applications.</li>
                    <li>Technical support included.</li>
                    <li>Integrated SMS generator (online system).</li>
                    <li>Full SMS control and management.</li>
                    <li>Business account included.</li>
                    <li>Opt-in messages included.</li>
                </ul>
            </div>
            <div class="collapseContent col-md-6">
                <h3>Purpose</h3>
                <ul class="collapseContentBox">
                    <li>Interaction with customers.</li>
                    <li>Convert leads into customers.</li>
                    <li>Quality customer support.</li>
                    <li>To stimulate customer interest for your product / service.</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="col-md-3">
        <div class="row">
            <div class="col-md-12 col-xs-6 innerPageImage">
                <?php echo $this->renderPicture('picture1', '/images/inner/picture1', 'Placeholder image for sms winning game', '.jpg');?>
            </div>
            <div class="col-md-12 col-xs-6 innerPageImage">
                <?php echo $this->renderPicture('picture2', '/images/inner/picture2', 'Placeholder image for sms winning game', '.jpg');?>
            </div>
        </div>
    </div>
</div>
<section class="collapsibleSection">
    <h2>Description</h2>
    <div class="row description">
        <div class="col-md-9">
            <p>Inbound SMS service can collect SMS messages from worldwide and enables a two-way SMS interactivity which represents a
            starting point for your successful marketing campaigns, effective social networking and increases customer loyalty. The main 
            goal is to collect mobile phone numbers that will bring the quality to your customer database system. In this way you will 
            increase sales, business availability and/or brand visibility, but will also stimulate your customer’s interest for your products or 
            services.</p> 

            <p>HORISEN provides Inbound SMS service that generates local, but also international mobile phone numbers and is available
            worldwide. This service allows customers to easily interact with your business: they can send you questions, inquires, requests 
            for free content download or text-to-win messages. Interactive SMS communication enables your brand to stick to customers’ 
            minds. As a result, you can measure the level of customer loyalty after each campaign you organized.</p>

            <p>Inbound SMS service is a key element which allows you to interact with your mobile audience, motivate your customers and 
            build great brand awareness through various advertising or marketing campaigns.</p>
            
            <h3>Here are some of the key benefits you get with Inbound SMS service:</h3>
            <ul>
                <li>Customer interaction with your brand, specific product or service.</li>
                <li>International mobile dialogue is enabled.</li>
                <li>Reliable and fast SMS delivery.</li>
                <li>Reliable infrastructure which is able to process high volumes of incoming SMS in short timeframes.</li>
            </ul>
        </div>
        <div class="col-md-3">
            <div class="row">
                <div class="col-md-12 col-xs-6 innerPageImage">
                    <?php echo $this->renderPicture('picture1', '/images/inner/picture1', 'Placeholder image for sms winning game', '.jpg');?>
                </div>
                <div class="col-md-12 col-xs-6 innerPageImage">
                    <?php echo $this->renderPicture('picture1', '/images/inner/picture1', 'Placeholder image for sms winning game', '.jpg');?>
                </div>
            </div>
        </div>  
    </div>
</section>
<section class="collapsibleSection">
    <h2>Preparations</h2>
    <div class="row">
        <div class="col-md-12">  
            <h3>How does Inbound SMS service looks like when a user sends SMS:</h3>
            <ol>
                <li>There is a globally reachable number (number to send SMS to).</li>
                <li>A user can send SMS to selected number from everywhere in the world.</li>
                <li>This is not extra-charging message. The cost is same as regular SMS cost per operator.</li>
                <li>The system catches the SMS and sends it to your specific URL.</li>
                <li>After you select and analyze the message, it would appear in our internal system.</li>
                <li>You can also define email address and receive customer SMS.</li>
            </ol>
        </div>
    </div>
</section>
<section class="collapsibleSection">
    <h2>Prices</h2>
    <div class="row">
        <div class="col-md-12">  
            <p><a href="<?php echo $this->contactUrl();?>">Contact us</a> or Download <a href="#">Order Form</a> in PDF.</p>
        </div>
    </div>
</section>