<div class="introTxt">
    <h1>Landing Pages</h1>
    <h2>Fast convertors which carry effective content</h2>
</div>
<p>Call-to-action tools that capture early customers fast!</p>
<div class="row innerRow">
    <div class="col-md-9 listWrapper">
        <div class="row listGroup">
            <div class="collapseContent col-md-6">
                <h3>You want</h3>
                <ul class="collapseContentBox">
                    <li>Effective new promotion web page.</li>
                    <li>Time-limited promo campaigns.</li>
                    <li>Better product &quot;shopping window&quot;.</li>
                    <li>Attractive design for your selling page.</li>
                    <li>Short time to market your promo page.</li>
                </ul>
            </div>
            <div class="collapseContent col-md-6">
                <h3>We have</h3>
                <ul class="collapseContentBox">
                    <li>Customizable web page elements.</li>
                    <li>Flexible and fast promo pages' development.</li>
                    <li>Automation process that established communication with customers.</li>
                    <li>Many custom design options at hand.</li>
                    <li>Fast implementation of your landing page.</li>
                </ul>
            </div>
        </div>
        <div class="row listGroup">
            <div class="collapseContent col-md-6">
                <h3>Features</h3>
                <ul class="collapseContentBox">
                    <li>Free text-editable fields.</li>
                    <li>Drag and drop elements.</li>
                    <li>Automated e-mail notifications.</li>
                    <li>Custom call-to-actions.</li>
                    <li>A/B testing included or on demand.</li>
                    <li>Conversion analysis report.</li>
                    <li>Contact database and quality data export.</li>
                    <li>Custom design and CSS adaptations.</li>
                </ul>
            </div>
            <div class="collapseContent col-md-6">
                <h3>Purpose</h3>
                <ul class="collapseContentBox">
                    <li>Fast conversions.</li>
                    <li>Capturing quality contacts.</li>
                    <li>Instant selling.</li>
                    <li>Early-bird product promotion.</li>
                    <li>Service quality evaluation.</li>
                    <li>Separate product's shopping window.</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="col-md-3">
        <div class="row">
            <div class="col-md-12 col-xs-6 innerPageImage">
                <?php echo $this->renderPicture('picture1', '/images/inner/picture1', 'Placeholder image for sms winning game', '.jpg');?>
            </div>
            <div class="col-md-12 col-xs-6 innerPageImage">
                <?php echo $this->renderPicture('picture2', '/images/inner/picture2', 'Placeholder image for sms winning game', '.jpg');?>
            </div>
        </div>
    </div>
</div>
<section class="collapsibleSection">
    <h2>Description</h2>
    <div class="row description">
        <div class="col-md-9">
            <p>The purpose of effective landing pages is to convert visitors into leads. But how? Attractive landing page with great design and 
            custom contact form is simply not enough. Landing pages need to speak with visitors and understand their needs and 
            expectations. That’s why this unique page can do the magic for your business in a few seconds.</p> 

            <p>Landing pages are very flexible when it comes to page editing and form creating. By smart content distribution you can generate
            and convert a lot of traffic coming to this page only. Either you organize a special promotion or a time-limited campaign for your 
            new product / service, this type of web presentation will accelerate the conversion process. Landing pages are made to attract 
            users’ attention and it’s very important to work on its design first!</p>

            <p>Another thing which can be included prior to real landing page launching is A/B testing done. In this way, you will be sure which
            type of content, page composition and design works best! With customizable call-to-actions you can easily attract the right 
            visitors to come and see your proposal or selling argument. You are able to test any element including headlines, call-to-action 
            and images; also preview differently edited landing pages and see which version drives the most conversions.</p>

            <p>With its specific URL or sub-domain, a landing page can be easily analysed. Each promotion can be measured continuously in
            order to make future promotion optimizations or adaptations (if needed).</p> 

            <p>The automated email notifications are great point for successful email marketing and regular newsletter updates. In this way
            you do not only establish communication with your customers, but also remind them of other offers coming from your brand or 
            specific business niche.</p>

        </div>
        <div class="col-md-3">
            <div class="row">
                <div class="col-md-12 col-xs-6 innerPageImage">
                    <?php echo $this->renderPicture('picture1', '/images/inner/picture1', 'Placeholder image for sms winning game', '.jpg');?>
                </div>
                <div class="col-md-12 col-xs-6 innerPageImage">
                    <?php echo $this->renderPicture('picture1', '/images/inner/picture1', 'Placeholder image for sms winning game', '.jpg');?>
                </div>
            </div>
        </div>  
    </div>
</section>
<section class="collapsibleSection">
    <h2>Preparations</h2>
    <div class="row">
        <div class="col-md-12">  
            <h3>Preparations from your side</h3>
            <ul>
                <li>Idea for promotion (e.g. seasonal promotion, sales, call-to-action for joining a cause, etc.)</li>
                <li>Writing text elements with call-to-action included.</li>
                <li>Choosing fields for contact form or e-mail subscription.</li>
                <li>Decide upon design elements and visual appearance.</li>
                <li>Do the testing and see which version suits you best.</li>
                <li>Launch your landing page and promote it on different offline/online media, including social media channels as well.</li>
            </ul>
            <h3>How your customers end up on your landing page</h3>
            <ul>
                <li>You created an advertisement.</li>
                <li>The Ad is posted on: your promo flyers, store banner, TV Ad, product package, or social media accounts including
                Facebook or Google Ads.</li>
                <li>By entering your website page URL or clicking on the promo link (online Ad), visitors are redirected to landing page first.</li>
                <li>They see the attractive content and leave their data / answer the question or whatever you defined within a
                promotion.</li>
                <li>After receiving email notification, they can proceed to another activity; otherwise, this will be the last step – if prizes or
                discounts are, for example, announced to be distributed later.</li>
            </ul>
        </div>
    </div>
</section>
<section class="collapsibleSection">
    <h2>Prices</h2>
    <div class="row">
        <div class="col-md-12">  
            <p><a href="<?php echo $this->contactUrl();?>">Contact us</a> or Download <a href="#">Order Form</a> in PDF.</p>
        </div>
    </div>
</section>