<div class="introTxt">
    <h1>Marketing Technology</h1>
    <h2>Marketing and Technology have become one</h2>
</div>
<p>Smart and easy marketing automation executable for any business or industry size.</p>
<h2>Our Business</h2>
<p>It all started when successful marketers and CMOs (Chief marketing officers) couldn't manage their efforts without a quality
    technical support. They battled between using standard and digital way of communication. And the digital has won. Standard 
    communication consisted mostly of personal selling, PR and sponsorships, advertising on electronic media, sending direct mails 
    and taking care about product packaging. New, digital communication is about:</p>
<ul>
    <li>search marketing (SEO, paid search, etc.)</li>
    <li>online PR – referring to brand protection and link-building</li>
    <li>then interactive ads</li>
    <li>opt-in email</li>
    <li>viral marketing</li>
</ul>
<p>New marketing approach requires certain technological inputs and knowledge. A modern marketer is, therefore, a technically-
    savvy professional who understands the needs of the market and his consumers well and uses these technological inputs to 
    achieve final goals of his customers.</p>
<p>Digital marketing era imposes strong professionalism on both sides – marketing and technology. HORISEN employees are
    specialists in marketing, but also specialists in technology. We talk the same language in the both worlds and have strong know-
    how arguments when it comes to final customer experience. Our specialists use different web, mobile phones, social media and 
    customer relationship management (CRM) systems based on our own developed and hosted software. We understand both 
    marketing and technology departments’ needs and our task is to successfully mediate between these two essentials in today’s 
    digital world.</p>
<p>Although marketing technology is, practically, a new business field, HORISEN team is already way ahead using innovations in
    technology to remain relevant in all forms of marketing for our customers. We work and connect marketing and technology by 
    integrating IT with marketing department. Marketing technologists in HORISEN are people who are equally adept at marketing 
    and technology. These people are bridge builders between marketing officer and information officer and they, actually, help you 
    navigate the digital world.</p>
<p>Marketing technologists working in HORISEN combine different talents and skills that create a real professional in this field. Our
    marketing technologist thinks logically, has extraordinary software developer skills; but also heart of an artist and creative spirit 
    that brings great content and visual solutions fast. Hiring a marketing technologist that understands and will better execute your 
    marketing strategies in a digital world is the best investment you can make when it comes to overall customer experience.</p>

<p>Reasons why your company needs a marketing technologist:</p>
<ol>
    <li>It helps you build real customer loyalty – with speed and agility.</li>
    <li>Your business productivity rises – spending less time investing in necessary technology and right marketers with know-
        how strategies.</li>
    <li>All aspects of your business are simply focused on your customers – today, quality data is the weapon used to maintain
        customer loyalty.</li>
    <li>Marketing technologist helps your company by providing a unique value proposition – market understanding, service
        delivery and marketing operations around overall client experience.</li>
    <li>You become a customer-centric company – HORISEN team of marketing technologists will do everything else.</li>
</ol>

<p>We at HORISEN architect our marketing technology infrastructure according to our customers' needs. And we are a key
    competitor within this field. Our professionals are intuitive users of technology and passionate to apply it in brilliant marketing 
    and extraordinary customer experience. Marketing technologists of HORISEN make marketing tech-savvy.</p>
<p>Now you see that the IT sector has become an unavoidable part of any successful marketing effort which emphasizes the need
    for IT expertise. This expertise is very precise and complex so you do not always have the right people in your team while 
    still need to handle numerous customer requests. HORISEN has got both experienced technology specialists and marketing 
    specialists, but also the right technology which satisfies customer needs. The broad expertise comes out of many successfully 
    run projects with companies from various sectors: from SMEs to Fortune 500 companies. For more information, take a look at 
    our references!</p>
<p>Technology decisions and the right marketing strategy - This is why marketing must become one with technology.</p>

<h3>HORISEN – marketing technology for marketing professionals.</h3>