<div class="introTxt">
    <h1>megafanapps.com</h1>
    <h2>Facebook fan page apps for social media professionals</h2>
</div>
<p>Smart apps for social enterprises – successful social media marketing done like never before.</p>
<div class="row innerRow">
    <div class="col-md-9 listWrapper">
        <div class="row listGroup">
            <div class="collapseContent col-md-6">
                <h3>You want</h3>
                <ul class="collapseContentBox">
                    <li>To pimp-up your fan page.</li>
                    <li>More viral buzz on your fan page.</li>
                    <li>Cost-effective promo activities.</li>
                    <li>Increased brand awareness and customer attraction.</li>                    
                </ul>
            </div>
            <div class="collapseContent col-md-6">
                <h3>We have</h3>
                <ul class="collapseContentBox">
                    <li>Variety of customer engaging apps with quality contacts.</li>
                    <li>Highly entertaining apps which drive virality to your business Facebook page.</li>
                    <li>Apps with digital instant vouchers and excellent communication options beyond any campaign.</li>
                    <li>Excellent app design solutions for any occasion.</li>
                </ul>
            </div>
        </div>
        <div class="row listGroup">
            <div class="collapseContent col-md-6">
                <h3>Features</h3>
                <ul class="collapseContentBox">
                    <li>Easy-to-navigate app admin cockpit.</li>
                    <li>Unlimited number of campaigns per app.</li>
                    <li>Unlimited number of Facebook page likes.</li>
                    <li>Mobile access to live campaigns.</li>
                    <li>Country targeting capability.</li>
                    <li>WYSIWYG editor for live configuration preview.</li>
                    <li>Fully customizable contact form.</li>
                    <li>White label email communication.</li>
                    <li>Real-time statistics and quality campaign data export.</li>
                    <li>Ready-made app designs and custom CSS upload.</li>
                    <li>Instant coupon awards for each participation.</li>
                </ul>
            </div>
            <div class="collapseContent col-md-6">
                <h3>Purpose</h3>
                <ul class="collapseContentBox">
                    <li>Fast customer conversion: visitor &gt; fan &gt; lead &gt; customer.</li>
                    <li>More traffic to specific website or landing page.</li>
                    <li>Ideal for seasonal promotions.</li>
                    <li>Cost-effective advertising: no extra payments.</li>
                    <li>Accurate audience behavior workflow.</li>
                    <li>Great starting point for other online/offline marketing promotion.</li>
                    <li>Suitable to any industry or company size.</li>                    
                </ul>
            </div>
        </div>
    </div>
    <div class="col-md-3">
        <div class="row">
            <div class="col-md-12 col-xs-6 innerPageImage">
                <?php echo $this->renderPicture('picture1', '/images/inner/picture1', 'Placeholder image for sms winning game', '.jpg');?>
            </div>
            <div class="col-md-12 col-xs-6 innerPageImage">
                <?php echo $this->renderPicture('picture2', '/images/inner/picture2', 'Placeholder image for sms winning game', '.jpg');?>
            </div>
        </div>
    </div>
</div>
<section class="collapsibleSection">
    <h2>Description</h2>
    <div class="row description">
        <div class="col-md-9">
            <p><a href="http://www.megafanapps.com" target="_blank">megafanapps.com</a> is online store for Facebook fan page apps that bring additional value to your social media business promotion. Our apps are ready-made and can be easily customized by you, since no technical or coding skills are needed. <a href="http://www.megafanapps.com" target="_blank">megafanapps.com</a> is a very affordable app store with different apps tailored for any occasion and promotion during the year.</p>

            <p>The main purpose of Facebook fan page apps is to collect quality participant data and help you with fan-to-customer conversion process. The other aspect is increasing the value and attractiveness of your business page on the largest social media platform. Installing an app from <a href="http://www.megafanapps.com" target="_blank">megafanapps.com</a> is very easy.</p>

            <p>The centralized admin cockpit allows you to easily configure a campaign in just a few clicks. Many useful options will help you to create a quality and attractive page to your fans. Each page can be customized with specific HTML possible for live preview during the configuration process. You can also preview the progress of your configuration at any time. The other great opportunity is a fully customizable contact form for quality leads. Here you determine, select and make your first step to the final sales process.</p>

            <p>Each app has ready-made design options applicable for many occasions during the year. On the other hand, you are allowed to upload a custom CSS at any time and mark your campaign with strong brand awareness and consistency. Live campaigns are accessible from every device – desktop, tablet or smartphone. Quality statistics and campaign reports are essential part of your marketing activities and are integrated in every app with a possibility of data export in csv or xls format at any time during or after the campaign. Pre-integrated coupon app allows you to give incentives to every participant after submitting a contact form which automatically increases sales at your PoS or e-commerce service.</p>

            <p>We offer you variety of apps which fit to any industry or agency: <a href="http://www.megafanapps.com/en/applications#Sweepstakes+Apps" target="_blank">Sweepstake Apps</a>, <a href="http://www.megafanapps.com/en/applications#Social+Media+Apps" target="_blank">Social Media Apps</a>, <a href="http://www.megafanapps.com/en/applications#Fan+page+Management+Apps" target="_blank">Fan page management Apps</a>, <a href="http://www.megafanapps.com/en/applications#Landing+Page+Apps" target="_blank">Landing page Apps</a> or <a href="http://www.megafanapps.com/en/applications#Custom+Apps" target="_blank">Custom App development</a>. 

            <p><a href="http://www.megafanapps.com/en/default/agency" target="_blank">Sign up</a> for Agency partner programme today and get extra privileges to our apps!            
        </div>
        <div class="col-md-3">
            <div class="row">
                <div class="col-md-12 col-xs-6 innerPageImage">
                    <?php echo $this->renderPicture('picture1', '/images/inner/picture1', 'Placeholder image for sms winning game', '.jpg');?>
                </div>
                <div class="col-md-12 col-xs-6 innerPageImage">
                    <?php echo $this->renderPicture('picture1', '/images/inner/picture1', 'Placeholder image for sms winning game', '.jpg');?>
                </div>
            </div>
        </div>  
    </div>
</section>
<section class="collapsibleSection">
    <h2>Preparations</h2>
    <div class="row">
        <div class="col-md-12">  
            <h3>Preparations from your side</h3>
            <ol>
                <li>Idea for a campaign (e.g. Instant winning game – immediate prizes for participants)</li>
                <li>Preparations: fan page posting, image design, planning of prizes</li>
                <li>Configuration of e.g. Winning game App – admin cockpit</li>
                <li>Announcing the campaign: posting on Facebook and paying Facebook Ads</li>
                <li>Regular communication with fans during the campaign</li>
                <li>Campaign success monitoring</li>
                <li>Distribution of prizes and campaign evaluation</li>
                <li>Announcing a new campaign!</li>
            </ol>
            <h3>How your customers participate in a winning game campaign</h3>            
            <ol>
                <li>They see your Ad on their Facebook newsfeed / or regular posts if already fans</li>
                <li>Go to page tab and enter the campaign</li>
                <li>Participate from everywhere (on-the-go) using their mobile devices</li>
                <li>Fill-in the registration form, leave their details and win instant prizes</li>
                <li>Share the campaign on their social media profiles and spread the word around</li>
            </ol>
        </div>
    </div>
</section>
<section class="collapsibleSection">
    <h2>Prices</h2>
    <div class="row">
        <div class="col-md-12">  
            <p><a href="<?php echo $this->contactUrl();?>">Contact us</a> or Download <a href="#">Order Form</a> in PDF.</p>
        </div>
    </div>
</section>