<div class="introTxt">
    <h1>Facebook Moderation</h1>
    <h2>Step-by-step guide towards successful campaign management</h2>
</div>
<p>Full-time support which navigates your Facebook campaigns to final results.</p>
<div class="row innerRow">
    <div class="col-md-9 listWrapper">
        <div class="row listGroup">
            <div class="collapseContent col-md-6">
                <h3>You want</h3>
                <ul class="collapseContentBox">
                    <li>Campaigns that create viral buzz!</li>
                    <li>Detailed campaign performance.</li>
                    <li>Quality campaign configuration. </li>
                    <li>Content moderation during the campaign runtime. </li>
                    <li>Outsource moderation due to lack of resources.</li>
                </ul>
            </div>
            <div class="collapseContent col-md-6">
                <h3>We have</h3>
                <ul class="collapseContentBox">
                    <li>Experienced team working in online marketing. </li>
                    <li>Dedicated support for quality campaign configuration.</li>
                    <li>All eyes opened during your campaign’s runtime. </li>
                    <li>Professional Moderation team which will take care of your fan page.</li>
                </ul>
            </div>
        </div>
        <div class="row listGroup">
            <div class="collapseContent col-md-6">
                <h3>Features</h3>
                <ul class="collapseContentBox">
                    <li>Posts on your wall with attractive content.</li>
                    <li>Complete campaign structure: from initial idea through implementation process.</li>
                    <li>Different media (images, links, videos and text) included.</li>
                    <li>Watching the campaign success at any stage of implementation.</li>
                    <li>Live support during the campaign.</li>
                    <li>Post planning strategy included.</li>
                </ul>
            </div>
            <div class="collapseContent col-md-6">
                <h3>Purpose</h3>
                <ul class="collapseContentBox">
                    <li>Increase the attractiveness of your fan page. </li>
                    <li>To secure the campaign’s success.</li>
                    <li>Accelerate the conversion fan-to-customer process. </li>
                    <li>Reduce time needed to configure and execute Facebook campaigns. </li>
                    <li>Cost-effectiveness: no need to hire additional experts.</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="col-md-3">
        <div class="row">
            <div class="col-md-12 col-xs-6 innerPageImage">
                <?php echo $this->renderPicture('picture1', '/images/inner/picture1', 'Placeholder image for sms winning game', '.jpg');?>
            </div>
            <div class="col-md-12 col-xs-6 innerPageImage">
                <?php echo $this->renderPicture('picture2', '/images/inner/picture2', 'Placeholder image for sms winning game', '.jpg');?>
            </div>
        </div>
    </div>
</div>
<section class="collapsibleSection">
    <h2>Description</h2>
    <div class="row description">
        <div class="col-md-9">
            <p>Fan page moderation in terms of social media services means that we support our clients who are either unexperienced or do not have time to monitor the implementation of campaign using their Facebook fan page or other social media network. Community managers are usually people responsible for social media content – but are they experienced enough to successfully configure, execute and monitor the whole campaign? </p>

            <p>Using our moderation service will surely help you run any campaign smoothly. The team of experienced people will implement any planned activity, moderate online campaigns (fan page contests, promotions, etc.), change settings and fix ongoing issues, all with the aim to manage your customers being engaged to your business all the time. Of course, you are actively involved into all aspects of campaign’s moderation, including regular reports and data analysis. </p>

            <p>This service makes you feel relied and comfortable when it comes to successful social media marketing. Moderation is part of the social media management system; therefore, the necessity to engage people who use the “know how” method is just one step to your business’ success which includes regular social media promo activities.</p>
        </div>
        <div class="col-md-3">
            <div class="row">
                <div class="col-md-12 col-xs-6 innerPageImage">
                    <?php echo $this->renderPicture('picture1', '/images/inner/picture1', 'Placeholder image for sms winning game', '.jpg');?>
                </div>
                <div class="col-md-12 col-xs-6 innerPageImage">
                    <?php echo $this->renderPicture('picture1', '/images/inner/picture1', 'Placeholder image for sms winning game', '.jpg');?>
                </div>
            </div>
        </div>  
    </div>
</section>
<section class="collapsibleSection">
    <h2>Preparations</h2>
    <div class="row">
        <div class="col-md-12">  
            <h3>Preparations from the side of your business</h3>
            <ol>
                <li>Decide upon attractive brand look.</li>
                <li>Create or edit your existing Facebook fan page. </li>
                <li>Request moderation support from our social media marketing team. </li>
                <li>Monitor the overall campaign execution and analyse final results. </li>
                <li>Prepare for another campaign – we help you to use the latest tips &amp; tricks.</li>
            </ol>
        </div>
    </div>
</section>
<section class="collapsibleSection">
    <h2>Prices</h2>
    <div class="row">
        <div class="col-md-12">  
            <p><a href="<?php echo $this->contactUrl();?>">Contact us</a> or Download <a href="#">Order Form</a> in PDF.</p>
        </div>
    </div>
</section>