<div class="introTxt">
    <h1>Premium Number Hosting</h1>
    <h2>Value Added Service numbers for great business outcome</h2>
</div>
<p>Safe and reliable hosting for your VAS premium-rate numbers and IVR services.</p>
<div class="row innerRow">
    <div class="col-md-9 listWrapper">
        <div class="row listGroup">
            <div class="collapseContent col-md-6">
                <h3>You want</h3>
                <ul class="collapseContentBox">
                    <li>Memorable 0800 / 090x numbers</li>
                    <li>All telecom services under one umbrella.</li>
                    <li>Reliable and safe server space.</li>
                    <li>Dedicated technical support.</li>
                </ul>
            </div>
            <div class="collapseContent col-md-6">
                <h3>We have</h3>
                <ul class="collapseContentBox">
                    <li>Wide range of VAS numbers on stock</li>
                    <li>Our own hosting servers within cloud-based services.</li>
                    <li>Space in data center provided for quality number hosting.</li>
                    <li>Telecom specialist's support 24/7.</li>
                </ul>
            </div>
        </div>
        <div class="row listGroup">
            <div class="collapseContent col-md-6">
                <h3>Features</h3>
                <ul class="collapseContentBox">
                    <li>High data security.</li>
                    <li>Internal server space provided.</li>
                    <li>Network routing hosting.</li>
                    <li>Support and maintenance provided by phone, email and messaging.</li>
                    <li>Private cloud infrastructure included.</li>
                </ul>
            </div>
            <div class="collapseContent col-md-6">
                <h3>Purpose</h3>
                <ul class="collapseContentBox">
                    <li>Worry-free hosting service for your premium numbers.</li>
                    <li>Technical support available 24/7.</li>
                    <li>Cost-effective for premium number data storage.</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="col-md-3">
        <div class="row">
            <div class="col-md-12 col-xs-6 innerPageImage">
                <?php echo $this->renderPicture('picture1', '/images/inner/picture1', 'Placeholder image for sms winning game', '.jpg');?>
            </div>
            <div class="col-md-12 col-xs-6 innerPageImage">
                <?php echo $this->renderPicture('picture2', '/images/inner/picture2', 'Placeholder image for sms winning game', '.jpg');?>
            </div>
        </div>
    </div>
</div>
<section class="collapsibleSection">
    <h2>Description</h2>
    <div class="row description">
        <div class="col-md-9">
            <p>To provide your different customer segments access to your services, we provide you premium numbers (800, 090x) that can 
            freely be combined with our IVR voice as well mobile, web or messaging (SMS) apps.
            Premium numbers are ideal for business & advertising. The most popular ways of using premium-rate numbers are phone 
            winning games, voting campaigns via phone, weather forecasts or different competitions (especially related to TV shows or 
            broadband media campaigns including audience’s active participation). For example, premium numbers in Switzerland are 090x 
            – mostly for business & marketing or for different Entertainment services.</p> 

            <p>In HORISEN we host our own IVR (Interactive Voice Response) services that offer your customers a 24/7 service without
            additional cost implications or network connection problems. This includes hosting your premium-rate numbers, too. 
            Premium number hosting has been simplified since the introduction to web services into the contact center. This means that 
            your IVR service can be hosted remotely from one center.</p>

            <p>Managing hosting can be a really additional obligation for your company and a very exhausting additional activity. We have a 
            team of experienced technical support and system administrators that manage and update our internal server all the time. With 
            HORISEN premium number hosting you feel like at home.</p>
        </div>
        <div class="col-md-3">
            <div class="row">
                <div class="col-md-12 col-xs-6 innerPageImage">
                    <?php echo $this->renderPicture('picture1', '/images/inner/picture1', 'Placeholder image for sms winning game', '.jpg');?>
                </div>
                <div class="col-md-12 col-xs-6 innerPageImage">
                    <?php echo $this->renderPicture('picture1', '/images/inner/picture1', 'Placeholder image for sms winning game', '.jpg');?>
                </div>
            </div>
        </div>  
    </div>
</section>
<section class="collapsibleSection">
    <h2>Preparations</h2>
    <div class="row">
        <div class="col-md-12">  
            <p>Premium number hosting is done within HORISEN internal server or using private cloud infrastructure offered to its clients.
            Premium number services are part of IVR (Interactive Voice Response) services which are already included into regular technical 
            support / maintenance.</p>
        </div>
    </div>
</section>
<section class="collapsibleSection">
    <h2>Prices</h2>
    <div class="row">
        <div class="col-md-12">  
            <p><a href="<?php echo $this->contactUrl();?>">Contact us</a> or Download <a href="#">Order Form</a> in PDF.</p>
        </div>
    </div>
</section>