<div class="introTxt">
    <h1>SMS & Pay</h1>
    <h2>Fastest way to pay & shop</h2>
</div>
<p>Ideal for online sales and safe payments with a single SMS.</p>
<div class="row innerRow">
    <div class="col-md-9 listWrapper">
        <div class="row listGroup">
            <div class="collapseContent col-md-6">
                <h3>You want</h3>
                <ul class="collapseContentBox">
                    <li>Fast and easy payment system.</li>
                    <li>To increase online purchases.</li>
                    <li>Quality marketing activities.</li>
                    <li>Alternative to credit card payment.</li>
                </ul>
            </div>
            <div class="collapseContent col-md-6">
                <h3>We have</h3>
                <ul class="collapseContentBox">
                    <li>SMS & Pay application that ensures safe purchases.</li>
                    <li>The application is ideal for online purchases because it requires a user to send just one SMS.</li>
                    <li>Excellent customer contacts database for continuous marketing activities.</li>
                </ul>
            </div>
        </div>
        <div class="row listGroup">
            <div class="collapseContent col-md-6">
                <h3>Features</h3>
                <ul class="collapseContentBox">
                    <li>Fully automated buying process.</li>
                    <li>Fast & safe purchases enabled.</li>
                    <li>Custom transaction code generator.</li>
                    <li>Real-time statistics provided.</li>
                    <li>Technical support included.</li>
                    <li>Premium SMS included.</li>
                    <li>Quality contact database.</li>
                </ul>
            </div>
            <div class="collapseContent col-md-6">
                <h3>Purpose</h3>
                <ul class="collapseContentBox">
                    <li>Increase online sales.</li>
                    <li>Promote fast and safe purchase.</li>
                    <li>Improve SMS marketing.</li>
                    <li>Get quality contacts.</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="col-md-3">
        <div class="row">
            <div class="col-md-12 col-xs-6 innerPageImage">
                <?php echo $this->renderPicture('picture1', '/images/inner/picture1', 'Placeholder image for sms winning game', '.jpg');?>
            </div>
            <div class="col-md-12 col-xs-6 innerPageImage">
                <?php echo $this->renderPicture('picture2', '/images/inner/picture2', 'Placeholder image for sms winning game', '.jpg');?>
            </div>
        </div>
    </div>
</div>
<section class="collapsibleSection">
    <h2>Description</h2>
    <div class="row description">
        <div class="col-md-9">
            <p>SMS & Pay is easy and safe payment method that opens new business opportunities and allows you to make your business more
            developed and efficient with fully automated buying process. Payment via SMS is very easy; it’s extremely comfortable but also 
            very safe for the seller. SMS & Pay is, therefore, ideal for online sales. This application is a great alternative to existing payment 
            systems, but faster and easier to use. User doesn’t have to verify his/her credit card number or pass any security steps in order 
            to pay a product or a service.</p> 

            <p>The process is very simple: seller communicates with a buyer for every product or service purchase using unique transaction
            code. The buyer then sends an SMS with the transaction code (e.g. “PAY”) to our short code number. Immediately after that, 
            a fee-based premium SMS confirmation code is sent to the buyer via SMS & Pay service. This code has to be confirmed on the 
            sellers website. The reimbursement process is also very simple: the chargeable amount is taken from the buyer’s monthly phone 
            bill or debit phone balance. 
            At the same time our SMS & Pay application notifies the seller that the payment process has been successfully completed using 
            the right transaction code. After the buying procedure finishes, the seller delivers the product/service to the buyer.</p>

            <p>When the transaction fee has been deducted, the seller gets his share. Access to real-time statistics shows how much revenue 
            you generated at any time. In addition, as a seller you don’t only want to sell a product or service and then close the circle; you 
            also want valuable contact details from your customers – mobile phone numbers. This allows you to run effective SMS direct 
            marketing campaigns and inform your customers about news, new activities, sales or other important business updates.</p>

            <p>For accessing SMS & Pay application, please contact us now!</p>
        </div>
        <div class="col-md-3">
            <div class="row">
                <div class="col-md-12 col-xs-6 innerPageImage">
                    <?php echo $this->renderPicture('picture1', '/images/inner/picture1', 'Placeholder image for sms winning game', '.jpg');?>
                </div>
                <div class="col-md-12 col-xs-6 innerPageImage">
                    <?php echo $this->renderPicture('picture1', '/images/inner/picture1', 'Placeholder image for sms winning game', '.jpg');?>
                </div>
            </div>
        </div>  
    </div>
</section>
<section class="collapsibleSection">
    <h2>Preparations</h2>
    <div class="row">
        <div class="col-md-12">  
            <h3>Payment procedure from the user’s perspective:</h3>
            <ol>
                <li>Go to online store and select a particular product / service.</li>
                <li>Click on the pay button.</li>
                <li>SMS & Pay service instruction is displayed.</li>
                <li>Send the displayed transaction code by SMS.</li>
                <li>Receive a confirmation SMS with a payment code.</li>
                <li>Confirm the payment code online.</li>
                <li>A product will be delivered soon / a service is paid.</li>
            </ol>
        </div>
    </div>
</section>
<section class="collapsibleSection">
    <h2>Prices</h2>
    <div class="row">
        <div class="col-md-12">  
            <p><a href="<?php echo $this->contactUrl();?>">Contact us</a> or Download <a href="#">Order Form</a> in PDF.</p>
        </div>
    </div>
</section>