<div class="introTxt">
    <h1>Premium SMS</h1>
    <h2>Monetize your content and customer engagement</h2>
</div>
<p>For premium service value that generates revenue worldwide.</p>
<div class="row innerRow">
    <div class="col-md-9 listWrapper">
        <div class="row listGroup">
            <div class="collapseContent col-md-6">
                <h3>You want</h3>
                <ul class="collapseContentBox">
                    <li>More revenue and fast customer attraction.</li>
                    <li>Flexible payment system.</li>
                    <li>Interaction with your customers.</li>
                    <li>Long-term relationship with customers.</li>
                </ul>
            </div>
            <div class="collapseContent col-md-6">
                <h3>We have</h3>
                <ul class="collapseContentBox">
                    <li>Premium SMS service that monetizes content and engages customers.</li>
                    <li>Attractive pay-out rates.</li>
                    <li>Reply messages sent to customers (with personal note!).</li>
                    <li>Subscription-based content; users apply for this service which is chargeable, but you send them regular updates.</li>
                </ul>
            </div>
        </div>
        <div class="row listGroup">
            <div class="collapseContent col-md-6">
                <h3>Features</h3>
                <ul class="collapseContentBox">
                    <li>Application to rely on.</li>
                    <li>Unlimited number of prizes allowed.</li>
                    <li>Different answer for each prize enabled.</li>
                    <li>Instant SMS answer to participants.</li>
                    <li>Winning game frequency is completely adjustable.</li>
                    <li>Website address generator.</li>
                    <li>Customer data export (Excel, csv).</li>
                    <li>Time-limited campaigns enabled.</li>
                    <li>Flexible cost per SMS.</li>
                    <li>Custom voucher codes easily imported.</li>
                    <li>Online admin panel for campaign settings.</li>
                    <li>Real-time statistics.</li>
                    <li>And many more…</li>
                </ul>
            </div>
            <div class="collapseContent col-md-6">
                <h3>Purpose</h3>
                <ul class="collapseContentBox">
                    <li>Attractive advertising campaign.</li>
                    <li>Great entertainment for retail industry.</li>
                    <li>Increase brand awareness.</li>
                    <li>Winning game package for different purposes.</li>
                    <li>Quality customer contact database.</li>
                    <li>Achieve customer retention.</li>
                    <li>Great sales promotion tool.</li>
                    <li>Effectively measures advertising channels.</li>
                    <li>Implementation of different promo solutions.</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="col-md-3">
        <div class="row">
            <div class="col-md-12 col-xs-6 innerPageImage">
                <?php echo $this->renderPicture('picture1', '/images/inner/picture1', 'Placeholder image for sms winning game', '.jpg');?>
            </div>
            <div class="col-md-12 col-xs-6 innerPageImage">
                <?php echo $this->renderPicture('picture2', '/images/inner/picture2', 'Placeholder image for sms winning game', '.jpg');?>
            </div>
        </div>
    </div>
</div>
<section class="collapsibleSection">
    <h2>Description</h2>
    <div class="row description">
        <div class="col-md-9">
            <p>Premium services are those that add premium value to basic services (price is different from standard price of SMS – so the
            mobile phone user is charged an additional amount for using this service). Premium SMS service uses short codes for sending a 
            message, for example, when buying a product or service or participate in SMS voting. 
            HORISEN hosts Premium SMS service on its own servers and platforms, included cloud-based services for mobile marketing 
            applications.</p> 

            <p>Premium SMS service is a great tool for companies to generate revenue by simple short messaging system which charges mobile
            phone users for a certain service (payment, contest, voting, donations, etc.).
            This service is ideal for: one-off payments, subscriptions or text-and-win promotions.</p>

            <h3>Premium SMS are used when mobile phone users want to:</h3>
            <ul>
                <li>Participate in a contest.</li>
                <li>Participate in winning games and auctions.</li>
                <li>Pay for certain website access.</li>
                <li>Buy any online content.</li>
                <li>Vote for their favorite candidate in a show or competition (TV/radio programs mostly).</li>
                <li>Subscribe to receiving certain content from the provider.</li>
                <li>Their message is being reproduced after the service collects all incoming messages.</li>
                <li>And much more!</li>
            </ul>
        </div>
        <div class="col-md-3">
            <div class="row">
                <div class="col-md-12 col-xs-6 innerPageImage">
                    <?php echo $this->renderPicture('picture1', '/images/inner/picture1', 'Placeholder image for sms winning game', '.jpg');?>
                </div>
                <div class="col-md-12 col-xs-6 innerPageImage">
                    <?php echo $this->renderPicture('picture1', '/images/inner/picture1', 'Placeholder image for sms winning game', '.jpg');?>
                </div>
            </div>
        </div>  
    </div>
</section>
<section class="collapsibleSection">
    <h2>Preparations</h2>
    <div class="row">
        <div class="col-md-12">  
            <p>Maybe the most popular way for using Premium SMS service are &quot;Text-to-win&quot; competitions. In this way, the audience gets into
            serious interaction with your business. For example, this type of service is used among broadcast media (television and radio) in 
            order to interact with the brand during popular shows. Participation procedure is very simple:</p>
            <ol>
                <li>Audience can participate by sending SMS to a particular number (usually it is a short code).</li>
                <li>Participation often includes different countries or regions, so messages can be sent from everywhere.</li>
                <li>There is a pre-determined text which should be entered in a valid message (a keyword).</li>
                <li>A reply message is sent and additionally charged to the user.</li>
                <li>Voting for a favorite candidate is not the end – you get a new number in your CRM database.</li>
                <li>Either you organize text-to-win competition or sponsor it, these numbers are a great starting point for direct marketing activities.</li>
                <li>Continue sending Bulk SMS, email newsletters, social network promo activities, etc.</li>
            </ol>
        </div>
    </div>
</section>
<section class="collapsibleSection">
    <h2>Prices</h2>
    <div class="row">
        <div class="col-md-12">  
            <p><a href="<?php echo $this->contactUrl();?>">Contact us</a> or Download <a href="#">Order Form</a> in PDF.</p>
        </div>
    </div>
</section>