<h1>Security and Privacy</h1>

<h2>Introduction</h2>
<p>HORISEN, Inc. ("HORISEN" or "we") operates the HORISEN services to make professional marketing easy, efficicient and effective. 
    We provide you with opportunities to engage with your customers, advertise your services or interact with your fan base in many ways.<br />
    We provide this Privacy Policy to inform you of our policies regarding the collection, use, disclosure and protection of information. This 
    Privacy Policy applies to all of the HORISEN social media websites, mobile, messaging and voice features, applications, and other interactive 
    features or services that link to it ("HORISEN Services"), including the HORISEN website (http://www.HORISEN.com) (the "HORISEN Site") and the 
    HORISEN applications and pages on Facebook (the "HORISEN App"). And the HORISEN Facebook App Market (the HORISEN App Market”). <br />
    Your use of the HORISEN Services is subject to our Terms of Use ( The “TOS” under http://HORISEN.com/about/terms). If you access the HORISEN 
    Services through Facebook, you may be required to read and accept the Facebook terms of service and privacy policy.<br />
    The HORISEN Services are not intended for consumers but to companies understood as legal entities.</p>

<h2>2. HORISEN Community Basics.</h2>
<p>Through the HORISEN services, we provide you with the tools to instantly start professional marketing based on your existing Facebook profile 
    and comprised of your friends and their friends and that you can expand as you connect with other members and friends. Importantly, however, 
    HORISEN does not request, receive or access your non- professional Facebook information such as your photos (other than your profile photo), 
    videos, wall posts, status updates, location check-ins, personal interests (e.g., favourite bands and movies) and use of other Facebook apps 
    and services.<br />
    By joining HORISEN, you are voluntarily deciding to become part of HORISEN's global customer and partner community (the “HORISEN buz community”) 
    and to disclose or share certain information with HORISEN. Below we summarize what it means to be part of the HORISEN community.</p>

<h2>3. Information We Receive</h2>
<h3>B. Information We Collect From You Directly</h3>
<p>When you use HORISEN, whether through the HORISEN Site or through the HORISEN App or otherwise, we may collect and store information from you 
    directly as described below:</p>
<h3>Registration and Payment Information</h3>
<p>In addition to the information we receive from Facebook, when you register with us or choose to participate in one of our features or otherwise 
    interact with us, you may be required or asked to provide certain information, which may include personal information (which is information that 
    can be used to identify or contact a specific individual, such as your name and email address), account information (such as a password or other 
    information that helps us confirm that it is you accessing your account) and demographic information (such as your country or zip code). We will 
    also collect payment information (typically, credit card account information) if you choose to purchase products or services through the HORISEN 
    Services.</p>
<h3>Customer Support Correspondence</h3>
<p>When you ask for assistance from our Customer Support team, we may collect and store contact information you provide (generally your name and e-mail 
    address), as well as information about your usage of HORISEN so that we can appropriately respond to inquiries. We will also store the correspondence 
    and any related information.</p>
<h3>C. Information we collect when you interact with HORISEN.</h3>
<p>When you access the HORISEN Services, we and our analytics providers and other third party service providers may collect "Usage Information," which is 
    (i) certain technical information about your computer system and (ii) usage statistics about your interactions with the HORISEN Services, such as the 
    pages and content you view and actions you take on the HORISEN Websites, like updating your profile or buying additional services. The information 
    collected also includes your IP address or other unique identifier for the computer or other device you use to access the HORISEN services. Some mobile 
    service providers may also provide us or our third-party service providers with information regarding the physical location of the mobile device used to 
    access the HORISEN Services. Usage Information is collected through the use of server log files and tracking technologies, including cookies, web beacons 
    and embedded scripts. In some cases, we will associate this information with your user ID number for our internal use.<br />
    A cookie is a small text file that is stored on a user's computer for record keeping purposes. Cookies may be used for many purposes, such as remembering you 
    and your preferences and tracking your visits to our web pages.<br />
    A web beacon is a small (often invisible) graphic image or other web programming code embedded in a web page or email. Web beacons or similar technologies may 
    be used for a number of purposes, including, without limitation, to count visitors to the HORISEN Services, to monitor how users navigate the HORISEN Services 
    and to count how many e-mails that were sent were actually opened.<br />
    An embedded script is programming code that is designed to collect information about your interactions with the Sites, such as the links you click on. The code 
    is temporarily downloaded onto your computer or other device from our server or a third party service provider and is deactivated or deleted when you disconnect 
    from the HORISEN services.</p>
<h3>D. Information we receive from third parties and social media applications.</h3>
<p>We may receive information from third parties. For example, if you are on another web site and you agree to receive information from HORISEN, that web site 
    will forward your contact and other information to us so that we may contact you as requested. You may also choose to participate in a HORISEN or third party 
    application or features (such as a widget that allows you to import your HORISEN profile information to a third party site) through which you allow us to 
    collect or share information about you. In addition, we may receive information about you if other users of a third party web site give us access to their 
    profiles and you are one of their "connections" or information about you is otherwise accessible through your "connections" web page, profile page, or similar page
    on a social networking or other third party web site or interactive service.<br />
    We also may supplement the information we collect with outside records from third parties in order to provide you with information, services or goods you have 
    requested. We may combine the information we receive from those other sources with information we collect through the Site. In those cases, we will apply this 
    Privacy Policy to the combined information.</p>

<h2>4. How We Use Your Information</h2>
<p>HORISEN uses information it collects and receives about you to provide the HORISEN services, to contact you, and as disclosed at the time you provide your information. 
    Specifically, here are some ways that we use the information we collect and receive, including personal information and Usage Information:</p>
<h3>When You Agree to Receive Information From Third Parties or Otherwise Request That We Share Your Information.</h3>
<p>You may be presented with an opportunity to receive information and/or marketing offers from one or more third parties. If you agree at that time to have your 
    information shared, your information will be disclosed to that third party (or parties) and will be subject to the privacy policy and practices of that third 
    party. We are not responsible for the privacy policies and practices of third parties, and, if you later decide that you no longer want to receive communications 
    from a third party, you will need to contact that third party directly. You also may request, sometimes through your use of an interactive feature, a widget or 
    third party application, that we share information about you with a third party and we will typically do so under those circumstances.</p>
<h3>User Registration.</h3>
<p>The information you provide to us is used to register your account, establish your profile, allow you to use the HORISEN Services and allow others to discover 
    and communicate with you. Your Profile is not available at all to any other user of HORISEN services.</p>
<h3>Managing our Service.</h3>
<p>We use the information we collect to provide our services and features to you, to measure and improve those services and features, and to provide you with customer 
    support. We may also use information we collect to serve you content that will be more meaningful to you. For example, if we may use your service history or country 
    of operations to recommend available services you might want to know.</p>
<h3>Communications from HORISEN.</h3>
<p>We may contact you through email, messages in Facebook and HORISEN, wall posts and notifications on Facebook with service-related announcements, to respond to customer 
    support inquiries, keep you informed of your services activity (e.g., update to services history or endorsements) and present you with commercial opportunities. We may 
    also send you promotional email messages on our behalf or on behalf of our partners. You can opt out of receiving promotional messages by clicking "unsubscribe" in the 
    message or changing your email settings in the Privacy Center (http://HORISEN.com/about/privacy).</p>
<h3>Polls and Surveys.</h3>
<p>HORISEN conducts polls and surveys that users can take. Participation in these polls and surveys is completely voluntary and you therefore have a choice whether or not 
    to disclose this information. Certain customers may use the results from these activities in their marketing technology efforts. Additionally, third parties may target 
    advertising to you based on answers and information from these activities.</p>

<h2>5. How We Share Information</h2>
<p>We do not sell, rent, or otherwise provide your personal identifiable information to any third party advertisers for direct marketing purposes without your consent. 
    We share your information (which may include personal information) with third parties (not HORISEN) with your consent, as disclosed in this privacy policy or at the 
    time you provide us with information, and in the following circumstances:</p>
<h3>Third Party Service Providers.</h3>
<p>We may provide information to service providers that help us bring you the services we offer. For example, we may use third parties to help host our website, send out 
    email updates about HORISEN, remove repetitive information from our user lists, process payments, or provide search results or links (including sponsored links). If 
    you purchase any products or services from HORISEN, our billing partners will receive billing and financial information (e.g., credit card numbers or PayPal details) 
    necessary to process your charges, including your postal and e-mail addresses, depending on your payment method. HORISEN will store this information and it will be 
    provided to third parties so that they may process your payment.</p>
<h3>Joint Services.</h3>
<p>We may provide services jointly with other companies. If you use these services, we may share your information to facilitate that service. However, we will identify 
    the partner before you use that service.</p>
<h3>Legal Requests and Safety.</h3>
<p>We may transfer and disclose information, including personal Information and Usage Information and your device identifier (including IP address), to third parties to 
    comply with a legal obligation; when we believe in good faith that the law requires it; at the request of governmental authorities conducting an investigation; to 
    verify or enforce our Terms of Use or other applicable policies; to respond to an emergency; or otherwise to protect the rights, property, safety, or security of 
    third parties, users of the HORISEN Services or the public. We may also use device identifiers to identify users, and may do so in cooperation with copyright owners, 
    Internet service providers, wireless service providers or law enforcement agencies, in our discretion. Such disclosures may be carried out without notice to you.</p>
<h3>Transfer in the Event of Sale or Change of Control.</h3>
<p>HORISEN reserves the right to disclose and transfer user information, including personal information, in connection with a corporate merger, consolidation, 
    restructuring, the sale of certain stock and/or assets, or other corporate change including, without limitation, during the course of any due diligence process.</p>
<h3>Sweepstakes, Contests and Promotions.</h3>
<p>We may offer sweepstakes, contests, and other promotions (each, a "Promotion") that may require registration. If you choose to enter a Promotion, your personal 
    information may be disclosed to third parties in connection with the administration of such Promotion, such as in connection with winner selection, prize fulfilment, 
    and as required by law, such as on a winners list. By entering a Promotion, you are agreeing to the official rules that govern that Promotion, which may contain 
    specific requirements of you, including, except where prohibited by law, allowing the sponsor and/or other parties to use your name, voice and/or likeness in 
    advertising or marketing materials.</p>
<h3>Non-Personal Information.</h3>
<p>We may share non-personal information, such as aggregated user statistics with third parties for a variety of purposes. But we only do so in such a way that no 
    individual user is identified or linked to any specific action or information.</p>

<h2>6. Third Party Analytics Providers And Ad Servers.</h2>
<p>Although the HORISEN Site currently does not display ads from third parties, HORISEN works with network advertisers, ad agencies, third party traffic measurement 
    services and other vendors to provide us with information regarding traffic on the HORISEN Sites and through the HORISEN Services, to serve our advertisements on 
    other web sites, within third party applications, and across the Internet, and to provide us with information regarding the use of the HORISEN Services and the 
    effectiveness of our advertisements. For example in connection with providing analytics and advertisement services, our service providers may collect certain 
    information about your visits to this or other web sites. We do not share personal information with these service providers, but they may set and access their 
    own tracking technologies on your computer or device (including cookies and web beacons) and may otherwise collect or have access to information about you (such 
    as your general interest in career networking and Usage Information). Cookies and web beacons, including those set by third party network advertisers, may be used 
    to, among other things, target advertisements, prevent you from seeing the same advertisements too many times and to conduct research regarding the usefulness of 
    certain advertisements to you. We may share Usage Information about visitors with third party advertising companies, analytics providers and other vendors for 
    similar purposes. While we may use a variety of service providers to perform advertising and analytics services, you may wish to visit 
    http:// www.networkadvertising.org/managing/opt_out.asp, which provides information regarding this practice by Network Advertising Initiative ("NAI") members, 
    including the "opt-out" procedures of NAI members.</p>

<h2>7. How to Access and Update Your Information.</h2>
<h3>Information We Receive From Facebook.</h3>
<p>To manage the information HORISEN receives about you from Facebook, you will need to follow the instructions in your "Account" and "Privacy Settings" on Facebook 
    (or similar features as determined by Facebook) for updating your information and changing your privacy settings.<br />
    Once HORISEN receives your information from Facebook, that information is stored and used by HORISEN in accordance with this Privacy Policy.</p>
<h3>Accessing and Controlling Your Information.</h3>
<p>You can review and update your Full Profile (some of which will be included in your Public Profile), with your latest services history and other information, at 
    any time by logging into your account on HORISEN Sites and following the instructions.</p>
<h3>Closing Your Account.</h3>
<p>We would hate to see you go, but if you no longer want HORISEN to make active use of your information, you may send an e-mail to privacy@horisen.com.<br />
Place "Delete My Account" in the subject line and include your full contact details incl. company name in the body of the e-mail. We will respond to your request as 
soon as practical and within thirty (30) days. Please note that some information may not be able to be deleted from all databases and backup records and that certain 
records, for example those pertaining to payments or customer service matters, will be retained for legal and accounting purposes. Also, if you have posted content 
on or through the HORISEN Services, we may not be able to delete it.</p>

<h2>8. Security of Your Information.</h2>
<p>HORISEN implements reasonable security measures to protect the security of your information both online and offline, and we are committed to the protection of customer 
    information.<br />
    When you sign into your account or enter payment information (such as a credit card number when purchasing virtual currency), we encrypt the transmission of that information 
    using secure socket layer technology ("SSL").<br />
    While we take reasonable precautions against possible security breaches of our websites and our customer databases and records, no website or Internet transmission is 
    completely secure, and we cannot guarantee that unauthorized access, hacking, data loss, or other breaches will never occur. We urge you to take steps to keep your personal 
    information safe (including your account password), and to log out of your account after use. If your Facebook account is hacked, this may lead to unauthorized use of your 
    HORISEN application, so be careful to keep your account information secure.</p>

<h2>9. HORISEN Widgets And HORISEN Content Found Outside The HORISEN Services.</h2>
<p>When you are using any of the HORISEN Sites, you may be directed to other websites or online services that are operated and controlled by third parties that are beyond 
    our control. In addition, HORISEN content and widgets may be included on web pages and web sites that are not associated with us and over which we have no control. 
    These third parties may independently collect data. HORISEN is not responsible for the privacy practices of any third party</p>

<h2>10. Changes/Consent To Transfer/Contact Us</h2>
<h3>Changes.</h3>
<p>HORISEN may update this policy from time to time and any changes will be effective upon posting. We will notify you about significant changes in the way we treat 
    personal information by sending a notice to the primary email address specified in your HORISEN account or by placing a prominent notice on our site. However, we 
    will use your personal information in a manner consistent with the Privacy Policy in effect at the time you submitted the information, unless you consent to the 
    new or revised policy.</p>
<h3>Consent to Transfer.</h3>
<p>The HORISEN Services are operated in Switzerland. If you are located outside of Switzerland, please be aware that information we collect will be transferred to and 
    processed in Switzerland. By using the HORISEN Services, or providing us with any information, you fully understand and unambiguously consent to this transfer, 
    processing and storage of your information in Switzerland, a jurisdiction in which the privacy laws may not be as comprehensive as those in the country where you 
    reside and/or are a citizen.</p>
<h3>How to Contact Us.</h3>
<p>If you have any questions, comments or concerns regarding our Privacy Policy and/or practices, please send an e-mail to privacy@horisen.com. Any other questions 
    or inquiries should be directed to HORISEN Customer Care at contact@horisen.com.</p>