<div class="introTxt">
    <h1>SMS Voting Application</h1>
    <h2>Ideal for votes, elections and surveys</h2>
</div>
<p>HORISEN is the SMS Voting application specialist of the country.</p>
<div class="row innerRow">
    <div class="col-md-9 listWrapper">
        <div class="row listGroup">
            <div class="collapseContent col-md-6">
                <h3>You want</h3>
                <ul class="collapseContentBox">
                    <li>To run a voting campaign via SMS.</li>
                    <li>Set-up a voting campaign quickly and easily.</li>
                    <li>Have a real-time overview of the pool results.</li>
                    <li>Simple voting application management process.</li>
                </ul>
            </div>
            <div class="collapseContent col-md-6">
                <h3>We have</h3>
                <ul class="collapseContentBox">
                    <li>A powerful SMS Voting application.</li>
                    <li>SMS voting application installed in a minute.</li>
                    <li>Real-time statistics available online.</li>
                    <li>Web access to the application which is fully intuitive to use.</li>
                </ul>
            </div>
        </div>
        <div class="row listGroup">
            <div class="collapseContent col-md-6">
                <h3>Features</h3>
                <ul class="collapseContentBox">
                    <li>SMS voting application applies to any type of voting campaigns.</li>
                    <li>Real-time voting results available.</li>
                    <li>Automatic votes' evaluation.</li>
                    <li>Configurable immediate SMS response to voters.</li>
                    <li>No registration needed.</li>
                    <li>Possibility of combination with Premium SMS for paid votes.</li>
                    <li>Votes export in Excel file at any time.</li>
                    <li>Full subscriber management and data export.</li>
                    <li>Online cockpit for settings and results evaluation provided.</li>
                </ul>
            </div>
            <div class="collapseContent col-md-6">
                <h3>Purpose</h3>
                <ul class="collapseContentBox">
                    <li>Applicable for any type of voting (e.g. voting for Miss of...).</li>
                    <li>To attract voters for radio and TV shows, concerts, sports events, fairs, etc.</li>
                    <li>Political Barometers.</li>
                    <li>Product reviews.</li>
                    <li>Print media surveys.</li>
                    <li>Voting for Parliament Elections.</li>
                    <li>Television voting.</li>
                    <li>Great marketing tool to generate customer data.</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="col-md-3">
        <div class="row">
            <div class="col-md-12 col-xs-6 innerPageImage">
                <?php echo $this->renderPicture('picture1', '/images/inner/picture1', 'Placeholder image for sms winning game', '.jpg');?>
            </div>
            <div class="col-md-12 col-xs-6 innerPageImage">
                <?php echo $this->renderPicture('picture2', '/images/inner/picture2', 'Placeholder image for sms winning game', '.jpg');?>
            </div>
        </div>
    </div>
</div>
<section class="collapsibleSection">
    <h2>Description</h2>
    <div class="row description">
        <div class="col-md-9">
            <p>SMS Voting application allows you to quickly and easily collect large number of votes via SMS especially suitable for elections,
            surveys or polls; these votes are easily counted thanks to an automated online application system. The advantage of SMS voting 
            is that participants in voting campaigns always carry their mobile phones with them, so they can spontaneously vote from 
            anywhere, regardless of place or time.</p> 

            <p>Participation in SMS Voting is very simple: participants submit their votes by sending SMS with specific keyword to the short
            code number 919. All votes under given keyword are automatically written in application's database. This is how you can see 
            real-time results without any delays and successfully monitor the voting progress, especially if it is election campaign you want 
            to track and evaluate. The SMS voting system counts all changes within different keywords and automatically changes rankings.</p>

            <p>SMS Voting application grants access to its administration where you have a complete overview of all/current surveys and sent 
            SMS containing different keywords. Incoming text messages are automatically filtered and sorted within the application system
            according to active campaigns and used keywords. Current voting result is immediately visible on the screen in the form of bar 
            charts. Using online cockpit you always have full control over the voting procedure. You can also download customer data as 
            Excel sheet. Detailed and real-time statistics give you valuable information about the current status and progress of your voting 
            campaign.</p>

            <p>SMS Voting application allows you to perform quick and easy SMS voting. Your management efforts are very low, because
            the whole process is fully automated. What is also important, your customers don’t need to register in order to vote. Their 
            vote counts by simply send a SMS. The application processes all steps independently, starting from participants log-in, replies' 
            control, sorting and final evaluation. This evaluation can be combined with other applications for more accurate data output. 
            The results of your voting campaign can successfully affect other marketing activities (e.g. new promo campaign idea).</p> 

            <p>In combination with Premium SMS, a voting campaign can be additionally charged to participants. This allows you to generate
            more revenue during the voting campaign. </p>
        </div>
        <div class="col-md-3">
            <div class="row">
                <div class="col-md-12 col-xs-6 innerPageImage">
                    <?php echo $this->renderPicture('picture1', '/images/inner/picture1', 'Placeholder image for sms winning game', '.jpg');?>
                </div>
                <div class="col-md-12 col-xs-6 innerPageImage">
                    <?php echo $this->renderPicture('picture1', '/images/inner/picture1', 'Placeholder image for sms winning game', '.jpg');?>
                </div>
            </div>
        </div>  
    </div>
</section>
<section class="collapsibleSection">
    <h2>Preparations</h2>
    <div class="row">
        <div class="col-md-12">  
            <h3>Preparations from your side</h3>
            <ol>
                <li>Define your voting campaign first.</li>
                <li>Select all keywords that will be used for your campaign.</li>
                <li>Plan and make your advertising material.</li>
                <li>Define additional communication channels (e.g. web, offline and online media presentation).</li>
                <li>Determine activities that will happen after the voting.</li>
                <li>Set duration (start / end) of your voting campaign within the system.</li>
                <li>Let's start!</li>
            </ol>
            <h3>How your customers participate in SMS Voting campaign</h3>
            <ol>
                <li>Participants send SMS with predefined keywords.</li>
                <li>The system filters and evaluates responses.</li>
                <li>The application prepare and sort the data.</li>
                <li>The system sends a thank you message right after participation with a web link for campaign.</li>
                <li>Participant clicks on a link.</li>
                <li>This is the part where your future marketing activities start.</li>
            </ol>
        </div>
    </div>
</section>
<section class="collapsibleSection">
    <h2>Prices</h2>
    <div class="row">
        <div class="col-md-12">  
            <p><a href="<?php echo $this->contactUrl();?>">Contact us</a> or Download <a href="#">Order Form</a> in PDF.</p>
        </div>
    </div>
</section>