<div class="introTxt">
    <h1>SMS Newsletter Application</h1>
    <h2>Send SMS easily to thousands of customers</h2>
</div>
<p>HORISEN is the professional service for sending SMS to your customers.</p>
<div class="row innerRow">
    <div class="col-md-9 listWrapper">
        <div class="row listGroup">
            <div class="collapseContent col-md-6">
                <h3>You want</h3>
                <ul class="collapseContentBox">
                    <li>Large number of SMS messages to be sent to your clients or business contacts.</li>
                    <li>Keep in touch with your customers by SMS.</li>
                    <li>Automated outgoing message system.</li>
                    <li>Define existing customer list and groups.</li>
                    <li>Low costs and no infrastructure expenses.</li>
                    <li>Simple training how to use the SMS tools easily.</li>
                </ul>
            </div>
            <div class="collapseContent col-md-6">
                <h3>We have</h3>
                <ul class="collapseContentBox">
                    <li>Powerful and very intuitive-to-use SMS Newsletter application.</li>
                    <li>Application which automates the process of sending SMS messages to customers.</li>
                    <li>A system that sends all messages in very short time.</li>
                    <li>Easily imported or generated Excel sheet with necessary data.</li>
                    <li>Online tool tailored to your business needs.</li>
                    <li>Brief user-guide and intuitive interface.</li>
                </ul>
            </div>
        </div>
        <div class="row listGroup">
            <div class="collapseContent col-md-6">
                <h3>Features</h3>
                <ul class="collapseContentBox">
                    <li>Large number of SMS sent in a short timeframe.</li>
                    <li>Groups for sending enabled.</li>
                    <li>Full management over clients and groups for newsletter campaigns.</li>
                    <li>Individual Bulk SMS enabled.</li>
                    <li>Security settings for sending limitations enabled.</li>
                    <li>Real-time statistics and overview included.</li>
                    <li>Automated SMS sending process.</li>
                    <li>Real-time SMS status provided.</li>
                    <li>SMS sending scheduler provided.</li>
                    <li>SMS templates and target recipients' list enabled.</li>
                    <li>Online application without any investments or contracts needed.</li>
                </ul>
            </div>
            <div class="collapseContent col-md-6">
                <h3>Purpose</h3>
                <ul class="collapseContentBox">
                    <li>Successful marketing campaigns for new products or services (international campaigns included).</li>
                    <li>Increase CRM activities.</li>
                    <li>To send birthday wishes to customers.</li>
                    <li>Pick-up invitations sent to customers.</li>
                    <li>To send status messages.</li>
                    <li>To send appointment reminders.</li>
                    <li>To send payment reminders.</li>
                    <li>Meeting notes sent to participants.</li>
                    <li>Communication with staff.</li>
                    <li>Send automatically generated password during registration in order to enter in protected website areas.</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="col-md-3">
        <div class="row">
            <div class="col-md-12 col-xs-6 innerPageImage">
                <?php echo $this->renderPicture('picture1', '/images/inner/picture1', 'Placeholder image for sms winning game', '.jpg');?>
            </div>
            <div class="col-md-12 col-xs-6 innerPageImage">
                <?php echo $this->renderPicture('picture2', '/images/inner/picture2', 'Placeholder image for sms winning game', '.jpg');?>
            </div>
        </div>
    </div>
</div>
<section class="collapsibleSection">
    <h2>Description</h2>
    <div class="row description">
        <div class="col-md-9">
            <p>SMS Newsletter application allows you to send large number of messages to customers and your business contacts in no time!
            You are able to schedule time and date, but also fully customize these messages. Similar to Bulk SMS application, each message 
            can be sent individually – containing recipient’s full name which is ideal for a message with personal note and customer loyalty 
            messages. What is the most important, all contact details can be easily managed – either individually or in a group. Customer 
            contact details import or export is fully supported which makes your customer database very flexible for management and 
            maintenance. For subscription purpose, a sender can use either numeric or alphabetic keyword. This is a global service, so 
            customers can send SMS from all parts of the world.</p> 

            <p>Registered customers can also get newsletter updates about: news, weather reports, important sports results, etc. These 
            services can be additionally charged to your customers which opens a great opportunity to combine SMS Newsletter with 
            Premium SMS application.</p>

            <p>SMS Newsletter application is web based and can be easily accessed via regular Internet connection. The application is very
            intuitive and easy-to-use. We offer you a brief introduction (user guide) how to easily manage the application without any 
            problems. Furthermore, you can easily set up other direct marketing activities – SMS Newsletter application is only a starting 
            point that provides a quality customers' contact database. This application is ideal for companies, retailers, clubs / event 
            organizers, personal scheduling, personal use, etc. SMS Newsletter is quick and easy tool for sending useful information and call-
            to-action.</p>

            <p>Call us and get a personal advice now!</p>
        </div>
        <div class="col-md-3">
            <div class="row">
                <div class="col-md-12 col-xs-6 innerPageImage">
                    <?php echo $this->renderPicture('picture1', '/images/inner/picture1', 'Placeholder image for sms winning game', '.jpg');?>
                </div>
                <div class="col-md-12 col-xs-6 innerPageImage">
                    <?php echo $this->renderPicture('picture1', '/images/inner/picture1', 'Placeholder image for sms winning game', '.jpg');?>
                </div>
            </div>
        </div>  
    </div>
</section>
<section class="collapsibleSection">
    <h2>Preparations</h2>
    <div class="row">
        <div class="col-md-12">  
            <h3>Preparations from your side</h3>
            <ol>
                <li>Order your SMS Newsletter application.</li>
                <li>Brief introduction to the application via phone.</li>
                <li>Define your customer target group.</li>
                <li>Create SMS templates.</li>
                <li>Choose notification date and time.</li>
                <li>Let’s start</li>
            </ol>
            <h3>How your customers use SMS Newsletter application</h3>
            <ol>
                <li>Customer subscribes for SMS newsletter (opt-in).</li>
                <li>Then he/she gets regular messages from you.</li>
                <li>Customer then can decide whether he wants to use other applications (e.g. Premium SMS).</li>
                <li>Customer can, at any time, unsubscribe from the SMS newsletter service.</li>
            </ol>
        </div>
    </div>
</section>
<section class="collapsibleSection">
    <h2>Prices</h2>
    <div class="row">
        <div class="col-md-12">  
            <p><a href="<?php echo $this->contactUrl();?>">Contact us</a> or Download <a href="#">Order Form</a> in PDF.</p>
        </div>
    </div>
</section>