<div class="introTxt">
    <h1>SMS &amp; Park</h1>
    <h2>Convenient, fast and reliable service</h2>
</div>
<p>Ideal for car park operators, but also end-user experience.</p>
<div class="row innerRow">
    <div class="col-md-9 listWrapper">
        <div class="row listGroup">
            <div class="collapseContent col-md-6">
                <h3>You want</h3>
                <ul class="collapseContentBox">
                    <li>Flexible pay-to-park solution.</li>
                    <li>Reduced parking logistics.</li>
                    <li>Reliable parking payment system.</li>
                </ul>
            </div>
            <div class="collapseContent col-md-6">
                <h3>We have</h3>
                <ul class="collapseContentBox">
                    <li>Automated park and pay system.</li>
                    <li>Software that uses SMS messages to regulate parking.</li>
                    <li>Fast and accurate payment system.</li>
                </ul>
            </div>
        </div>
        <div class="row listGroup">
            <div class="collapseContent col-md-6">
                <h3>Features</h3>
                <ul class="collapseContentBox">
                    <li>Fast and simple payment system.</li>
                    <li>Payment possible with any mobile phone (just send SMS).</li>
                    <li>SMS reminder before the parking time elapses.</li>
                    <li>Parking extension with new SMS sent.</li>
                    <li>Charging over monthly mobile phone invoice.</li>
                    <li>SMS &amp; Park complements existing parking systems.</li>
                    <li>Can be used everywhere.</li>
                    <li>No physical money needed.</li>
                    <li>Convenient parking: no need to change parking spot.</li>
                </ul>
            </div>
            <div class="collapseContent col-md-6">
                <h3>Purpose</h3>
                <ul class="collapseContentBox">
                    <li>To introduce an easy and modern car parking system.</li>
                    <li>Reducing total car park operators' cost.</li>
                    <li>Attract drivers to use regular parking more often.</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="col-md-3">
        <div class="row">
            <div class="col-md-12 col-xs-6 innerPageImage">
                <?php echo $this->renderPicture('picture1', '/images/inner/picture1', 'Placeholder image for sms winning game', '.jpg');?>
            </div>
            <div class="col-md-12 col-xs-6 innerPageImage">
                <?php echo $this->renderPicture('picture2', '/images/inner/picture2', 'Placeholder image for sms winning game', '.jpg');?>
            </div>
        </div>
    </div>
</div>
<section class="collapsibleSection">
    <h2>Description</h2>
    <div class="row description">
        <div class="col-md-9">
            <p>Parking with SMS &amp; Park system is very simple and, above all, user friendly. The whole process consists of sending SMS message 
            with selected parking zone to parking service number. This system is excellent for any parking service because it can be used 
            everywhere across the country. It's also fully user-oriented; there are no unnecessary features or technology used to pay for 
            parking service.</p> 

            <p>Anyone can pay using mobile phone: one SMS charges parking fee without necessity to register within the system. SMS & Park
            works on every mobile phone and on all mobile networks, making it ideal for every user. There is no need for spare money 
            which is usually lacking in users' pockets. One SMS sent covers the parking for certain time. But, this is nothing to worry about! 
            By simply sending another SMS, user can extend the same parking for another round. When time is going to elapse, reminder 
            SMS will be sent. Using SMS is very popular because we are completely confident that every SMS will be delivered.</p>

            <p>SMS &amp; Park brings many advantages for drivers and car park operators. A great advantage for car park operator is the massive 
            cost saving potential which comes by reducing the operational and logistics cost. Cost savings are mainly achieved thanks to 
            cashless payment method, which saves the overall cash change management (collection of the coins, service and maintenance 
            of ticket machines, etc.).</p>

            <p>Totally reliable and fast service available to everyone at every place provided by parking service!</p>
        </div>
        <div class="col-md-3">
            <div class="row">
                <div class="col-md-12 col-xs-6 innerPageImage">
                    <?php echo $this->renderPicture('picture1', '/images/inner/picture1', 'Placeholder image for sms winning game', '.jpg');?>
                </div>
                <div class="col-md-12 col-xs-6 innerPageImage">
                    <?php echo $this->renderPicture('picture1', '/images/inner/picture1', 'Placeholder image for sms winning game', '.jpg');?>
                </div>
            </div>
        </div>  
    </div>
</section>
<section class="collapsibleSection">
    <h2>Preparations</h2>
    <div class="row">
        <div class="col-md-12">  
            <h3>What does the user do?</h3>
            <ol>
                <li>Goes to the parking and park a car;</li>
                <li>Type in the car registration number into SMS;</li>
                <li>Chooses a parking zone;</li>
                <li>Sends SMS message to specific service number;</li>
                <li>Gets an immediate answer that the parking is paid.</li>
                <li>If needed, extend the parking for another time period.</li>
            </ol>
            <h3>User benefits:</h3>
            <ol>
                <li>No cash or spare money needed;</li>
                <li>New SMS to extend parking.</li>
                <li>SMS reminder 10 minutes before parking expiration time.</li>
            </ol>
        </div>
    </div>
</section>
<section class="collapsibleSection">
    <h2>Prices</h2>
    <div class="row">
        <div class="col-md-12">  
            <p><a href="<?php echo $this->contactUrl();?>">Contact us</a> or Download <a href="#">Order Form</a> in PDF.</p>
        </div>
    </div>
</section>