<div class="introTxt">
    <h1>Our Team</h1>
    <h2>Number One Success Factor</h2>
</div>
<p>Alone we can do so little, together we can do so much. (Helen Keller)</p>
<h2>&#187; You don't build a business – you build people – and then people build your business &#171;</h2>

<p>There is a moment in your life when you know that certain people will simply make a difference. This is what I think about my
    team. Strong leaders with great entrepreneurship and communication skills on the one hand; and on the other, accurate and 
    logically-thinking, passionate and tech-savvy people. And each and every one of them is part of HORISEN company spirit.</p>
<p>A pretty diverse team. Building my team is the most valuable goal I have achieved in HORISEN so far. My people are self-driven, 
    motivated, committed to work and aware of how our business potential is to grow. The diversity in skills and knowledge is 
    confirmed through numerous successfully implemented projects and satisfied clients. HORISEN has become a professional and 
    competitive marketing technology company thanks to: great ideas, strong team work, kindness and willingness to help each 
    other in any situation.</p>
<p>My team consists of people. These people are professionals in their fields thus helping this company to grow; but, actually, they 
    are just people who know how to make you laugh at the end of the day. And making the right company spirit (with the right 
    people) is what ensures your business success!</p>
<?php echo $this->renderPicture('fabrizio-salanitri', '/images/inner/contact_person/fabrizio-salanitri', 'Placeholder image for contact person', '.png');?>
<p>Fabrizio Salanitri, CEO</p>
<p>Founder and Owner of HORISEN AG</p>
<p>HORISEN team (all employees)</p>
<?php echo $this->renderPicture('our_team', '/images/inner/team', 'Placeholder image for our team', '.jpg');?>