<div class="introTxt">
    <h1>Shaping</h1>
    <h2>contributes to your image</h2>
</div>
<p>Do you need more attention of the target group? Does your communication a crisp
    and zeitgemasses facelift or hovering in front of you a new advertising concept?
    We enitwickeln with your Mirwirken a suitable Strategic define objectives and implement them gesstalterisch attractive for you to.</p>
<p>Do you need more attention of the target group? Does your communication a crisp
    and zeitgemasses facelift or hovering in front of you a new advertising concept?
    We enitwickeln with your Mirwirken a suitable Strategic define objectives and implement them gesstalterisch attractive for you to.</p>
<div class="row servicesRow">
    <h3>Our services</h3>
    <div class="col-md-6">
        <ul>
            <li>Great SMS winning game for your customers.</li>
            <li>To give away prizes in different amounts.</li>
            <li>Quality customer database.</li>
            <li>No extra operational costs.</li>
        </ul>
    </div>
    <div class="col-md-6">
        <ul>
            <li>The best SMS winning game apps on the market.</li>
            <li>Automated prizes’ distribution system.</li>
            <li>Clever customer data collection strategies.</li>
            <li>Already defined SMS winning game prices.</li>
        </ul>
    </div>
</div>
<div class="graphicOverview">
    <div class="row">
        <div class="col-md-4 innerPageImage">
            <?php echo $this->renderPicture('logo-design', '/images/inner/services/logo-design', 'Placeholder image for our services', '.jpg');?>
            <p>Logo design</p>
        </div>
        <div class="col-md-4 innerPageImage">
            <?php echo $this->renderPicture('corporate-design', '/images/inner/services/corporate-design', 'Placeholder image for our services', '.jpg');?>
            <p>Corporate design</p>
        </div>
        <div class="col-md-4 innerPageImage">
            <?php echo $this->renderPicture('illustration', '/images/inner/services/illustration', 'Placeholder image for our services', '.jpg');?>
            <p>Illustration</p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4 innerPageImage">
            <?php echo $this->renderPicture('flyer', '/images/inner/services/flyer', 'Placeholder image for our services', '.jpg');?>
            <p>Flyer</p>
        </div>
        <div class="col-md-4 innerPageImage">
            <?php echo $this->renderPicture('magazin-design', '/images/inner/services/magazin-design', 'Placeholder image for our services', '.jpg');?>
            <p>Magazine design</p>
        </div>
        <div class="col-md-4 innerPageImage">
            <?php echo $this->renderPicture('sales-promotion', '/images/inner/services/sales-promotion', 'Placeholder image for our services', '.jpg');?>
            <p>Sales promotion</p>
        </div>
    </div>
</div>
