<div class="introTxt">
    <h1>Responsive Web Design</h1>
    <h2>Only the best designed websites survive</h2>
</div>
<p>For superior content consumption experience across all access devices.</p>
<div class="row innerRow">
    <div class="col-md-9 listWrapper">
        <div class="row listGroup">
            <div class="collapseContent col-md-6">
                <h3>You want</h3>
                <ul class="collapseContentBox">
                    <li>A better website.</li>
                    <li>Website that sales.</li>
                    <li>Professional web presence.</li>
                    <li>Highest security and data protection.</li>
                    <li>Website pages accessible and interactive.</li>
                    <li>Great design accessible from any device.</li>
                </ul>
            </div>
            <div class="collapseContent col-md-6">
                <h3>We have</h3>
                <ul class="collapseContentBox">
                    <li>Website development that covers all business needs.</li>
                    <li>Responsive web design included in web development process.</li>
                    <li>Expertise that helps you build successful websites.</li>
                    <li>High-security CMS built completely on our own</li>
                    <li>Team that brings you expected browsing results through various devices.</li>
                    <li>Interactive media and design options accessible from any device.</li>
                </ul>
            </div>
        </div>
        <div class="row listGroup">
            <div class="collapseContent col-md-6">
                <h3>Features</h3>
                <ul class="collapseContentBox">
                    <li>Fast coding – short developing time.</li>
                    <li>100% custom website – excellent coding and security enabled.</li>
                    <li>Custom art direction: responsive images that fit into custom screen size.</li>
                    <li>Responsive layout: website optimized for any device.</li>
                    <li>Better Search Engine Optimization (SEO) performance – with a single URL.</li>
                    <li>Fully "hacker-free" websites.</li>
                    <li>Landing pages optimized for mobile access.</li>
                    <li>Access to analytics from one source instead of multiple.</li>
                    <li>Easier maintenance that excludes mobile apps.</li>
                </ul>
            </div>
            <div class="collapseContent col-md-6">
                <h3>Purpose</h3>
                <ul class="collapseContentBox">
                    <li>Quality browsing experience and end-user satisfaction.</li>
                    <li>Visually appealing web presentations direction).</li>
                    <li>Good selling proposition within online brand appearance.</li>
                    <li>Interactive web pages – used from mobile device(s).</li>
                    <li>To speed up the buying process.</li>
                    <li>Competitiveness on the market/business industry.</li>
                    <li>Responsive web design increases leads.</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="col-md-3">
        <div class="row">
            <div class="col-md-12 col-xs-6 innerPageImage">
                <?php echo $this->renderPicture('picture1', '/images/inner/picture1', 'Placeholder image for sms winning game', '.jpg');?>
            </div>
            <div class="col-md-12 col-xs-6 innerPageImage">
                <?php echo $this->renderPicture('picture2', '/images/inner/picture2', 'Placeholder image for sms winning game', '.jpg');?>
            </div>
        </div>
    </div>
</div>
<section class="collapsibleSection">
    <h2>Description</h2>
    <div class="row description">
        <div class="col-md-9">
            <p>Successful business can happen only with a high-quality developed website. Building websites does not represent a 
            technological challenge anymore, but the real challenge is how to provide quality website content in terms of: concept and idea,  
            design, performance, using apps and writing quality content optimized for search engines. We compete on the market as the  
            leading providers of “all-inclusive” web packs – which means that we provide a fully-designed website for your business.</p> 

            <p>HORISEN web design utilizes latest insights from neuro-scientific research on how the human brain works. Despite design being
                subject to fashion trends and “flavours of the day” we incorporate neuro-marketing best practices to optimize impact and 
                perception of your web site. One compelling change on the market is the explosion of form factors and screen sizes people use 
                to browse the web: people now use laptops, tablets, smartphones or new devices like smart TV sets. A web site designed in 
                responsive layout uses fluid, proportion-based grids, flexible images and CSS3 media queries.</p>

            <p>“Mobile first” is a modern rule. More and more people access the Internet from their portable devices on daily basis. Responsive
            web design is a key to successful and visible business – especially for sales. According to some rough statistics made by the end 
            of 2013, 1 in 8 websites is responsive. With accelerating trends, mobile browsing will shortly overcome desktop Internet search. 
            Responsive web design is especially important for brands because many consumers are already using their mobile devices to 
            search products, but also purchase them this way.</p>
            
            <p>Besides mobile-first trending there is a concern about the overall web application security in the future. HORISEN builds 100%
                custom websites which satisfy the leading security requirements. Our high-security CMS is based on Zend Framework which 
                includes high performance, reduces development and ensures reliable and tested foundation. Security is completely in our 
                hands!<br /> 
                High-security CMS provides excellent coding which involves regular security testing and means that we provide more security-
                enabled websites. This testing is done using OWASP (Open Web Application Security Project) tool for a completely hacker-
                free web application testing. Our core competence are people that have wide range of security experience and use these 
                tools to achieve highest security protocols and ensure our web apps are protected all the time.</p>
            
            <p>Stay safe in the years to come, ensure your business sustainability with high-security enabled web applications done in
            responsive web design only – which is our own rule for success and relevance on the business market worldwide.</p>
            
            <p>In one of the interviews from the Forbes magazine, Responsive Web Design was described as: “Responsive websites simplify
            internet marketing and SEO (Search Engine Optimization). Instead of having to develop and manage content for multiple 
            websites, businesses with responsive sites can take a unified approach to content management because they have only the 
            one responsive site to manage”. Responsive web design is different from mobile site pages and, therefore, has many positive 
            features comparing it with websites done separately for mobile and desktop preview. It consists of just one URL so users can 
            access the same page using different access devices.</p>
            
            <p>So, using Responsive web design in your online business presentation will save your money, efforts and costs in multi-channel
            organization and product/service promotion. This feature comes along with custom website development, so you don’t need 
            to worry about adding it after website launch. Besides responsiveness, your web applications are secured from any malware, 
            totally “hacker-free” and tested on regular basis for flawless performance.</p>
            
            <p>User Experience Benefits:</p>
            <ul>
                <li>Users like sites which are visually appealing to them.</li>
                <li>The aesthetics of the responsive site will attract more visitors to come back.</li>
                <li>It’s more efficient and effective to use.</li>
                <li>Quick loading time needed, regardless of device.</li>
                <li>Same information and pages which are available for browsing.</li>
            </ul>      
            
        </div>
        <div class="col-md-3">
            <div class="row">
                <div class="col-md-12 col-xs-6 innerPageImage">
                    <?php echo $this->renderPicture('picture1', '/images/inner/picture1', 'Placeholder image for sms winning game', '.jpg');?>
                </div>
                <div class="col-md-12 col-xs-6 innerPageImage">
                    <?php echo $this->renderPicture('picture1', '/images/inner/picture1', 'Placeholder image for sms winning game', '.jpg');?>
                </div>
            </div>
        </div>  
    </div>
</section>
<section class="collapsibleSection">
    <h2>Preparations</h2>
    <div class="row">
        <div class="col-md-12">  
            <p>Responsive web design is part of any successfully developed web presentation – especially when it comes to a business. This
            step is done within initial project specification (technical documentation). The need for “Mobile first” websites has created the 
            whole new philosophy that uses strategic approaches to provide web best practices. This philosophy of mobile first websites 
            prioritizes mobile context in terms of end-user experience. So, mobile first allows websites to:</p>
            <ol>
                <li>Reach more people;</li>
                <li>Be functional forcing designers to focus on the core content;</li>
                <li>Take advantage of new technologies where designers innovate the process by adding geolocation, touch events, etc.;</li>
                <li>Increase sales because the complete content is also available “on the move”.</li>
            </ol>
        </div>
    </div>
</section>
<section class="collapsibleSection">
    <h2>Prices</h2>
    <div class="row">
        <div class="col-md-12">  
            <p><a href="<?php echo $this->contactUrl();?>">Contact us</a> or Download <a href="#">Order Form</a> in PDF.</p>
        </div>
    </div>
</section>