<?php
    $this->headScript()->appendFile('/plugins/imagebrowser/jquery.imagebrowserdialog.js');
    $this->headScript()->appendFile('/plugins/serverbrowser/jquery.filebrowserdialog.js');

    $this->headScript()->appendFile('/plugins/hfb/js/jquery.hfbSelect.js');
    $this->headScript()->appendFile('/plugins/hfb/js/jquery.hfbSearch.js');
    $this->headScript()->appendFile('/plugins/hfb/js/jquery.hfbList.js');
    #$this->headScript()->appendFile('/plugins/tableDnD/jquery.tablednd.js');
    $this->headScript()->appendFile('/modules/admin/js/list.js');
    $this->headScript()->appendFile('/modules/bgchanger/js/menuBg.js');
    $settings = Bgchanger_Model_MenuItemBackgroundMapper::getInstance()->getSettings(); 
    ?>


<script type="text/javascript">    
    var settings = <?php echo json_encode($settings); ?>; 
</script>

<script type="text/javascript">
    var listUrl = '/' + CURR_LANG + '/bgchanger/admin-menu/menu-list/?langFilter=<?php echo $this->defaultLang;?>';
    //$(document).ready(function(){
    $('.bgcImage').live('mouseenter', function () {
            var _position = $(this).position();
            var _positionParent = $(this).parent().position();
            $('#bgcPreview')
                .css('display', 'block')
                .css('top', (_positionParent.top + _position.top) + 'px')
                .css('left', (_positionParent.left + _position.left + 75) + 'px');
            $('#bgcPreviewImage').attr('src', $(this).attr('src'));
        }
    );
    $('.bgcImage').live('mouseleave', function () {
            $('#bgcPreview').css('display', 'none');
        }
    );
    //});
</script>

<script type="text/html" id="images_tpl">
<%  if (images){
        for ( var imageId in images){
            var image = images[imageId];
            var imageValue = (data && data['content'] && data['content'][imageId])? data['content'][imageId]: '';%>    
    <label class="customImage"><%=image.name %>
        <div class="customImage">
            <input type="text" class="_input backgroundImage" data-id="<%=imageId %>" name="data[content][<%=imageId %>]"  id="data[content][<%=imageId %>]" value="<%=imageValue%>" maxlength="255" />
        </div>        
    </label>
<%      }
    } %>    
</script>

<div id="bgcPreview" style="position: absolute; background: #eee; border: 1px solid #bbb; padding: 10px; display: none; z-index: 2;" class="clearfix">
    <img id="bgcPreviewImage" src="" style="width: 500px;"/>
</div>
<div class="hcms_content_top">
    <h1><?php echo $this->translate('Menu Items Background'); ?> </h1>
    <span class="hcms_search">
    </span>
</div>
<div class="hcms_content">
    <div class="language">
        <label><?php echo $this->translate('Menu');?></label>
        <select id="menuFilter" name="menuFilter">
            <?php foreach ($this->menus as $menu) {?>
            <option value="<?php echo $menu['code'];?>" <?php if($menu['code'] == 'main') {?>selected="selected" <?php } ?>><?php echo $this->escape($menu['name']);?></option>
            <?php }?>
        </select>
        <?php if($this->singleLang === false){?>
        <label><?php echo $this->translate('Language');?></label>
        <select id="langFilter" name="langFilter">
            <?php echo $this->langOptions($this->languages,$this->defaultLang,true);?>
        </select>
        <?php }?>
       <!-- <span class="hcms_button"><a href="#">Filter</a></span> -->
    </div>
    <table class="hcms_table adminList" width="100%">
        <thead>
            <tr>
                <th><a href="#" class="sort" data-column="name"><?php echo $this->translate('Name');?><b></b></a></th>
                <th width="20%"><a href="#" class="sort" data-column="hidden"><?php echo $this->translate('Hidden');?><b></b></a></th>
            </tr>
        </thead>
    </table>
    <table class="hcms_table adminList" width="100%" id="listContainer">
        <tbody>
        </tbody>
    </table>
    <div id="pager"></div>
</div>
<script type="text/html" id="records_tpl">
<% menuItemData = rows;
    if (rows.length > 0){
    var rowClass = 'odd';
    %>
    <% for ( var i = 0; i < rows.length; i++ ){
        rowClass = (i % 2 == 0)? 'even':'odd';
    %>
    <tr class="<%=rowClass%>" id="listContainer-row-<%=rows[i].id%>" >
            <td  style="padding-left:<%=rows[i].level * 50 + 10%>px; position: relative;" >
                <% if (rows[i].image_path != ''){ %>
                <img src="<%=rows[i].image_path%>" data-menu_item_id="<%=rows[i].id%>" style="float: left; margin: 0 10px; width: 50px;" class="bgcImage"/>
                <% }%>
                <%=rows[i].name%><br />
                <ul class="hcms_menu_actions" style="left: 55px; position: static;">
                    <li><a href="#" class="edit" data-id="<%=rows[i].id%>"><?php echo $this->translate('Edit');?></a></li>
                </ul>
            </td>
            <td width="20%">
                <%=rows[i].hidden%>
            </td>
        </tr>
    <% } %>
<% } %>
</script>