<script type="text/javascript">
    $(document).ready(function(){
        $("#data\\[route\\]").change(function(){
            
            if($(this).val() == 'cms'){
                $('#routeUri').show();
            }else{
                $('#routeUri').hide();
            }
            if($(this).val() == ''){
                $("#data\\[page_id_new\\]").val("");
                $('#routeUri').hide();  
                $('#path').hide();  
                $('#pageId').hide();  
                $('#params').hide();  
                $('#uri').show();  
            }else{
                $('#path').show();
                if($("#data\\[page_id_new\\]").val() == ''){
                    openDialog();
                }
                $("#data\\[page_id_new\\]").val("");
                $("#pageName").text("");
                if($("#data\\[path\\]").find('option:selected').data('dialog') == ''){
                    $("#data\\[page_id_new\\]").val("");
                    $("#pageName").text("");
                    $('#pageId').hide();
                }else{
                    $('#pageId').show(); 
                }
                $('#params').show();  
                $('#uri').hide();  
            }
        });
         $("#data\\[path\\]").change(function(){
            openDialog();
            return false;
        });
        $("#pageName").click(function(){
            openDialog();
            return false;
        });
        $("#pageDelete").click(function(){
            $("#data\\[page_id_new\\]").val("");
            $("#pageName").text("");
            return false;
        });
        $("#pageSelect").click(function(){
            openDialog();
            return false;
        });
        $("#pageId").find('div').hover(
            function(){
                if( $("#data\\[page_id_new\\]").val() != ''){
                    
                }
                $(this).find('ul.page_actions').show();
            },
            function(){
                $(this).find('ul.page_actions').hide();
            }
        );
     });
     
     
     function openDialog(){
        var selected = $("#data\\[path\\]").find('option:selected');
        var dialogUrl = selected.data('dialog'); 
        if(dialogUrl != '' ){
            $('#pageId').show();
            ajaxForm.dialog('/' + CURR_LANG + '/' +dialogUrl + '/page_id/'+$("#data\\[page_id_new\\]").val() + '/langFilter/' + '<?php echo $this->langFilter ;?>',{
                onContent: function(dialog){

                },
                onClose: function(success, data){
                    if(success){
                        if(data.data){
                           data = data.data; 
                           $("#data\\[page_id_new\\]").val(data['page_id']); 
                           $("#pageName").text(data[data.page_id]['title']); 
                        }else{
                            updateList();
                        }
                    }
                },
                width: 'auto',
                height: 'auto',
                dialogId :'pageDialog',
                saveCaption:'<?php echo $this->translate('Select'); ?>'
            });
        }else{
            $("#data\\[page_id_new\\]").val("");
            $("#pageName").text("");
            $('#pageId').hide();
        }
    }
 </script>
 <div id="pageDialog" title="Dialog Title" style="display: none;"></div>

<form method="post" class="hcms_form" title="<?php if(isset($this->data['id']) && $this->data['id'] != '') {
     printf($this->translate('Edit \'%s\' Menu Item'), $this->escape($this->menuFilter)); 
}else {
    printf($this->translate('Add new \'%s\' Menu Item'), $this->escape($this->menuFilter));
      }?>" action="<?php echo $this->url(array('controller' => 'admin-menu', 'action' => 'menu-edit')) ?>" enctype="application/x-www-form-urlencoded">
    <input type="hidden" id="data[id]" value="<?php echo $this->escape($this->data['id']);?>" name="data[id]"/>
    <input type="hidden" name="data[menu]" id="data[menu]"  value="<?php echo $this->escape($this->menuFilter);?>" />
    <input type="hidden" name="data[dialog_url]" id="data[dialog_url]"  value="" />
    <div class="clearfix">
        <div>
            <label for="data[name]" title="<?php echo $this->translate('Menu Item Name') ;?>"><?php echo $this->translate('Name');?>:</label>
            <input type="text" title="<?php echo $this->translate('Menu Item Name') ;?>" name="data[name]" title="<?php echo $this->translate('Menu Item Name') ;?>" id="data[name]" value="<?php echo $this->escape($this->data['name']);?>" maxlength="100" style="width:200px;" />
            <?php echo $this->errorMessages($this->errors['name']);?>
        </div>
         <div>
             <label for="data[parent_id]" title="<?php echo $this->translate('Parent Menu') ;?>" ><?php echo $this->translate('Parent');?>:</label>
            <input type="hidden" id="parent_selected" value="<?php echo $this->escape($this->data['parent_id']);?>"/>
            <select id="data[parent_id]" title="<?php echo $this->translate('Parent Menu') ;?>" name="data[parent_id]" style="width:200px;">
                <option value="">select</option>
            </select>
            <?php echo $this->errorMessages($this->errors['parent_id']);?>
        </div>
    </div>
    <div class="clearfix">
        <div>
            <label for="data[route]" title="<?php echo $this->translate('Url Type') ;?>"><?php echo $this->translate('Url Type');?>:</label>
            <select id="data[route]" title="<?php echo $this->translate('Url Type') ;?>" name="data[route]" style="width:200px;">
                <option value=""><?php echo $this->translate('Direct Link');?></option>
                <?php foreach($this->routes as $route) {?>
                <option  value="<?php echo $route;?>" <?php if($route == $this->data['route']) { ?> selected="selected" <?php } ?>><?php echo $this->translate($route);?> </option>
                <?php } ?>
            </select>
            <?php echo $this->errorMessages($this->errors['route']);?>
        </div>
        <div id="routeUri" <?php if($this->data['route'] != "cms"){?> style="display: none;"<?php } ?>> 
                <label for="route[uri]" title="<?php echo $this->translate('URL part after language identificator') ;?>"><?php echo $this->translate('URL');?>:</label>
                <input type="text" title="<?php echo $this->translate('URL part after language identificator') ;?>" name="data[route_uri]" id="data[route_uri]" value="<?php echo $this->escape($this->data['route_uri']);?>" maxlength="200" style="width:200px;" />
        </div>
    </div>
    <div class="clearfix">
        <div id="path" <?php if($this->data['route'] == ""){?> style="display: none;"<?php } ?>>
            <label for="data[path]" title="<?php echo $this->translate('Destination Module') ;?>"><?php echo $this->translate('Destination Module');?>:</label>
            <select id="data[path]" title="<?php echo $this->translate('Destination Module') ;?>" name="data[path]" style="width:200px;">
                <?php foreach($this->modules as $module) {?>
                <?php $data = $module->get_data();
                    if(isset($data['menus'])){?>
                        <optgroup label="<?php echo $module->get_name();?>">
                            <?php foreach($data['menus'] as $path => $menu) {?>
                            <option data-dialog="<?php echo $menu['dialog_url']; ?>" value="<?php echo $module->get_code()."/".$path ;?>" <?php if($module->get_code()."/".$path == $this->data['path']) { ?> selected="selected" <?php } ?>><?php echo $menu['name'];?> </option>
                            <?php } ?>
                        </optgroup>
                <?php } 
                }?>
                    
            </select>
            <?php echo $this->errorMessages($this->errors['path']);?>
        </div>
        <div id="pageId" <?php if($this->data['route'] == "" || ($this->data['page_id'] == "" &&  $this->data['id'] != "")){?> style="display: none;"<?php } ?>>
            <label for="data[page_id]" title="<?php echo $this->translate('Page') ;?>"><?php echo $this->translate('Page');?>:</label>
            <input type="hidden" name="data[page_id]"  id="data[page_id]" value="<?php echo $this->escape($this->data['page_id']);?>" />
            <input type="hidden" name="data[page_id_new]" id="data[page_id_new]" value="<?php echo $this->escape($this->data['page_id']);?>" maxlength="100" style="width:200px;" />
            <div style="margin-top: 2px;padding-top: 4px ;padding-left: 4px; border: 1px solid #D0D0D0;display: block;width: 200px;height: 18px;">
                <a href="#" style=" font-size: 14px;color: #999999;" id="pageName" title="<?php echo $this->translate('Change Page');?>" ><?php echo (isset($this->page_title))?$this->escape($this->page_title) : "";?></a>
                <ul class="page_actions" style="float:right;display: none;">
                    <li style="display: inline"><a href="#" id="pageDelete" title="<?php echo $this->translate('Remove Page') ;?>"><?php echo $this->translate('Remove');?></a></li>
                    <li style="display: inline"><a href="#" id="pageSelect" title="<?php echo $this->translate('Select Page') ;?>"><?php echo $this->translate('Select');?></a></li>
                </ul>
            </div>
            <?php echo $this->errorMessages($this->errors['page_id']);?>
        </div>
    </div>
    <div class="clearfix"> 
        <div id="params" <?php if($this->data['route'] == ""){?> style="display: none;"<?php } ?>>
            <input type="hidden" name="data[params_old]" id="data[params_old]" value="<?php echo $this->escape($this->data['params']);?>"  />
            <label title="<?php echo $this->translate('Additional parameters to be appended to URL in the form of &quot;name/value&quot;') ;?>" for="data[params]"><?php echo $this->translate('Custom Params');?>:</label>
            <input type="text" title="<?php echo $this->translate('Additional parameters to be appended to URL in the form of &quot;name/value&quot;') ;?>" name="data[params]" id="data[params]" value="<?php echo $this->escape($this->data['params']);?>" maxlength="100" style="width:200px;" />
            <?php echo $this->errorMessages($this->errors['params']);?>
        </div>
        <div id="uri" <?php if($this->data['route'] != ""){?> style="display: none;"<?php } ?>>
            <label for="data[uri]"><?php echo $this->translate('Link');?>:</label>
            <input type="text" name="data[uri]" id="data[uri]" value="<?php echo $this->escape($this->data['uri']);?>" maxlength="100" style="width:200px;" />
            <?php echo $this->errorMessages($this->errors['uri']);?>
        </div>
    </div>
    <div class="clearfix">
        <div>
            <label for="data[ord_num]"><?php echo $this->translate('Order Num');?>:</label>
            <input type="text" name="data[ord_num]" id="data[ord_num]" value="<?php echo $this->escape($this->data['ord_num']);?>" maxlength="100" style="width:80px;" />
            <?php echo $this->errorMessages($this->errors['ord_num']);?>
        </div>
        <div>
            <label for="data[hidden]"><?php echo $this->translate('Hidden');?>:</label>
            <select name="data[hidden]" id="data[hidden]" style="width:70px;">
                    <option value="yes" <?php if($this->data['hidden'] == 'yes' ) {?> selected="selected" <?php } ?>><?php echo $this->translate('Yes');?></option>
                    <option value="no" <?php if($this->data['hidden'] == 'no' ) {?> selected="selected" <?php } ?>><?php echo $this->translate('No');?></option>
            </select>
            <?php echo $this->errorMessages($this->errors['hidden']);?>
        </div>
        <div>
            <label for="data[target]"><?php echo $this->translate('Target');?>:</label>
            <select name="data[target]" id="data[target]" style="width:70px;">
                    <option value="" <?php if($this->data['target'] == '' ) {?> selected="selected" <?php } ?>><?php echo $this->translate('self');?></option>
                    <option value="_blank" <?php if($this->data['target'] == '_blank' ) {?> selected="selected" <?php } ?>><?php echo $this->translate('blank');?></option>
            </select>
            <?php echo $this->errorMessages($this->errors['hidden']);?>
        </div>
        <input type="submit" value="<?php echo $this->translate('Save');?>" name="submit[save]" />
    </div>
</form>