<div class="introTxt">
    <h1>Web Apps: Shape your visitors’ web experience</h1>
    <h2>Integrated online tools for successful businesses.</h2>
</div>
<p>You are spot-on: HORISEN is the leading SMS winning game app provider.</p>
<div class="row innerRow">
    <div class="col-md-9 listWrapper">
        <div class="row listGroup">
            <div class="collapseContent col-md-6">
                <h3>You want</h3>
                <ul class="collapseContentBox">
                    <li>Fast setup of engaging web applications.</li>
                    <li>To wrap-up your online presence.</li>
                    <li>Additional features for your website.</li>
                    <li>More visitors coming to your website.</li>
                    <li>Quality conversions and visitor experience.</li>
                </ul>
            </div>
            <div class="collapseContent col-md-6">
                <h3>We have</h3>
                <ul class="collapseContentBox">
                    <li>Web apps specialist who know exactly which app to
                    develop for your web presentation.</li>
                    <li>Different web apps already developed.</li>
                    <li>Custom app features tailored to specific
                    requirements.</li>
                    <li>Attractive add-ons and web extensions.</li>
                    <li>Digital consumer research results as example.</li>
                </ul>
            </div>
        </div>
        <div class="row listGroup">
            <div class="collapseContent col-md-6">
                <h3>Features</h3>
                <ul class="collapseContentBox">
                    <li>Custom web extensions.</li> 
                    <li>Mobile ready for any device.</li>
                    <li>Webmail app included.</li> 
                    <li>Employee/customer portal enabled.</li> 
                    <li>Live support widget.</li> 
                    <li>User login enabled.</li>
                </ul>
            </div>
            <div class="collapseContent col-md-6">
                <h3>Purpose</h3>
                <ul class="collapseContentBox">
                    <li>Interactive web presentations.</li>
                    <li>Attractive content and web pages.</li>
                    <li>Apps that help the conversion process visitor  customer.</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="col-md-3">
        <div class="row">
            <div class="col-md-12 col-xs-6 innerPageImage">
                <?php echo $this->renderPicture('picture1', '/images/inner/picture1', 'Placeholder image for sms winning game', '.jpg');?>
            </div>
            <div class="col-md-12 col-xs-6 innerPageImage">
                <?php echo $this->renderPicture('picture2', '/images/inner/picture2', 'Placeholder image for sms winning game', '.jpg');?>
            </div>
        </div>
    </div>
</div>
<section class="collapsibleSection">
    <h2>Description</h2>
    <div class="row description">
        <div class="col-md-9">
            <p>In this hyper-competitive landscape, only the best designed websites survive as competition in just one click away. Here 
            HORISEN brings in best practices and knowhow from countless numbers of designed websites using latest insights from neuro-science 
            and digital consumer research. Rapid deployment and seamless integration is imperative for any marketing campaign 
            success. HORISEN rapid deployment methodology enables going-live within weeks after kick-off building on top of developed 
            web app building blocks.</p> 

            <p>Web apps support many widgets made for web pages but also social networks, then interactive and animated banners, website
            headers, intros and, but also microsites enabled to work on every device. Website apps can work in responsive web design as 
            well, supporting quality and easy browsing.</p>

            <p>A fully customizable web experience tailored for each business or industry – with different web apps you get the right view of 
            your business, combined with smart marketing approach and concrete sales pitch. That’s why marketing technology is a 
            necessary part of your online presence and promotion.</p>
        </div>
        <div class="col-md-3">
            <div class="row">
                <div class="col-md-12 col-xs-6 innerPageImage">
                    <?php echo $this->renderPicture('picture1', '/images/inner/picture1', 'Placeholder image for sms winning game', '.jpg');?>
                </div>
                <div class="col-md-12 col-xs-6 innerPageImage">
                    <?php echo $this->renderPicture('picture1', '/images/inner/picture1', 'Placeholder image for sms winning game', '.jpg');?>
                </div>
            </div>
        </div>  
    </div>
</section>
<section class="collapsibleSection">
    <h2>Preparations</h2>
    <div class="row">
        <div class="col-md-12">  
            <ol>
                <li>Business idea – necessary apps for your online presence success</li>
                <li>Writing project specification</li>
                <li>Web apps design</li>
                <li>Web apps integration</li>
                <li>A/B testing</li>
                <li>Measuring success.</li>
            </ol>
        </div>
    </div>
</section>
<section class="collapsibleSection">
    <h2>Prices</h2>
    <div class="row">
        <div class="col-md-12">  
            <p>For custom web app development prices, please <a href="mailto:info@horisen.com">contact us</a>.</p>
        </div>
    </div>
</section>