<?php
//we don't need layout - the page will contain all needed
$this->layout()->setLayout('intro');
?>
        <div id="sequence">
            <div class="sequence-next-container">
                <img class="sequence-next" src="<?php echo ('/images/arrows-01.png'); ?>" alt="Next" />
            </div>
            <ul class="sequence-canvas">
                <li class="animate-in">
                    <div class="info">
                        <h1>On our way to <span class="bold">success</span></h1>
                        <h2>Since 2001 we’ve been working on bringing all digital communication channels under one umbrella to make a single, cross-media channel.</h2>
                        <span class="hwButton">Learn more</span>
                    </div>
                    <div class="back slide1"></div>
                </li>
                <li>
                    <div class="info">
                        <h1>High above the <span class="bold">expectations</span></h1>
                        <h2>We offer cloud-based combination of mobile apps and digital services which improve the total customer experience and end-user satisfaction.</h2>
                        <span class="hwButton">Learn more</span>
                    </div>
                    <div class="back slide2"></div>
                </li>
                <li>
                    <div class="info">
                        <h1>Meet our partners' <span class="bold">milestones</span></h1>
                        <h2>Together we design your roadmap! With our partner program you choose, decide and design your business solutions and packages easily. </h2>
                        <span class="hwButton">Learn more</span>
                    </div>
                    <div class="back slide3"></div>
                </li>
                <li>
                    <div class="info">
                        <h1>Maintain tight <span class="bold">relationships</span></h1>
                        <h2>A well-defined, executable and measurable cross-media strategy provides you with competitive advantage in your overall business workflow.</h2>
                        <span class="hwButton">Learn more</span>
                    </div>
                    <div class="back slide4"></div>
                </li>
                <li>
                    <div class="info">
                        <h1>Make our goals <span class="bold">sustainable</span></h1>
                        <h2>HORISEN has grown into a large business thanks to hundreds of satisfied clients and partners which businesses are constantly developing.</h2>
                        <span class="hwButton">Learn more</span>
                    </div>
                    <div class="back slide5"></div>
                </li>
            </ul>
        </div>