<div class="introTxt">
    <h1>megafanapps.com</h1>
    <h2>Organize your business fan page in a few clicks!</h2>
</div>
<p>Successful social media marketing campaigns using Facebook.</p>
<div class="row innerRow">
    <div class="col-md-9 listWrapper">
        <div class="row listGroup">
            <div class="collapseContent col-md-6">
                <h3>You want</h3>
                <ul class="collapseContentBox">
                    <li>Attractive fan page content.</li>
                    <li>Engaging campaigns for more viral buzz.</li>
                    <li>Quality contact database.</li>
                    <li>Cost-effective promo activities.</li>
                </ul>
            </div>
            <div class="collapseContent col-md-6">
                <h3>We have</h3>
                <ul class="collapseContentBox">
                    <li>5 different app categories including custom apps.</li>
                    <li>Customer engaging apps for all occasions during the year.</li>
                    <li>Customizable campaign management and quality data export and analysis.</li>
                    <li>White-label communication with customers beyond campaign’s runtime.</li>
                </ul>
            </div>
        </div>
        <div class="row listGroup">
            <div class="collapseContent col-md-6">
                <h3>Features</h3>
                <ul class="collapseContentBox">
                    <li>Unlimited number of campaigns per app.</li>
                    <li>Unlimited number of Facebook page likes.</li>
                    <li>Mobile access to live campaigns.</li>
                    <li>Easy-to-navigate app admin cockpit.</li>
                    <li>WYSIWYG editor for live configuration preview.</li>
                    <li>Ready-made app designs and custom CSS upload.</li>
                    <li>Custom app development enabled.</li>
                </ul>
            </div>
            <div class="collapseContent col-md-6">
                <h3>Purpose</h3>
                <ul class="collapseContentBox">
                    <li>Increase website traffic.</li>
                    <li>Quality product/service promotion.</li>
                    <li>Fast customer conversion: visitor fan customer.</li>
                    <li>Cost-effective advertising: no extra payments.</li>
                    <li>Suitable to any industry or company size.</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="col-md-3">
        <div class="row">
            <div class="col-md-12 col-xs-6 innerPageImage">
                <?php echo $this->renderPicture('picture1', '/images/inner/picture1', 'Placeholder image for sms winning game', '.jpg');?>
            </div>
            <div class="col-md-12 col-xs-6 innerPageImage">
                <?php echo $this->renderPicture('picture2', '/images/inner/picture2', 'Placeholder image for sms winning game', '.jpg');?>
            </div>
        </div>
    </div>
</div>
<section class="collapsibleSection">
    <h2>Description</h2>
    <div class="row description">
        <div class="col-md-9">
            <p>Online presence does not only include a quality and, ideally, interactive web presentation – your business website. Social media
            accounts and cross-channel consistency is something you have to take care of in order to be competitive on the market. Since 
            Facebook is still number one social media network, a lot of businesses are already very active. Not only small or medium sized 
            companies (SMEs), but also multinational companies that maintain their popularity and try to attract even more customers via 
            social media networks – especially Facebook.</p> 

            <p>That’s why we created Facebook apps platform – engaging apps for social media professionals. Megafanapps is a reliable way to 
            convert fans into loyal customers. Variety of customer engaging apps will help you achieve great fan page viral buzz, boost your 
            sales and increase website traffic. Most of the apps are highly entertaining and thus drive virality to your Facebook business 
            page. Pimp your fan page with just a few clicks; easy-to-navigate admin cockpit help you to configure and run quality campaigns 
            for any sort of occasion during the year, including unlimited number of campaigns per app license.</p>

            <p>Quality customer database with possibility of data export (in csv), custom CSS upload for great design and brand consistency,
            totally customizable contact form and mobile access to apps during the campaign are key elements for successful social media 
            marketing. Furthermore, instant coupon awards help to achieve fast and continuous redemption – ideal for sales and customer 
            retention! On the other hand, if you have another idea and need a very specific promotion, we help you develop custom apps 
            that will fit into your specific business’ needs.</p>

            <p>By signing up to our agency partner program, you have up to 45% discount on apps and more campaign management privileges.</p>
        </div>
        <div class="col-md-3">
            <div class="row">
                <div class="col-md-12 col-xs-6 innerPageImage">
                    <?php echo $this->renderPicture('picture1', '/images/inner/picture1', 'Placeholder image for sms winning game', '.jpg');?>
                </div>
                <div class="col-md-12 col-xs-6 innerPageImage">
                    <?php echo $this->renderPicture('picture1', '/images/inner/picture1', 'Placeholder image for sms winning game', '.jpg');?>
                </div>
            </div>
        </div>  
    </div>
</section>
<section class="collapsibleSection">
    <h2>Campaign Ideas</h2>
    <div class="row">
        <div class="col-md-12">
            <ol>
                <li>Promote your products or services around major national holidays.</li>
                <li>Run specific campaigns related to your brand or service.</li>
                <li>Organize daily, weekly or monthly winning game.</li>
                <li>Organize products’ quiz – ask your fans questions regarding your newest product/service.</li>
                <li>Make your fans take photos while using your products.</li>
                <li>Apps provide entertaining content for your regular wall posts.</li>
                <li>Put bigger prize for the next campaign and attract even more fans.</li>
                <li>Offer your fans immediate rewards by giving discount vouchers.</li>
                <li>Empty your excess stock during the sales season.</li>
            </ol>
        </div>
    </div>
</section>
<section class="collapsibleSection">
    <h2>Prices</h2>
    <div class="row">
        <div class="col-md-12">  
            <h3>Prices div goes here...</h3>
        </div>
    </div>
</section>