<?php
$this->doctype('HTML5');
echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml" lang="<?php echo $this->currLang; ?>">
<head>
    <base href="<?php echo $this->serverUrl() . $this->fileWebRoot; ?>" />
    <meta charset="utf-8" />
    <?php
        $favicon =  '/images/favicon.ico';
        $this   ->headLink(array('rel' => 'icon', 'href' => $favicon, 'type' => 'image/x-icon'),'PREPEND')
                ->headLink(array('rel' => 'shortcut icon', 'href' => $favicon, 'type' => 'image/x-icon'),'PREPEND'); //fb ico
        //fb sharer
        echo $this->headMeta();
        echo $this->headTitle();
        $this->headLink()->prependStylesheet( '/css/style.css');
        echo $this->headLink();

        echo $this->headScript();
        echo $this->headStyle();
    ?>    

    <?php
        //bg changer - comment out if it's to be used in the project
        //echo $this->bgChanger();
        if(isset ($this->application)){
            $gaSettings = $this->application->get_settings('ga');
            //check ga settings
            if(isset ($gaSettings) && isset ($gaSettings['tracking_id'])){
    ?>
<script type="text/javascript">
//GA
var _gaq = _gaq || [];
_gaq.push(['_setAccount', '<?php echo $this->escape($gaSettings['tracking_id']);?>']);
_gaq.push(['_trackPageview']);

(function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
})();
</script>
<?php
        }
    }
?>
</head>
<body>
<div class="wrapper">
    <header class="clearfix">
    	<div class="wrap clearfix">
            <br />
            <span id="logo">HORISEN CMS</span>
        </div><br />
        <span style="color:red;">Theme is not activated!!</span>
    </header>
    <section class="content">
        <?php echo $this->layout()->content; ?>
    </section>
</div>
</body>
</html>

