<?php
$this->headScript()->appendFile('/plugins/hfb/js/jquery.hfbSelect.js');
$this->headScript()->appendFile('/plugins/hfb/js/jquery.hfbSearch.js');
$this->headScript()->appendFile('/plugins/hfb/js/jquery.hfbList.js');
$this->headScript()->appendFile('/plugins/hfb/js/jquery.hfbImagePath.js');
$this->headScript()->appendFile('/modules/admin/js/list.js');
$this->headScript()->appendFile('/plugins/imagebrowser/jquery.imagebrowserdialog.js');
$this->headScript()->appendFile('/plugins/serverbrowser/jquery.filebrowserdialog.js');
$this->headScript()->appendFile('/plugins/tinymce/jquery.tinymce.js');
$this->headScript()->appendFile('/js/tinyCommon.js');
$this->headScript()->appendFile('/plugins/coolfieldset/js/jquery.coolfieldset.js');
$this->headScript()->appendFile('/plugins/jquery-ui-timepicker-addon/jquery-ui-timepicker-addon.js'); 
$this->headLink()->appendStylesheet('/plugins/coolfieldset/css/style.css');
$this->headLink()->appendStylesheet('/plugins/hfb/css/style.css');

$typeEditData = array();
$typeDeleteData = array();
/*@var $type Cms_Model_PageType */
foreach ($this->types as $type) {
    $editData = $type->get_data('edit');
    if(isset ($editData)){
        $typeEditData[$type->get_id()] = $editData;
    }
    $deleteData = $type->get_data('delete');
    if(isset ($deleteData)){
        $typeDeleteData[$type->get_id()] = $deleteData;
    }
}
/*@var $pageType Cms_Model_PageType */
$pageType = $this->pageType;
$singleType = isset ($pageType);
?>
<script type="text/javascript">
    var cmsSettings = <?php echo json_encode($this->moduleSettings); ?>;
    var typeEditData = <?php echo json_encode($typeEditData); ?>;
    var typeDeleteData = <?php echo json_encode($typeDeleteData); ?>;
    var typeEditFunctions = {};
    var pageType = <?php echo isset ($pageType)?json_encode($pageType->toArray()):'{}'; ?>;
    var singleType = <?php echo json_encode($singleType); ?>;
    var picker = "<?php echo $this->picker; ?>";
    function getEditUrl(id,lang,typeId){
        var typeEditLink = 'cms/admin/page-edit';

        if(typeId && typeEditData[typeId] && typeEditData[typeId].link){
            typeEditLink = typeEditData[typeId].link;
        }
        if(!lang || lang == null || lang == undefined){
            return sprintf('/%s/' + typeEditLink + '/id/%d/type_id/%d',CURR_LANG,id,typeId);
        }
        return sprintf('/%s/' + typeEditLink + '/id/%d/langFilter/%s/type_id/%d',CURR_LANG,id,lang,typeId);
    }

    function editDialog(id,typeId){
        ajaxForm.dialog(getEditUrl(id,$("#langFilter").val(),typeId),{
            onContent: function(dialog){
                if((!cmsSettings['tiny'] || !cmsSettings['tiny']['disabled']) && dialog.find("#data\\[format\\]").val() == 'html' ){
                    //tiny
                    var localTinyOpts = {
                        width:"520",
                        height:"300",
                        theme_advanced_buttons1 : "bold,italic,underline,strikethrough,sub,sup,|,justifyleft,justifycenter,justifyright,justifyfull,formatselect,bullist,numlist,outdent,indent,|,cut,copy,paste,pasteword",
                        theme_advanced_buttons2 : "undo,redo,|,link,unlink,anchor,image,cleanup,code,|,hr,removeformat,|,media,advhr,charmap"
                    };
                    //must render tiny from here due to FF error
                    tiny.init(dialog.find("#data\\[content\\]"), fileWebRoot, "",localTinyOpts);
                }
                //change format
                dialog.find("#data\\[format\\]").change(function(){
                    //add tiny
                    if($(this).val() == 'html'){
                        tiny.init(dialog.find("#data\\[content\\]"), fileWebRoot, "",localTinyOpts);
                    }
                    //remove tiny
                    else{
                        if (tinyMCE.getInstanceById('data[content]'))
                        {
                            tinyMCE.execCommand('mceFocus', false, 'data[content]');
                            tinyMCE.execCommand('mceRemoveControl', false, 'data[content]');
                        }
                    }
                });
                //apply coolfieldset
                $('.coolfieldset').coolfieldset({collapsed:true});
                $("#data\\[title\\]").blur(function(){
                    if($(this).val() != '' && $("#data\\[url_id\\]").val() == ''){
                        $.post("/" + CURR_LANG + "/cms/admin/url-id",{"title":$(this).val(),"lang":$("#langFilter").val()},
                        function(data){
                            $("#data\\[url_id\\]").val(data.url_id);
                        });
                    }
                });
                //load and render categories
                loadCategories($("#data\\[type_id\\]").val(),$("#data\\[id\\]").val());
                $("#data\\[type_id\\]").change(function(){
                    loadCategories($(this).val(),$("#data\\[id\\]").val());
                });
                //teaser image dialog
                var teaserImageDims = {
                    maxwidth: 150,
                    minwidth: 150,
                    maxheight: 150,
                    minheight: 150
                };
                //read dims from type definition
                if(typeId && typeEditData[typeId] && typeEditData[typeId].teaserImageDims){
                    teaserImageDims = typeEditData[typeId].link;
                }
                var opts = {
                    fileWebRoot: fileWebRoot,
                    initPath: dialog.find("#data\\[data\\]\\[teaser_image\\]").val(),
                    extensions: "gif,png,jpg,jpeg"
                };
                jQuery.extend(opts,teaserImageDims);
                dialog.find("#data\\[data\\]\\[teaser_image\\]").imagebrowserdialog(opts).hfbImagePath();
                //run custom type processing function
                if(typeId && typeEditData[typeId] && typeEditData[typeId].fn && typeof typeEditFunctions[typeEditData[typeId].fn] == 'function'){
                    typeEditFunctions[typeEditData[typeId].fn](dialog);
                }
            },
            onClose: function(success){
                tinyMCE.execCommand('mceRemoveControl', false, 'data[content]');
                if(success){
                    updateList();
                }
            },
            width: 'auto',
            height: 'auto'
        });
    }

    /**
     * Load and render categories
     */
    function loadCategories(typeId,pageId){
        $.get(sprintf('/%s/cms/admin/categories/type_id/%s/page_id/%s',CURR_LANG,$("#data\\[type_id\\]").val(),$("#data\\[id\\]").val()), function(data){
            //console.log(data);
            $("#categoriesPanel").html(renderCategories(data.categories,data.checked));
        });
    }

    /**
     * recursive render categories based on loaded array
     */
    function renderCategories(categories,checkedCategories){
        var length = categories.length, result = '', category = null, i = 0, j = 0, checked='';

        if(!length){
            return result;
        }

        for(i = 0; i < length; i++){
            category = categories[i];
            for(j = 0; j < category.level; j++){
                result += '&nbsp;&nbsp;&nbsp;&nbsp;';
            }
            if($.inArray(category.id, checkedCategories) >= 0){
                checked = 'checked="checked"';
            }
            else{
                checked = '';
            }
            result += '<input id="category_' + category.id + '" name="data[categories][]" type="checkbox" ' + checked + ' value="' + category.id  + '" /> \n\
                       <label style="display:inline;margin-top:5px;" for="category_' + category.id + '">' + category.name + '</label><br />';
            if(category.pages){
                result += renderCategories(category.pages,checkedCategories);
            }
        }

        return result;
    }
    
    /**
     * recursive render categories based on loaded array
     */
    function renderCategoriesFilter(categories){
        var length = categories.length, result = '', category = null, i = 0, j = 0, checked='';

        if(!length){
            return result;
        }
        for(i = 0; i < length; i++){
            category = categories[i];
            result += '<option value="' + category.id + '" style="padding-left:'+category.level * 10 +'px;"  >'+category.name+'</option>';
            if(category.pages){
                result += renderCategoriesFilter(category.pages);
            }
        }

        return result;
    }
    
    var listUrl = '/' + CURR_LANG + '/cms/admin/page-list/?langFilter=<?php echo $this->defaultLang;?>';
    if(singleType){
        listUrl += '&typeFilter=' + pageType.id ;
        getCategoriesFilter(pageType.id); 
    }
    initList(listUrl,{},function(me,data){
        $("#listContainer").find("a.edit").click(function(){
            editDialog($(this).data('id'),$(this).data('type_id'));
            return false;
        })
        //DELETE ajax action call
        $("#listContainer").find("a.delete").click(function(){
            if(!window.confirm("<?php echo $this->translate('Are you sure you want to delete this content item?\nThis operation has no undo. We recommend unpublishing this content instead of deleting.');?>")){
                return false;
            }
            $.ajax({
                type: "POST",
                data: {"page_id":$(this).data('id')},
                url: '/' + CURR_LANG + '/' + typeDeleteData[$(this).data('type_id')]['link'],
                success: function(data) {
                    if(data['success']){
                        if(data['message']){
                            $.flashMessenger(data['message'],{clsName:"ok"});
                        }
                        //reload list
                        updateList();
                    }
                    else{
                        if(data['message']){
                            $.flashMessenger(data['message'],{clsName:"err"});
                        }
                    }
                },
                error: function(data) {
                    alert(_('An error has occured retrieving data!'));
                }
            })
            return false;
        })
    });
    function getCategoriesFilter(typeId){
        $.get(sprintf('/%s/cms/admin/categories/type_id/%s',CURR_LANG,typeId), function(data){
            //console.log(data);
            $('#categoryFilter').empty();
            if(renderCategoriesFilter(data.categories) != ''){
                $("#categoryFilter").append('<option value="" selected="selected"><?php echo $this->translate('Select Category');?></option>'+renderCategoriesFilter(data.categories));
                $('#category').show();
            }else
                $('#category').hide();
        });
    }
    //init select filter
    $(document).ready(function(){
        //type dialog
        $( "#typeDialog" ).dialog({
            autoOpen: false,
            modal: true,
            buttons: {
                "OK": function() {
                    var typeId = $("#typeDialogSelect").val();
                    if(typeId){
                        editDialog(null,typeId);
                        $(this).dialog("close");
                    }
                    else{
                        alert('Please select a type.');
                    }
                },
                Cancel: function() {
                    $(this).dialog("close");
                }
            },
            close: function() {
            }
        });

        $("#langFilter").change(function(){
            updateList('langFilter',$(this).val());
        });
        $("#typeFilter").change(function(){
            if($(this).val()!= ''){
                getCategoriesFilter($(this).val());
            }else{
                 $('#category').hide();
            }
            updateList('typeFilter',$(this).val());
        });
        $('#categoryFilter').change(function(){
            updateList('categoryFilter',$(this).val());
        });
        $("#statusFilter").change(function(){
            updateList('statusFilter',$(this).val());
        });
        $("#menuFilter").change(function(){
            updateList('menuFilter',$(this).val());
        });        
        $(".add").click(function(){
            if(singleType){
                editDialog(null,pageType.id);
            }
            else{
                $("#typeDialog").dialog("open");
            }
            //editDialog(null);
            return false;
        });

        //include special javascript for each type
        for (var typeId in typeEditData) {
            var typeObject = typeEditData[typeId];
            if(typeObject.file && typeObject.file != ''){
                include(typeObject.file);
            }
        }
    });
</script>
<div class="hcms_content_top">
    <h1><?php echo $this->translate($singleType?$pageType->get_name():'Content'); ?> <span class="hcms_button"><a href="#" style="margin:6px 0 0 0;" class="add button"><?php echo $this->translate('Add new'); ?></a></span></h1>
    <span class="hcms_search">
        <input name="searchFilter" id="searchFilter" type="text" value="" />
        <span class="hcms_button"><a href="#" id="searchExecute"><?php echo $this->translate("Search"); ?></a></span>
    </span>
</div>
<div class="hcms_content">
    <div class="language">
        <?php if($this->singleLang === false) {?>
        <select id="langFilter" name="langFilter">
            <?php echo $this->langOptions($this->languages,$this->defaultLang,true);?>
        </select>
        <?php
        }
        if(!$singleType) {?>
        <select id="typeFilter" name="typeFilter" style="width: 180px;">
            <option value="" selected="selected"><?php echo $this->translate('Select Content Type');?></option>
            <?php foreach ($this->types as $type) { ?>
            <option value="<?php echo $type->get_id();?>"><?php echo $this->translate($type->get_name());?></option>
                <?php }?>
        </select>
        <?php }?>
        <select id="statusFilter" name="statusFilter">
            <option value="" selected="selected"><?php echo $this->translate('Select Status');?></option>
            <option value="published"><?php echo $this->translate("Published");?></option>
            <option value="draft"><?php echo $this->translate("Draft");?></option>
        </select>
        <span id="category" style="display:none">
            <select id="categoryFilter" name="categoryFilter">
                <option value="" selected="selected"><?php echo $this->translate('Select Category');?></option>
            </select>
        </span>
        <?php echo $this->cmsMenuSelect(array(
            'id'    => 'menuFilter',
            'name'  => 'menuFilter',
            'default_text'  => 'Select menu item',
            'attr'  => array(
                'style' => 'width: 300px'
            )
        ));?>         
        <!--<span class="hcms_button"><a href="#">Filter</a></span>-->
    </div>
    <table class="hcms_table adminList" width="100%">
        <thead>
            <tr>
                <th><a href="#" class="sort" data-column="id"><?php echo $this->translate('ID');?><b></b></a></th>
                <th><a href="#" class="sort" data-column="title"><?php echo $this->translate('Title');?><b></b></a></th>
                <th><a href="#" class="sort" data-column="code"><?php echo $this->translate('Code');?><b></b></a></th>
                <th><a href="#" class="sort" data-column="url_id"><?php echo $this->translate('URL ID');?><b></b></a></th>
                <th><a href="#" class="sort" data-column="type_name"><?php echo $this->translate('Type');?><b></b></a></th>
                <th><a href="#" class="sort" data-column="user_name"><?php echo $this->translate('User');?><b></b></a></th>
                <th><a href="#" class="sort" data-column="status"><?php echo $this->translate('Status');?><b></b></a></th>
                <th><a href="#" class="sort" data-column="posted"><?php echo $this->translate('Posted');?><b></b></a></th>
            </tr>
        </thead>
        <tbody id="listContainer">
        </tbody>
    </table>
    <div id="pager"></div>
</div>
<script type="text/html" id="records_tpl">
<% if (rows.length > 0){
    var rowClass = 'odd';
        %>
    <% for ( var i = 0; i < rows.length; i++ ){
        rowClass = (i % 2 == 0)? 'even':'odd';
            %>
        <tr class="<%=rowClass%>">
            <td><%=rows[i].id%></td>
            <td>
                <%=rows[i].title%>
                        <ul class="hcms_menu_actions">
                        <li><a href="#" class="edit" data-id="<%=rows[i].id%>" data-type_id="<%=rows[i].type_id%>"><?php echo $this->translate('Edit');?></a></li>                     
                                                                    
                        <% if (rows[i].type_name != "Content Block" && rows[i].type_name != "Image Slider") { %>
                            <li><a href="<%=rows[i].url%>" target="_blank" class="view" data-id="<%=rows[i].id%>"><?php echo $this->translate('View Page');?></a></li>
                        <% } %>
                       
                        <% if (typeDeleteData[rows[i].type_id] && typeDeleteData[rows[i].type_id]['link']){ %><li> <a href="#" class="delete" data-id="<%=rows[i].id%>" data-type_id="<%=rows[i].type_id%>"><?php echo $this->translate('Delete');?></a></li><% } %>
                        </ul>
                        </td>
            <td>
                <%=rows[i].code%>
                        </td>
            <td>
                <%=rows[i].url_id%>
                        </td>
            <td>
                <%=rows[i].type_name%>
                        </td>
            <td>
                <%=rows[i].user_name%>
                        </td>
            <td>
                <%=rows[i].status%>
                        </td>
            <td>
                <%=rows[i].posted%>
                        </td>
                        </tr>
    <% } %>
<% } %>
</script>
<div title="<?php echo $this->translate('Choose Content Type');?>" id="typeDialog" style="display: none">
    <select id="typeDialogSelect" name="typeDialogSelect">
        <?php foreach ($this->types as $type) { ?>
        <option value="<?php echo $type->get_id();?>"><?php echo $this->translate($type->get_name());?></option>
            <?php }?>
    </select>
</div>